import json
from genealogy_class import Person

gopal_31 = Person("Gopal", nepali_name="गोपाल", birth_year=1622)
ram_bhadra_32 = Person("Ram Bhadra", nepali_name="रामभद्र")
govinda_33 = Person("Govinda", nepali_name="गोविन्द")
prajapati_33 = Person("Prajapati", nepali_name="प्रजापति", birth_year=1650, comment="1677 Birta (Land Grant) from ShreeNivas Malla")
chamu_33 = Person("Chamu", nepali_name="चमु")
gautam_34 = Person("Gautam", nepali_name="गौतम")
Gangaram_34 = Person("Gangaram", nepali_name="गंगाराम")
Bhrigu_34 = Person("Bhrigu", nepali_name="भृगु")
laxmidhar_35 = Person("Laxmidhar", nepali_name="लक्ष्मीधर")
ramchandra_35 = Person("RamChandra", nepali_name="रामचन्द्र")
devhari_kancha_35 = Person("DevHari", nepali_name="देवहरि")
laxminarayan_36 = Person("LaxmiNarayan", nepali_name="लक्ष्मीनारायण")
VidyaNanda_37 = Person("VidyaNanda", nepali_name="विद्यानन्द")
DharmaNanda_38 = Person("DharmaNanda", nepali_name="धर्मनन्द")
HariLal_39 = Person("HariLal", nepali_name="हरिलाल")
ShivaNidhi_40 = Person("ShivaNidhi", nepali_name="शिवनिधि")
GedLal_41 = Person("GedLal", nepali_name="गेदलाल")
Lekhnath_41 = Person("LekhNath", nepali_name="लेखनाथ")
Premnath_41 = Person("PremNath", nepali_name="प्रेमनाथ")
RamChandra_35 = Person("RamChandra", nepali_name="रामचन्द्र")
Ratan_36 = Person("Ratan", nepali_name="रतन")
Nini_37 = Person("Nini", nepali_name="निनी")
VijayaNanda_38 = Person("VijayaNanda", nepali_name="विजयनन्द")
GauriShankar_39 = Person("GauriShankar", nepali_name="गौरीशंकर")
Eknath_42 = Person("EkNath", nepali_name="एक्नाथ")
Ram_42 = Person("Ram", nepali_name="राम")
Krishna_42 = Person("Krishna", nepali_name="कृष्ण")
Badri_42 = Person("Badri", nepali_name="बद्री")
VishwoNath_42 = Person("VishwoNath", nepali_name="विश्वनाथ")
AatmaRam_42 = Person("AatmaRam", nepali_name="आत्मराम")
Ananta_43 = Person("Ananta", nepali_name="अनन्त")
Harihar_43 = Person("Harihar", nepali_name="हरिहर")
Binod_43 = Person("Binod", nepali_name="विनोद", birth_year=1974)
Pramod_43 = Person("Pramod", nepali_name="प्रमोद")
Amod_43 = Person("Ammod", nepali_name="अमोद")
Arun_43 = Person("Arun", nepali_name="अरुण")
ShivaNath_43 = Person("ShivaNath", nepali_name="शिवनाथ")
Deepak_43 = Person("Deepak", nepali_name="दीपक")
Diwakar_43 = Person("Diwakar", nepali_name="दिवाकर")
Praveen_44 = Person("Praveen", nepali_name="प्रवीण")
Vivek_44 = Person("Vivek", nepali_name="विवेक")
Prashant_44 = Person("Prashant", nepali_name="प्रशान्त")
Rambhadra_36 = Person("Rambhadra", nepali_name="रामभद्र")
Ghanashyam_37 = Person("Ghanashyam", nepali_name="घनश्याम")
ShivaDutta_38 = Person("ShivaDutta", nepali_name="शिवदत्त")
BishnuDutta_38 = Person("BishnuDutta", nepali_name="विष्णुदत्त")
RamDutta_38 = Person("RamDutta", nepali_name="रामदत्त", place="Chasidol")
HariDutta_38 = Person("HariDutta", nepali_name="हरिदत्त")
Padmalochan_39 = Person("Padmalochan", nepali_name="पद्मलोचन")
Buddhinath_39 = Person("Buddhinath", nepali_name="बुद्धिनाथ")
Laxminath_39 = Person("Laxminath", nepali_name="लक्ष्मीनाथ")
Jeewanath_39 = Person("Jeewanath", nepali_name="जीवनाथ")
Kashinath_39 = Person("Kashinath", nepali_name="काशीनाथ")
Chakrapani_40 = Person("Chakrapani", nepali_name="चक्रपाणि")
Dandapani_40 = Person("Dandapani", nepali_name="दण्डपाणि")
GuruPrasad_41 = Person("GuruPrasad", nepali_name="गुरुप्रसाद")
Gunaraj_41 = Person("Gunaraj", nepali_name="गुणराज")
Ramanath_41 = Person("Ramanath", nepali_name="रामनाथ")
Balaram_41 = Person("Balaram", nepali_name="बलराम")
Dilliram_41 = Person("Dilliram", nepali_name="दिल्लीराम")
Toyanath_41 = Person("Toyanath", nepali_name="तोयनाथ")
KrishnaPrasad_41 = Person("KrishnaPrasad", nepali_name="कृष्णप्रसाद")
SitaRam_42 = Person("SitaRam", nepali_name="सीताराम")
Purushottam_43 = Person("Purushottam", nepali_name="पुरुषोत्तम")
Basanta_43 = Person("Basanta", nepali_name="बसन्त")
Bishwonath_43 = Person("Bishwonath", nepali_name="विश्वनाथ")
Damodar_43 = Person("Damodar", nepali_name="दामोदर")
Dhruva_42 = Person("Dhruva", nepali_name="ध्रुव")
Ishwori_42 = Person("Ishwori", nepali_name="ईश्वरी")
Suryamani_42 = Person("Suryamani", nepali_name="सूर्यमणि")
Janardan_42 = Person("Janardan", nepali_name="जनार्दन")
Raghu_42 = Person("Raghu", nepali_name="रघु")
Sudarshan_42 = Person("Sudarshan", nepali_name="सुदर्शन")
Gokul_42 = Person("Gokul", nepali_name="गोकुल")
Madan_42 = Person("Madan", nepali_name="मदन")
Madhav_42 = Person("Madhav", nepali_name="माधव")
Parshuram_42 = Person("Parshuram", nepali_name="परशुराम")
Rishiram_43 = Person("Rishiram", nepali_name="ऋषिराम")
Rajan_43 = Person("Rajan", nepali_name="राजन")
Chiranjibi_43 = Person("Chiranjibi", nepali_name="चिरञ्जीवी")
Uttam_43 = Person("Uttam", nepali_name="उत्तम")
Narottam_43 = Person("Narottam", nepali_name="नरोत्तम", birth_year=1983)
Mahesh_43 = Person("Mahesh", nepali_name="महेश")
Badibilas_40 = Person("Badibilas", nepali_name="बदिबिलास")
Bavanath_40 = Person("Bavanath", nepali_name="बवनाथ")
Naranath_40 = Person("Naranath", nepali_name="नरनाथ")
GaneshDutta_40 = Person("GaneshDutta", nepali_name="गणेशदत्त", birth_year=1889)
Bhuminanda_41 = Person("Bhuminanda", nepali_name="भूमिनन्द")
Buddhinath_41 = Person("Buddhinath", nepali_name="बुद्धिनाथ")
Angirash_41 = Person("Angirash", nepali_name="अंगिरस", birth_year=1906)
Dillinath_42 = Person("Dillinath", nepali_name="दिल्लीनाथ")
Basudev_42 = Person("Basudev", nepali_name="वासुदेव")
Debarshi_42 = Person("Debarshi", nepali_name="देवर्षि")
Mukunda_42 = Person("Mukunda", nepali_name="मुकुन्द")
Bishnugopal_42 = Person("Bishnugopal", nepali_name="विष्णुगोपाल")
Kedar_42 = Person("Kedar", nepali_name="केदार")
Hari_42 = Person("Hari", nepali_name="हरि")
Parasar_42 = Person("Parasar", nepali_name="पराशर")
Ram_43 = Person("Ram", nepali_name="राम")
Laxman_43 = Person("Laxman", nepali_name="लक्ष्मण")
Ramhari_43 = Person("Ramhari", nepali_name="रामहरि")
Haribol_43 = Person("Haribol", nepali_name="हरिबोल")
Anup_43 = Person("Anup", nepali_name="अनुप")
Sanod_43 = Person("Sanod", nepali_name="सनोद")
Suresh_43 = Person("Suresh", nepali_name="सुरेश")
Dinesh_43 = Person("Dinesh", nepali_name="दिनेश")
Narayan_43 = Person("Narayan", nepali_name="नारायण", birth_year=1955)
Bhagawan_43 = Person("Bhagawan", nepali_name="भगवान", birth_year=1961)
Pushpa_43 = Person("Pushpa", nepali_name="पुष्प", birth_year=1967)
Madhusudan_43 = Person("Madhu", nepali_name="मधुसुदन")
Kalyan_43 = Person("Kalyan", nepali_name="कल्याण", birth_year=1986)
Sudhir_43 = Person("Sudhir", nepali_name="सुधीर")
Prabakar_43 = Person("Prabakar", nepali_name="प्रभाकर")
Sunil_43 = Person("Sunil", nepali_name="सुनिल")
Ajij_44 = Person("Ajij", nepali_name="अजिज")
Amish_44 = Person("Amish", nepali_name="अमिश")
Ashok_44 = Person("Ashok", nepali_name="अशोक")
Anup_44 = Person("Anup", nepali_name="अनुप")
Anil_44 = Person("Anil", nepali_name="अनिल")
Sujan_44 = Person("Sujan", nepali_name="सुजन")
Ajay_44 = Person("Ajay", nepali_name="अजय")
Anish_44 = Person("Anish", nepali_name="अनिश")
Manish_44 = Person("Manish", nepali_name="मनिश")
Aaditya_44 = Person("Aaditya", nepali_name="आदित्य")
Aashish_44 = Person("Aashish", nepali_name="आशिष", birth_year=1983)
Pravesh_44 = Person("Pravesh", nepali_name="प्रवेश", birth_year=1991)
Niraj_44 = Person("Niraj", nepali_name="निरज", birth_year=1991)
Suraj_44 = Person("Suraj", nepali_name="सुरज", birth_year=1991)
Kushal_44 = Person("Kushal", nepali_name="कुशल", birth_year=1995)
Aayan_45 = Person("Aayan", nepali_name="आयान", birth_year=2017)
Adwik_45 = Person("Adwik", nepali_name="अद्विक", birth_year=2019)
Samyog_44 = Person("Samyog", nepali_name="संयोग")
DevHari_Kancha_35 = Person("DevHari", nepali_name="देवहरि")
Rishi_36 = Person("Rishi", nepali_name="ऋषि")
HariNarayan_37 = Person("HariNarayan", nepali_name="हरिनारायण")
ShreeLal_38 = Person("ShreeLal", nepali_name="श्रीलाल")
RamNath_38 = Person("RamNath", nepali_name="रामनाथ")
Narandutta_39 = Person("Narandutta", nepali_name="नरदत्त")
Kedarnath_39 = Person("Kedarnath", nepali_name="केदारनाथ")
Balbhadra_40 = Person("Balabhadra", nepali_name="बलभद्र")
Devhari_41 = Person("Devahari", nepali_name="देवहरी")
Lokraj_42 = Person("Lokaraj", nepali_name="लोकराज")
Dadhilal_40 = Person("Dadhilal", nepali_name="दधिलाल")
Sahadutta_41 = Person("Sahadutta", nepali_name="सहदत्त")
Damodar_42 = Person("Damodar", nepali_name="दामोदर")
Sadananda_43 = Person("Sadananda", nepali_name="सदानन्द")
Homraj_43 = Person("Homraj", nepali_name="होमराज")
Kulbahadur_43 = Person("Kulbahadur", nepali_name="कुलबहादुर")
Balkrishna_43 = Person("Balkrishna", nepali_name="बालकृष्ण")
Pushparaj_44 = Person("Pushraj", nepali_name="पुष्पराज")
Aatmanath_44 = Person("Aatmanath", nepali_name="आत्मनाथ")
Kirtinath_44 = Person("Kirtinath", nepali_name="कीर्तिनाथ")
Rajaram_44 = Person("Rajaram", nepali_name="राजाराम")
Balmiki_44 = Person("Balmiki", nepali_name="वाल्मीकि")
Upendra_44 = Person("Upendra", nepali_name="उपेन्द्र")
Raju_44 = Person("Raju", nepali_name="राजु")
Saroj_44 = Person("Saroj", nepali_name="सरोज")
Suraj_44_2 = Person("Suraj", nepali_name="सुरज")
Sudeep_44 = Person("Sudeep", nepali_name="सुदीप")
Ramraj_45 = Person("Ramraj", nepali_name="रामराज")
Manoj_45 = Person("Manoj", nepali_name="मनोज")
ShyamKrishna_45 = Person("ShyamKrishna", nepali_name="श्यामकृष्ण")
Pramod_45 = Person("Pramod", nepali_name="प्रमोद")
Sudan_45 = Person("Sudan", nepali_name="सुदन")
Suman_45 = Person("Suman", nepali_name="सुमन")
Naniram_45 = Person("Naniram", nepali_name="नानीराम")
Dharmaraj_45 = Person("Dharmaraj", nepali_name="धर्मराज")
Kulraj_45 = Person("Kulraj", nepali_name="कुलराज")
Kapil_45 = Person("Kapil", nepali_name="कपिल")
Kashiram_35 = Person("Kashiram", nepali_name="काशीराम")
Kapil_35 = Person("Kapil", nepali_name="कपिल")
Gopal_35 = Person("Gopal", nepali_name="गोपाल")
Jayanarayan_35 = Person("Jayanarayan", nepali_name="जयनारायण")
Kamalpati_36 = Person("Kamalapati", nepali_name="कमलपति")
Prajapati_37 = Person("Prajapati", nepali_name="प्रजापति")
Punyashil_37 = Person("Punyashil", nepali_name="पुण्यशील")
Krishnananda_37 = Person("Krishnananda", nepali_name="कृष्णनन्द")
Basudev_37 = Person("Bashudev", nepali_name="वासुदेव")
DevNarayan_38 = Person("DevNarayan", nepali_name="देवनारायण")
Basistha_38 = Person("Basistha", nepali_name="वसिष्ठ")
Bishwamitra_38 = Person("Bishamitra", nepali_name="विश्वामित्र")
Parmananda_38 = Person("Parmananda", nepali_name="परमानन्द")
Ganapati_39 = Person("Ganapati", nepali_name="गणपति")
Ramchandra_39 = Person("Ramchandra", nepali_name="रामचन्द्र")
Me_laxman_39 = Person("Me_laxman", nepali_name="मे लक्ष्मण")
ShreeKanta_39 = Person("ShreeKanta", nepali_name="श्रीकान्त")
Ramakanta_39 = Person("Ramakanta", nepali_name="रामकान्त")
Narandutta_40 = Person("Narandutta", nepali_name="नरदत्त")
NandaLal_41 = Person("NandaLal", nepali_name="नन्दलाल")
Prabhunath_41 = Person("Prabhunath", nepali_name="प्रभुनाथ")
Chudamani_41 = Person("Chudamani", nepali_name="चूडामणि")
Thakurnath_41 = Person("Thakurnath", nepali_name="ठाकुरनाथ")
KeshavRaj_41 = Person("KeshavRaj", nepali_name="केशवराज")
Lilanath_41 = Person("Lilanath", nepali_name="लीलानाथ")
Pashupati_42 = Person("Pashupati", nepali_name="पशुपति")
Ramchandra_42 = Person("Ramchandra", nepali_name="रामचन्द्र")
Gopal_42 = Person("Gopal", nepali_name="गोपाल")
Govinda_42 = Person("Govinda", nepali_name="गोविन्द")
Hariprasad_42 = Person("Hariprasad", nepali_name="हरिप्रसाद")
Padmanav_42 = Person("Padmanav", nepali_name="पद्मनव")
Madhusudan_42 = Person("Madhusudan", nepali_name="मधुसुदन")
Mitraprasad_42 = Person("Mitraprasad", nepali_name="मित्रप्रसाद")
Damodar_43_2 = Person("Damodar", nepali_name="दामोदर")
Balaram_43 = Person("Balaram", nepali_name="बलराम")
Mukunda_43 = Person("Mukunda", nepali_name="मुकुन्द")
Shyamkrishna_43 = Person("Shyamkrishna", nepali_name="श्यामकृष्ण")
Madhusudan_43_2 = Person("Madhusudan", nepali_name="मधुसुदन", place="बल्थली")
Shivaram_43 = Person("Shivaram", nepali_name="शिवराम")
Shreedhar_43 = Person("Shreedhar", nepali_name="श्रीधर")
Sashidhar_43 = Person("Sashidhar", nepali_name="सशिधर")
Diwakar_43_2 = Person("Diwakar", nepali_name="दिवाकर")
Suresh_43_2 = Person("Suresh", nepali_name="सुरेश")
Mahesh_43_2 = Person("Mahesh", nepali_name="महेश")
Dinesh_43_2 = Person("Dinesh", nepali_name="दिनेश")
Nirmal_44 = Person("Nirmal", nepali_name="निर्मल")
Nirjan_44 = Person("Nirjan", nepali_name="निर्जन")
Brihaspati_44 = Person("Brihaspati", nepali_name="बृहस्पति")
Ekdev_44 = Person("Ekdev", nepali_name="एकदेव")
Sudip_44 = Person("Sudip", nepali_name="सुदीप")
Sudu_44 = Person("Sudu", nepali_name="सुदु")
Manish_44 = Person("Manish", nepali_name="मनिश")
Nandikeshar_40 = Person("Nandikeshar", nepali_name="नन्दिकेशर")
Udayananda_40 = Person("Udayananda", nepali_name="उदयनन्द")
Ramananda_38 = Person("Ramananda", nepali_name="रामानन्द")
Taranath_41 = Person("Taranath", nepali_name="तारानाथ")
Thakurnath_41_2 = Person("Thakurnath", nepali_name="ठाकुरनाथ")
DharmaNanda_39 = Person("DharmaNanda", nepali_name="धर्मनन्द")
Shivadutta_39 = Person("Shivadutta", nepali_name="शिवदत्त")
GaneshPrasad_42 = Person("GaneshPrasad", nepali_name="गणेशप्रसाद")
Ganapati_42 = Person("Ganapati", nepali_name="गणपति")
Kedarnath_42 = Person("Kedarnath", nepali_name="केदारनाथ")
Manorath_40 = Person("Manorath", nepali_name="मनोरथ")
Chandrakanta_40 = Person("Chandrakanta", nepali_name="चन्द्रकान्त")
DharmaNanda_43 = Person("DharmaNanda", nepali_name="धर्मनन्द")
TikaPrasad_43 = Person("TikaPrasad", nepali_name="टीकाप्रसाद")
BadriPrasad_43 = Person("BadriPrasad", nepali_name="बद्रीप्रसाद")
Ramnath_43 = Person("Ramnath", nepali_name="रामनाथ")
Haribansha_41 = Person("Haribansha", nepali_name="हरिवंश")
Kashinath_41 = Person("Kashinath", nepali_name="काशीनाथ")
Madhusudan_44 = Person("Madhusudan", nepali_name="मधुसुदन")
Raju_44 = Person("Raju", nepali_name="राजु")
Raghunath_44 = Person("Raghunath", nepali_name="रघुनाथ")
Mohan_44 = Person("Mohan", nepali_name="मोहन")
Navin_44 = Person("Navin", nepali_name="नवीन")
Kumar_44 = Person("Kumar", nepali_name="कुमार")
Deepak_44 = Person("Deepak", nepali_name="दीपक")
Bhola_42 = Person("Bhola", nepali_name="भोला")
Bashudev_42 = Person("Bashudev", nepali_name="वासुदेव")
Dillinath_42_2 = Person("Dillinath", nepali_name="दिल्लीनाथ")
Bishnuhari_42 = Person("Bishnuhari", nepali_name="विष्णुहरि")
RamPrasad_43 = Person("RamPrasad", nepali_name="रामप्रसाद")
Chiranjibi_43_2 = Person("Chiranjibi", nepali_name="चिरञ्जीवी")
Kishor_43 = Person("Kishor", nepali_name="किशोर")
Rajkumar_43 = Person("Ramkumar", nepali_name="रामकुमार")
Deepak_43_2 = Person("Deepak", nepali_name="दीपक")
Shreedhar_43_2 = Person("Shreedhar", nepali_name="श्रीधर")
Manoj_44 = Person("Manoj", nepali_name="मनोज")
Bijay_44 = Person("Bijay", nepali_name="विजय")
Pramod_44 = Person("Pramod", nepali_name="प्रमोद")
Niranjan_44 = Person("Niranjan", nepali_name="निरञ्जन")
Jeewan_44 = Person("Jeewan", nepali_name="जीवन")
Suraj_44_3 = Person("Suraj", nepali_name="सुरज")
#page 34
Agnidhar_35 = Person("Agnidhar", nepali_name="अग्निधर")
Satyadhar_36 = Person("Satyadhar", nepali_name="सत्यधर")
Gangadhar_36 = Person("Gangadhar", nepali_name="गंगाधर")
DevNarayan_37 = Person("DevNarayan", nepali_name="देवनारायण")
Punyashil_37_2 = Person("Punyashil", nepali_name="पुण्यशील")
Ramu_37 = Person("Ramu", nepali_name="रामु")
Prayagdut_38 = Person("Prayagdut", nepali_name="प्रयागदत्त")
Kashinath_39_2 = Person("Kashinath", nepali_name="काशीनाथ")
Gokul_38 = Person("Gokul", nepali_name="गोकुल")
Baijanath_38 = Person("Baijanath", nepali_name="बैजनाथ")
Birbhadra_39 = Person("Birbhadra", nepali_name="बीरभद्र")
Katakaba_40 = Person("Katakaba", nepali_name="कटकबा")
Makarananda_39 = Person("Makarananda", nepali_name="मकरानन्द")
Shumsheraba_40 = Person("Shumasheraba", nepali_name="शुमशेरबा")
HariNarayan_40 = Person("HariNarayan", nepali_name="हरिनारायण")
Laxminath_40 = Person("Laxminath", nepali_name="लक्ष्मीनाथ")
Jeewanath_40 = Person("Jeewanath", nepali_name="जीवनाथ")
Gopal_41 = Person("Gopal", nepali_name="गोपाल")
Lalav_41 = Person("Lalav", nepali_name="ललव")
Khadgav_41 = Person("Khadgav", nepali_name="खड्गव")
Padmav_41 = Person("Padmav", nepali_name="पद्मव")
Laxmikanta_41 = Person("Laxminkanta", nepali_name="लक्ष्मीकान्त")
Bhojraj_41 = Person("Bhojraj", nepali_name="भोजराज")
Shankar_41 = Person("Shankar", nepali_name="शंकर")
Keshav_41 = Person("Keshav", nepali_name="केशव")
Hariprasad_41 = Person("Hariprasad", nepali_name="हरिप्रसाद")
Ganeshav_42 = Person("Ganeshav", nepali_name="गणेशव")
Deepak_42 = Person("Deepak", nepali_name="दीपक")
Shreedhar_42 = Person("Shreedhar", nepali_name="श्रीधर")
Rajesh_42 = Person("Rajesh", nepali_name="राजेश")
Jeewan_42 = Person("Jeewan", nepali_name="जीवन")
Shrawan_42 = Person("Shrawan", nepali_name="श्रवण")
Bimal_42 = Person("Bimal", nepali_name="बिमल")
BadriPrasad_42 = Person("BadriPrasad", nepali_name="बद्रीप्रसाद")
Kedar_42_1 = Person("Kedar", nepali_name="केदार")
Shyam_42 = Person("Shyam", nepali_name="श्याम")
Jagannath_42 = Person("Jagannath", nepali_name="जगन्नाथ")
Balaram_42 = Person("Balaram", nepali_name="बलराम")
Belav_43 = Person("Belav", nepali_name="बेलव")
Ohmav_43 = Person("Ohmav", nepali_name="ओमव")
Ramsharan_43 = Person("Ramsharan", nepali_name="रामशरण")
Harisharan_43 = Person("Harisharan", nepali_name="हरिशरण")
Abhishek_43 = Person("Abhishek", nepali_name="अभिषेक")
Maniram_43 = Person("Maniram", nepali_name="मणिराम")
Uddhav_43 = Person("Uddhav", nepali_name="उद्धव")
Uttam_43 = Person("Uttam", nepali_name="उत्तम")
Dwarika_43 = Person("Dwarika", nepali_name="द्वारिका")
KrishnaPrasad_43 = Person("KrishnaPrasad", nepali_name="कृष्णप्रसाद")
Purushottam_43_2 = Person("Purushottam", nepali_name="पुरुषोत्तम")
Uday_43 = Person("Uday", nepali_name="उदय")
Hirav_44 = Person("Hirav", nepali_name="हिरव")
Harisharan_44 = Person("Harisharan", nepali_name="हरिशरण")
Shivasharan_44 = Person("Shivasharan", nepali_name="शिवशरण")
Sashindra_44 = Person("Sashindra", nepali_name="सशिन्द्र")
Krishnasharan_44 = Person("Krishnasharan", nepali_name="कृष्णशरण")
LabaPrasad_44 = Person("LabaPrasad", nepali_name="लवप्रसाद")
Pitabmar_41 = Person("Pitabmar", nepali_name="पिताम्बर")
Muktinath_41 = Person("Muktinath", nepali_name="मुक्तिनाथ")
Minanath_41 = Person("Minanath", nepali_name="मीननाथ")
Harischandra_42 = Person("Harischandra", nepali_name="हरिश्चन्द्र")
Hareram_42 = Person("Shreeram", nepali_name="हरेराम")
Harisharan_42 = Person("Harisharan", nepali_name="हरिशरण")
Harinath_42 = Person("Harinath", nepali_name="हरिनाथ")
Sharadprasad_42 = Person("Sharadprasad", nepali_name="शरदप्रसाद")
Bali_34 = Person("Bali", nepali_name="बलि")
Moksheswor_35 = Person("Moksheswor", nepali_name="मोक्षेश्वर")
Sreeram_35 = Person("Sreeram", nepali_name="श्रीराम")
Ramkrishna_35 = Person("Ramkrishna", nepali_name="रामकृष्ण", death_year=1822, place="Lubhu")
Bamdev_35 = Person("Bamdev", nepali_name="बमदेव")
Chandramadi_36 = Person("Chandramadi", nepali_name="चन्द्रमदन")
Tikaram_37 = Person("Tikaram", nepali_name="टीकाराम")
Laxmidhar_37 = Person("Laxmidhar", nepali_name="लक्ष्मीधर")
Liladhar_37 = Person("Liladhar", nepali_name="लीलाधर")
Haribamsha_38 = Person("Haribas", nepali_name="हरिबास")
Shivanath_38 = Person("Shivanath", nepali_name="शिवनाथ")
Shyamlal_39 = Person("Shyamlal", nepali_name="श्यामलाल")
Laxminath_39_2 = Person("Laxminath", nepali_name="लक्ष्मीनाथ")
Narayan_39 = Person("Narayan", nepali_name="नारायण")
VishwoNath_39 = Person("VishwoNath", nepali_name="विश्वनाथ")
Makardwoj_39 = Person("Makardwoj", nepali_name="मकरद्वोज")
Ganapati_39_2 = Person("Ganapati", nepali_name="गणपति")
Shreebilas_40 = Person("Shreebilas", nepali_name="श्रीबिलास")
Hitakanta_40 = Person("Hitakanta", nepali_name="हितकान्त")
Gajabinod_40 = Person("Gajabinod", nepali_name="गजबिनोद")
Nandalal_40 = Person("Nandalal", nepali_name="नन्दलाल")
Sashidhar_40 = Person("Sashidhar", nepali_name="सशिधर")
Chiranjibi_40 = Person("Chiranjibi", nepali_name="चिरञ्जीवी")
Sadananda_41 = Person("Sadananda", nepali_name="सदानन्द")
Narandutta_41 = Person("Narandutta", nepali_name="नरदत्त")
Chandrakanta_41 = Person("Chandrakanta", nepali_name="चन्द्रकान्त")
Chabilal_41 = Person("Chabilal", nepali_name="चबिलाल")
Tankanath_41 = Person("Tankanath", nepali_name="टंकनाथ")
Khomnath_41 = Person("Khomnath", nepali_name="खोमनाथ")
VishwoNath_41 = Person("VishwoNath", nepali_name="विश्वनाथ")
Sukadev_41 = Person("Sukadev", nepali_name="सुकदेव")
Gangasagar_41 = Person("Gangasagar", nepali_name="गंगासागर")
Gopilal_42 = Person("Gopilal", nepali_name="गोपी लाल")
Hemnath_42 = Person("Hemnath", nepali_name="हेमनाथ")
Gopal_42_2 = Person("Gopal", nepali_name="गोपाल")
Rishi_42 = Person("Rishi", nepali_name="ऋषि")
Laxminath_42 = Person("Laxminath", nepali_name="लक्ष्मीनाथ")
GopiKrishna_42 = Person("GopiKrishna", nepali_name="गोपीकृष्ण")
Bhojraj_42 = Person("Bhojraj", nepali_name="भोजराज")
Muktinath_42 = Person("Muktinath", nepali_name="मुक्तिनाथ")
Narayan_42 = Person("Narayan", nepali_name="नारायण")
SashyamPrasad_43 = Person("SashyamPrasad", nepali_name="सश्यामप्रसाद")
RamKrishna_43 = Person("RamKrishna", nepali_name="रामकृष्ण")
ShyamPrasad_43 = Person("ShyamPrasad", nepali_name="श्यामप्रसाद")
Madhu_43_2 = Person("Madhu", nepali_name="मधु")
Hari_43 = Person("Hari", nepali_name="हरि")
Bharat_43 = Person("Hari", nepali_name="भरत")
Ishwor_43 = Person("Ishwor", nepali_name="ईश्वर")
Niranjan_43 = Person("Niranjan", nepali_name="निरञ्जन")
Gokul_43 = Person("Gokul", nepali_name="गोकुल")
PurnaPrasad_43 = Person("PurnaPrasad", nepali_name="पूर्णप्रसाद")
Saroj_43 = Person("Saroj", nepali_name="सरोज")
Bhairav_43 = Person("Bhairav", nepali_name="भैरव")
GyanPrasad_43 = Person("GyanPrasad", nepali_name="ज्ञानप्रसाद")
BinodPrasad_43 = Person("BinodPrasad", nepali_name="विनोदप्रसाद")
Byapak_44 = Person("Byapak", nepali_name="ब्यापक")
Binay_44 = Person("Binay", nepali_name="विनय")
Prajyan_44 = Person("Prajyan", nepali_name="प्रज्ञान")
Pawan_44 = Person("Pawan", nepali_name="पवन")
Murari_44 = Person("Murari", nepali_name="मुरारी")
Taranath_40 = Person("Taranath", nepali_name="तारानाथ")
SivaPrasad_41 = Person("SivaPrasad", nepali_name="शिवप्रसाद")
SitaRam_41 = Person("SitaRam", nepali_name="सीताराम")
Dasrath_42 = Person("Dasrath", nepali_name="दशरथ")
Gokul_42_2 = Person("Gokul", nepali_name="गोकुल")
Ashok_42 = Person("Ashok", nepali_name="अशोक")
Surya_42 = Person("Surya", nepali_name="सूर्य")
ChandikaPrasad_42 = Person("ChandikaPrasad", nepali_name="चण्डिकाप्रसाद")
Niranjan_42 = Person("Niranjan", nepali_name="निरञ्जन")
UllasPunja_43 = Person("UllasPunja", nepali_name="उल्लासपुजा")
PurnaBhadra_38 = Person("PurnaBhadra", nepali_name="पूर्णभद्र")
HariLal_39_2 = Person("HariLal", nepali_name="हरिलाल")
GauriKanta_39 = Person("GauriKanta", nepali_name="गौरीकान्त")
Modnath_39 = Person("Modnath", nepali_name="मोदनाथ")
Dilliram_40 = Person("Dilliram", nepali_name="दिल्लीराम")
Chakrapani_40_2 = Person("Chakrapani", nepali_name="चक्रपाणि")
GaneshPrasad_40 = Person("GaneshPrasad", nepali_name="गणेशप्रसाद")
RatnaPrasad_40 = Person("RatnaPrasad", nepali_name="रत्नप्रसाद")
Dandapani_40_2 = Person("Dandapani", nepali_name="दण्डपाणि")
PadmaNarayan_40 = Person("PadmaNarayan", nepali_name="पद्मनारायण")
BishnuPrasad_41 = Person("BishnuPrasad", nepali_name="विष्णुप्रसाद")
DurgaPrasad_41 = Person("DurgaPrasad", nepali_name="दुर्गाप्रसाद")
Sudarshan_41 = Person("Sudarshan", nepali_name="सुदर्शन")
KrishnaPrasad_41_2 = Person("KrishnaPrasad", nepali_name="कृष्णप्रसाद")
Gopal_41_2 = Person("Gopal", nepali_name="गोपाल")
Uddhav_42 = Person("Uddhav", nepali_name="उद्धव")
Shyam_42_1 = Person("Shyam", nepali_name="श्याम")
KrishnaPrasad_42 = Person("KrishnaPrasad", nepali_name="कृष्णप्रसाद")
Baikuntha_42 = Person("Baikuntha", nepali_name="वैकुण्ठ")
Ramesh_42 = Person("Ramesh", nepali_name="रमेश")
Dinesh_42 = Person("Dinesh", nepali_name="दिनेश")
Saroj_42 = Person("Saroj", nepali_name="सरोज")
Basanta_42 = Person("Basanta", nepali_name="बसन्त")
Niraj_42 = Person("Niraj", nepali_name="निरज")
Rajan_42 = Person("Rajan", nepali_name="राजन")
Rajesh_42_1 = Person("Rajesh", nepali_name="राजेश")
Bhusan_42 = Person("Bhusan", nepali_name="भूषण")
Ashok_42_2 = Person("Ashok", nepali_name="अशोक")
Shreeram_42_1 = Person("Shreeram", nepali_name="श्रीराम")
Mukunda_42_1 = Person("Mukunda", nepali_name="मुकुन्द")
Madhuwan_42 = Person("Madhuwan", nepali_name="मधुवन")
Madhav_42_2 = Person("Madhav", nepali_name="माधव")
Deepak_43_3 = Person("Deepak", nepali_name="दीपक")
Suchit_43 = Person("Suchit", nepali_name="सुचित")
Pawan_43_2 = Person("Pawan", nepali_name="पवन")
Sourya_43 = Person("Sourya", nepali_name="सौर्य")
Saurav_43 = Person("Saurav", nepali_name="सौरव")
Santosh_43 = Person("Santosh", nepali_name="सन्तोष")
Saroj_43_2 = Person("Saroj", nepali_name="सरोज")
Mahesh_43_3 = Person("Mahesh", nepali_name="महेश")
Anupam_43 = Person("Anupam", nepali_name="अनुपम")
Pashupati_38 = Person("Pashupati", nepali_name="पशुपति")
Ganapati_38 = Person("Ganapati", nepali_name="गणपति")
Padmanath_39 = Person("Padmanath", nepali_name="पद्मनाथ")
Kashinath_39_2 = Person("Kashinath", nepali_name="काशीनाथ")
Umanath_39 = Person("Umanath", nepali_name="उमानाथ")
Kalu_40 = Person("Kalu", nepali_name="कालु")
Muktinath_40 = Person("Muktinath", nepali_name="मुक्तिनाथ")
Sadananda_40 = Person("Sadananda", nepali_name="सदानन्द")
Emanath_40 = Person("Emanath", nepali_name="एमानाथ")
Bhimnath_40 = Person("Bhimnath", nepali_name="भीमनाथ")
Narayan_40 = Person("Narayan", nepali_name="नारायण")
Sukadev_41_2 = Person("Sukadev", nepali_name="सुकदेव")
Dalbahadur_41 = Person("Dalbahadur", nepali_name="दलबहादुर")
Gopal_41_3 = Person("Gopal", nepali_name="गोपाल")
Ramjeev_41 = Person("Ramjeev", nepali_name="रामजीव")
Shyamjeev_41 = Person("Shyamjeev", nepali_name="श्यामजीव")
Sahadev_41 = Person("Sahadev", nepali_name="सहदेव")
Arjun_41 = Person("Arjun", nepali_name="अर्जुन")
Prahlad_41 = Person("Prahlad", nepali_name="प्रह्लाद")
Kamal_41 = Person("Kamal", nepali_name="कमल")
Ram_41 = Person("Ram", nepali_name="राम")
Krishna_41 = Person("Krishna", nepali_name="कृष्ण")
Bharat_41 = Person("Bharat", nepali_name="भरत")
Nanibabu_42 = Person("Nanibabu", nepali_name="नानीबाबु")
Rameshor_42 = Person("Rameshor", nepali_name="रामेश्वर")
Achyut_42 = Person("Achyut", nepali_name="अच्युत")
Shreeram_42_2 = Person("Shreeram", nepali_name="श्रीराम")
ShyamKrishna_42 = Person("ShyamKrishna", nepali_name="श्यामकृष्ण")
ShyamKaji_42 = Person("ShyamKaji", nepali_name="श्यामकाजी")
HariKrishna_42 = Person("HariKrishna", nepali_name="हरिकृष्ण")
Sundar_42 = Person("Sundar", nepali_name="सुन्दर")
Bidur_42 = Person("Bidur", nepali_name="विदुर")
Purushottam_42 = Person("Purushottam", nepali_name="पुरुषोत्तम")
Krishnasharan_42 = Person("Krishnasharan", nepali_name="कृष्णशरण")
Jayaraj_42 = Person("Jayaraj", nepali_name="जयराज")
Sudama_42 = Person("Sudama", nepali_name="सुदामा")
Suresh_42 = Person("Suresh", nepali_name="सुरेश")
Govinda_42_1 = Person("Govinda", nepali_name="गोविन्द")
Sambhu_42 = Person("Sambhu", nepali_name="शम्भु")
Nabaraj_43 = Person("Nabaraj", nepali_name="नवराज")
Chitra_43 = Person("Chitra", nepali_name="चित्र")
Habbu_43 = Person("Habbu", nepali_name="हब्बु")
Kailash_43 = Person("Kailash", nepali_name="कैलाश")
Umesh_43 = Person("Umesh", nepali_name="उमेश")
Radheshyam_43 = Person("Radheshyam", nepali_name="राधेश्याम")
Ganashyam_43 = Person("Ganashyam", nepali_name="गणश्याम")
Dinesh_43_3 = Person("Dinesh", nepali_name="दिनेश")
Su_Ramnath_36 = Person("Su_Ramnath", nepali_name="सु रामनाथ")
Prabhunath_36 = Person("Prabhunath", nepali_name="प्रभुनाथ")
Ranganath_36 = Person("Ranganath", nepali_name="रंगनाथ")
Siromani_36 = Person("Siromani", nepali_name="सिरोमणि")
Trilokya_36 = Person("Trilokya", nepali_name="त्रिलोक्क")
Su_Brajmohan_37 = Person("Su_Brajmohan", nepali_name="सु ब्रजमोहन")
Yagyanidhi_37 = Person("Yagyanidhi", nepali_name="यज्ञनिधि")
Ganapati_37 = Person("Ganapati", nepali_name="गणपति")
Krishnamohan_38 = Person("Krishnamohan", nepali_name="कृष्णमोहन")
Lalitmohan_38 = Person("Lalitmohan", nepali_name="ललितमोहन")
Chaturmohan_38 = Person("Chaturmohan", nepali_name="चतुर्मोहन")
Chandramohan_38 = Person("Chandramohan", nepali_name="चन्द्रमोहन")
Harimohan_39 = Person("Harimohan", nepali_name="हरिमोहन")
Rudramohan_39 = Person("Rudramohan", nepali_name="रुद्रामोहन")
Lokmohan_39 = Person("Lokmohan", nepali_name="लोकमोहन")
Ganeshmohan_39 = Person("Ganeshmohan", nepali_name="गणेशमोहन")
Premmohan_39 = Person("Premmohan", nepali_name="प्रेममोहन")
Yogmohan_39 = Person("Yogmohan", nepali_name="योगमोहन")
Buddhimohan_39 = Person("Buddhimohan", nepali_name="बुद्धिमोहन")
RamPrasad_40 = Person("RamPrasad", nepali_name="रामप्रसाद")
Narayan_40_2 = Person("Narayan", nepali_name="नारायण")
Dhruvamohan_40 = Person("Dhruvamohan", nepali_name="ध्रुवमोहन")
Tejmohan_40 = Person("Tejmohan", nepali_name="तेजमोहन")
Harshamohan_40 = Person("Harshamohan", nepali_name="हर्षमोहन")
Yankamohan_40 = Person("Yankamohan", nepali_name="यंकमोहन")
Padmanav_41 = Person("Padmanav", nepali_name="पद्मनव")
Binod_41 = Person("Binod", nepali_name="विनोद")
Pramod_41 = Person("Pramod", nepali_name="प्रमोद")
Amrit_41 = Person("Amrit", nepali_name="अमृत")
Damodar_41 = Person("Damodar", nepali_name="दामोदर")
Radhakrishna_41 = Person("Radhakrishna", nepali_name="राधाकृष्ण")
Bamshidhar_41 = Person("Bamshidhar", nepali_name="बंशीधर")
Yadav_41 = Person("Yadav", nepali_name="यादव")
Suraj_41 = Person("Suraj", nepali_name="सुरज")
Suman_41 = Person("Suman", nepali_name="सुमन")
Sanjay_41 = Person("Sanjay", nepali_name="सञ्जय")
Sunod_42 = Person("Sunod", nepali_name="सुनोद")
Sushan_42 = Person("Sushan", nepali_name="सुशान")
Ramesh_42_2 = Person("Ramesh", nepali_name="रमेश")
Pradeep_42 = Person("Pradeep", nepali_name="प्रदीप")
Prakash_42 = Person("Prakash", nepali_name="प्रकाश")
Kumud_42 = Person("Kumud", nepali_name="कुमुद")
Enoj_42 = Person("Enoj", nepali_name="एनोज")
Manoj_42 = Person("Manoj", nepali_name="मनोज")
Anil_42 = Person("Anil", nepali_name="अनिल")
Brahmananda_38 = Person("Brahmananda", nepali_name="ब्रह्मानन्द")
Gaurinath_38 = Person("Gaurinath", nepali_name="गौरिनाथ")
Ambarnath_38 = Person("Ambarnath", nepali_name="अम्बरनाथ")
Rewatiraman_38 = Person("Rewatiraman", nepali_name="रेवतीरमण")
Ramakanta_38 = Person("Ramakanta", nepali_name="रामकान्त")
Pradhumna_38 = Person("Pradhumna", nepali_name="प्रधुम्न")
Kabikulkeshari_38 = Person("Kabikulkeshari", nepali_name="कविकुलकेशरी")
Sadananda_38 = Person("Sadananda", nepali_name="सदानन्द")
Kashinath_38 = Person("Kashinath", nepali_name="काशीनाथ")
Tejprasad_38 = Person("Tejprasad", nepali_name="तेजप्रसाद")
Yojmohan_39 = Person("Yogmohan", nepali_name="योगमोहन")
KrishnaDutta_39 = Person("KrishnaDutta", nepali_name="कृष्णदत्त")
Pitabmar_39 = Person("Pitabmar", nepali_name="पिताम्बर")
VishwoNath_39_2 = Person("VishwoNath", nepali_name="विश्वनाथ")
Chiranjibi_39 = Person("Chiranjibi", nepali_name="चिरञ्जीवी")
Tejprasad_39 = Person("Tejprasad", nepali_name="तेजप्रसाद")
Maila_39 = Person("Maila", nepali_name="मैला")
Jeevprasad_39 = Person("Jeevprasad", nepali_name="जीवप्रसाद")
Tankanath_39 = Person("Tankanath", nepali_name="टंकनाथ")
YudhPrasad_39 = Person("YudhPrasad", nepali_name="युद्धप्रसाद")
Bhure_39 = Person("Bhure", nepali_name="भुरे")
Gwage_39 = Person("Gwage", nepali_name="ग्वागे")
Jhankanath_39 = Person("Jhankanath", nepali_name="झंकनाथ")
Homnath_39 = Person("Homnath", nepali_name="होमनाथ")
MayaPrasad_39 = Person("MayaPrasad", nepali_name="मायाप्रसाद")
TejPrasad_40 = Person("TejPrasad", nepali_name="तेजप्रसाद")
Tejpinath_40 = Person("Tejpinath", nepali_name="तेजपिनाथ")
KrishnaPrasad_40 = Person("KrishnaPrasad", nepali_name="कृष्णप्रसाद")
DeviPrasad_40 = Person("DeviPrasad", nepali_name="देवीप्रसाद")
PremRaj_40 = Person("PremRaj", nepali_name="प्रेमराज")
PushpaRaj_40 = Person("PushpaRaj", nepali_name="पुष्पराज")
Thute_40 = Person("Thute", nepali_name="थुते")
Ramji_41 = Person("Ramji", nepali_name="रामजी")
Ramraj_41 = Person("Ramraj", nepali_name="रामराज")
Laxman_41 = Person("Laxman", nepali_name="लक्ष्मण")
Vidyaraj_42 = Person("Vidyaraj", nepali_name="विद्याराज")
Nabaraj_42 = Person("Nabaraj", nepali_name="नवराज")
Raju_42 = Person("Raju", nepali_name="राजु")
Ratna_42 = Person("Ratna", nepali_name="रत्न")
Vijay_42 = Person("Vijay", nepali_name="विजय")
Narad_36 = Person("Narad", nepali_name="नारद")
Dinakar_36 = Person("Dinakar", nepali_name="दिनाकर")
Prabhakar_36 = Person("Prabhakar", nepali_name="प्रभाकर")
Antare_36 = Person("Antare", nepali_name="अन्तरे")
Kancha_36 = Person("Kancha", nepali_name="कञ्चा")
Laxmikanta_37 = Person("Laxmikanta", nepali_name="लक्ष्मीकान्त", place="Ekhudol")
Chandrasekhar_37 = Person("Chandrasekhar", nepali_name="चन्द्रशेखर")
Baburam_37 = Person("Baburam", nepali_name="बाबुराम")
Nandalal_38 = Person("Nandalal", nepali_name="नन्दलाल")
Harinanda_38 = Person("Harinanda", nepali_name="हरिनन्द")
Chandrakanta_38 = Person("Chandrakanta", nepali_name="चन्द्रकान्त")
Agnidhar_39 = Person("Agnidhar", nepali_name="अग्निधर")
Yadunath_39 = Person("Yadunath", nepali_name="यदुनाथ")
Gurudutta_39 = Person("Gurudutta", nepali_name="गुरुदत्त")
Dharmananda_39 = Person("Dharmananda", nepali_name="धर्मानन्द")
Bedimadhav_39 = Person("Bedimadhav", nepali_name="बेदिमाधव")
Govinda_39 = Person("Govinda", nepali_name="गोविन्द")
Damodar_39 = Person("Damodar", nepali_name="दामोदर")
Jagannath_40 = Person("Jagannath", nepali_name="जगन्नाथ")
Ramji_39 = Person("Ramji", nepali_name="रामजी")
Bholanath_39 = Person("Bholanath", nepali_name="भोलानाथ")
Madhav_39 = Person("Madhav", nepali_name="माधव")
Nabaraj_39 = Person("Nabaraj", nepali_name="नवराज")
Binod_41_2 = Person("Binod", nepali_name="विनोद")
Bijayanath_41 = Person("Bijayanath", nepali_name="विजयनाथ")
Pramod_41_2 = Person("Pramod", nepali_name="प्रमोद")
Subodh_41 = Person("Subodh", nepali_name="सुबोध")
Nayanath_41 = Person("Nayanath", nepali_name="नयनाथ")
Samanath_41 = Person("Samanath", nepali_name="समानाथ")
Brihaspati_41 = Person("Brihaspati", nepali_name="बृहस्पति")
Rukhmanath_41 = Person("Rukhmanath", nepali_name="रुखमनाथ")
Grihanath_41 = Person("Grihanath", nepali_name="गृहनाथ")
Shankar_41_2 = Person("Shankar", nepali_name="शंकर")
Deepak_41 = Person("Deepak", nepali_name="दीपक")
Sudarshan_41_2 = Person("Sudarshan", nepali_name="सुदर्शन")
Nirmal_41 = Person("Nirmal", nepali_name="निर्मल")
Ajay_42 = Person("Ajay", nepali_name="अजय")
Sanjay_42 = Person("Sanjay", nepali_name="सञ्जय")
Pradeep_42_1 = Person("Pradeep", nepali_name="प्रदीप")
Uttam_42 = Person("Uttam", nepali_name="उत्तम")
Bodhnath_42 = Person("Bodhnath", nepali_name="बोधनाथ")
Heli_42 = Person("Heli", nepali_name="हेली")
Heman_42 = Person("Heman", nepali_name="हेमन")
Sabij_42 = Person("Sabij", nepali_name="सबिज")
Anish_42 = Person("Anish", nepali_name="अनिश")
Manish_42 = Person("Manish", nepali_name="मनिश")
Damodar_37 = Person("Damodar", nepali_name="दामोदर")
Mitralal_37 = Person("Mitralal", nepali_name="मित्रलाल")
Sadananda_37 = Person("Sadananda", nepali_name="सदानन्द")
Chetnath_38 = Person("Chetnath", nepali_name="चेतनाथ")
Badri_39 = Person("Badri", nepali_name="बद्री", place="Koteshor")
Mahesh_40 = Person("Mahesh", nepali_name="महेश")
Shyamhari_40 = Person("Shyamhari", nepali_name="श्यामहरि")
Maheshwor_38 = Person("Maheshwor", nepali_name="महेश्वर")
ShivaDutta_38_2 = Person("ShivaDutta", nepali_name="शिवदत्त")
Wahaba_38 = Person("Wahaba", nepali_name="वहबा")
Birava_38 = Person("Birava", nepali_name="बिरव")
Bhairaba_38 = Person("Bhairaba", nepali_name="भैरव")
Katakaba_38 = Person("Katakaba", nepali_name="कटकबा")
Amaraba_38 = Person("Amaraba", nepali_name="अमरबा")
Bhuwaneshor_39 = Person("Bhuwaneshor", nepali_name="भुवनेश्वर")
GaneshDutta_39 = Person("GaneshDutta", nepali_name="गणेशदत्त")
ShivaPrasad_40 = Person("ShivaPrasad", nepali_name="शिवप्रसाद")
Sthaleshor_40 = Person("Sthaleshor", nepali_name="स्थलेश्वर")
Ranganath_40 = Person("Ranganath", nepali_name="रंगनाथ")
Fadindranath_40 = Person("Fadindranath", nepali_name="फदिन्द्रनाथ")
DeviPrasad_40_1 = Person("DeviPrasad", nepali_name="देवीप्रसाद")
Jhankanath_40 = Person("Jhankanath", nepali_name="झंकनाथ")
Homanath_40 = Person("Homanath", nepali_name="होमनाथ")
Kedarav_41 = Person("Kedarav", nepali_name="केदरव")
Krishnav_41 = Person("Krishnav", nepali_name="कृष्णव")
Arjunav_41 = Person("Arjunav", nepali_name="अर्जुनव")
BadriPrasad_41 = Person("BadriPrasad", nepali_name="बद्रीप्रसाद")
ShyamPrasad_41 = Person("ShyamPrasad", nepali_name="श्यामप्रसाद")
DamodarPrasad_41 = Person("DamodarPrasad", nepali_name="दामोदरप्रसाद")
Jagannath_41 = Person("Jagannath", nepali_name="जगन्नाथ")
Tarkaraj_41 = Person("Tarkaraj", nepali_name="तर्कराज")
Chiranjibi_41 = Person("Chiranjibi", nepali_name="चिरञ्जीवी")
Rishi_41 = Person("Rishi", nepali_name="ऋषि")
Hari_41 = Person("Hari", nepali_name="हरि")
Shyam_41 = Person("Shyam", nepali_name="श्याम")
Ramhari_41 = Person("Ramhari", nepali_name="रामहरि")
VishwoNath_42_1 = Person("VishwoNath", nepali_name="विश्वनाथ")
BadriPrasad_42_1 = Person("BadriPrasad", nepali_name="बद्रीप्रसाद")
Kiran_42 = Person("Kiran", nepali_name="किरण")
Ravi_42 = Person("Ravi", nepali_name="रवि")
Mani_42 = Person("Mani", nepali_name="मणि")
Kumar_42 = Person("Kumar", nepali_name="कुमार")
Jeewan_42_1 = Person("Jeewan", nepali_name="जीवन")
Diwakar_43_3 = Person("Diwakar", nepali_name="दिवाकर")
Prabhakar_43 = Person("Prabhakar", nepali_name="प्रभाकर")
Suman_43 = Person("Suman", nepali_name="सुमन")
Sagar_43 = Person("Sagar", nepali_name="सागर")
Sudhakar_43 = Person("Sudhakar", nepali_name="सुधाकर")
Bhaskar_43 = Person("Bhaskar", nepali_name="भास्कर")
Sankar_43 = Person("Sankar", nepali_name="शंकर")
Mahesh_43_4 = Person("Mahesh", nepali_name="महेश")

#Page 45
_4 = Person("Yogmohan")
#####################################################
gopal_31.add_child(ram_bhadra_32)
ram_bhadra_32.add_childs([govinda_33, prajapati_33, chamu_33])
govinda_33.add_childs([gautam_34, Gangaram_34, Bhrigu_34, Bali_34])
gautam_34.add_childs([laxmidhar_35, ramchandra_35, devhari_kancha_35])
laxmidhar_35.add_childs([laxminarayan_36, Rambhadra_36])
laxminarayan_36.add_child(VidyaNanda_37)
VidyaNanda_37.add_child(DharmaNanda_38)
DharmaNanda_38.add_child(HariLal_39)
HariLal_39.add_child(ShivaNidhi_40)

ShivaNidhi_40.add_childs([GedLal_41, Lekhnath_41, Premnath_41])
GedLal_41.add_child(Eknath_42)
Lekhnath_41.add_childs([Ram_42, Krishna_42, Badri_42, VishwoNath_42])
Premnath_41.add_child(AatmaRam_42)
Ram_42.add_child(Ananta_43)
Krishna_42.add_childs([Harihar_43, Binod_43])
Harihar_43.add_child(Praveen_44)
Binod_43.add_child(Vivek_44)

Badri_42.add_childs([Pramod_43, Amod_43, Arun_43])
Pramod_43.add_child(Prashant_44)

VishwoNath_42.add_child(ShivaNath_43)
AatmaRam_42.add_childs([Deepak_43, Diwakar_43])

Rambhadra_36.add_child(Ghanashyam_37)
Ghanashyam_37.add_childs([ShivaDutta_38, BishnuDutta_38, RamDutta_38, HariDutta_38])
RamDutta_38.add_childs([Padmalochan_39, Buddhinath_39, Laxminath_39, Jeewanath_39, Kashinath_39])
Laxminath_39.add_childs([Chakrapani_40, Dandapani_40])
Chakrapani_40.add_childs([GuruPrasad_41, Gunaraj_41, Ramanath_41, Balaram_41, Dilliram_41])
GuruPrasad_41.add_childs([Dhruva_42, Ishwori_42])
Gunaraj_41.add_childs([Suryamani_42])
Suryamani_42.add_child(Mahesh_43)
Ramanath_41.add_childs([Janardan_42, Raghu_42])
Balaram_41.add_childs([Sudarshan_42, Gokul_42, Madan_42])
Dilliram_41.add_childs([Madhav_42, Parshuram_42])
Dhruva_42.add_childs([Rishiram_43, Rajan_43])
Ishwori_42.add_childs([Chiranjibi_43, Uttam_43, Narottam_43])

Dandapani_40.add_childs([Toyanath_41, KrishnaPrasad_41])
Toyanath_41.add_childs([SitaRam_42])
SitaRam_42.add_childs([Purushottam_43, Basanta_43, Bishwonath_43, Damodar_43])
Jeewanath_39.add_childs([Badibilas_40, Bavanath_40, Naranath_40, GaneshDutta_40])
Badibilas_40.add_childs([Bhuminanda_41, Buddhinath_41])
GaneshDutta_40.add_child(Angirash_41)
Angirash_41.add_childs([Bishnugopal_42, Kedar_42, Hariprasad_42, Parasar_42])
Dillinath_42.add_childs([Ram_43, Laxman_43])
Buddhinath_41.add_childs([Basudev_42, Debarshi_42, Mukunda_42])
Basudev_42.add_child(Ramhari_43)
Debarshi_42.add_childs([Haribol_43, Anup_43, Binod_43, Sanod_43])
Mukunda_42.add_childs([Suresh_43, Dinesh_43])

Bishnugopal_42.add_childs([Narayan_43, Bhagawan_43, Pushpa_43, Madhusudan_43])
Kedar_42.add_child(Kalyan_43)
Hari_42.add_childs([Sudhir_43, Prabakar_43])
Parasar_42.add_child(Sunil_43)

Narayan_43.add_child(Aashish_44)
Aashish_44.add_childs([Aayan_45, Adwik_45])
Kalyan_43.add_child(Samyog_44)

Bhagawan_43.add_child(Pravesh_44)
Pushpa_43.add_childs([Suraj_44, Niraj_44])
Madhusudan_43.add_child(Kushal_44)

#page 29
devhari_kancha_35.add_child(Rishi_36)
Rishi_36.add_childs([HariNarayan_37])
HariNarayan_37.add_childs([ShreeLal_38, RamNath_38])
ShreeLal_38.add_child(Narandutta_39)
RamNath_38.add_child(Kedarnath_39)

#page 30
Narandutta_39.add_child(Balbhadra_40)
Balbhadra_40.add_child(Devhari_41)
Devhari_41.add_child(Lokraj_42)
Lokraj_42.add_childs([Sadananda_43, Homraj_43, Kulbahadur_43, Balkrishna_43])
Sadananda_43.add_childs([Pushparaj_44, Aatmanath_44, Kirtinath_44, Rajaram_44])
Homraj_43.add_child(Balmiki_44)
Kulbahadur_43.add_childs([Upendra_44, Raju_44, Saroj_44, Suraj_44])
Balkrishna_43.add_child(Sudip_44)

Pushparaj_44.add_child(Ramraj_45)
Aatmanath_44.add_childs([Manoj_45, ShyamKrishna_45])
Kirtinath_44.add_childs([Pramod_45, Sudan_45, Suman_45])
Rajaram_44.add_child(Naniram_45)
Balmiki_44.add_childs([Dharmaraj_45, Kulraj_45])
Upendra_44.add_child(Kapil_45)

#Page 31
Gangaram_34.add_childs([Kashiram_35, Kapil_35, Gopal_35, Jayanarayan_35])
Kashiram_35.add_child(Kamalpati_36)
Kamalpati_36.add_childs([Prajapati_37, Punyashil_37, Krishnananda_37, Basudev_37])
Punyashil_37.add_childs([DevNarayan_38, Basistha_38, Bishwamitra_38, Parmananda_38])
Basistha_38.add_childs([Ganapati_39, Ramchandra_39, Me_laxman_39, ShreeKanta_39, Ramakanta_39])
Ganapati_39.add_childs([Narandutta_40])
Narandutta_40.add_childs([NandaLal_41, Prabhunath_41, Chudamani_41, Thakurnath_41, KeshavRaj_41, Lilanath_41])

#page 32
Chudamani_41.add_childs([Pashupati_42, Ramchandra_42, Gopal_42])
Thakurnath_41.add_childs([Govinda_42, Hariprasad_42, Padmanav_42])
KeshavRaj_41.add_childs([Madhusudan_42, Mitraprasad_42])

Pashupati_42.add_childs([Damodar_43])
Damodar_43.add_childs([Nirmal_44, Nirjan_44])
Ramchandra_42.add_childs([Balaram_43, Mukunda_43])
Balaram_43.add_childs([Brihaspati_44, Ekdev_44])
Gopal_42.add_childs([Shyamkrishna_43, Madhusudan_43])
Shyamkrishna_43.add_childs([Sudip_44, Sudu_44])
Madhusudan_43.add_child(Manish_44)

Govinda_42.add_child(Shivaram_43)
Padmanav_42.add_childs([Shreedhar_43, Sashidhar_43])
Madhusudan_43_2.add_childs([Diwakar_43_2, Suresh_43_2])
Mitraprasad_42.add_childs([Mahesh_43_2, Dinesh_43_2])

Me_laxman_39.add_childs([Nandikeshar_40, Udayananda_40])
Udayananda_40.add_childs([Taranath_41, Thakurnath_41_2])
Thakurnath_41_2.add_childs([GaneshPrasad_42, Ganapati_42, Kedarnath_42])
Krishnananda_37.add_child(Ramananda_38)
Ramananda_38.add_childs([DharmaNanda_39, Shivadutta_39])
DharmaNanda_39.add_child(Manorath_40)
Shivadutta_39.add_child(Chandrakanta_40)

Manorath_40.add_child(Haribansha_41)
Chandrakanta_40.add_child(Kashinath_41)
Haribansha_41.add_child(Bhola_42)
Kashinath_41.add_childs([Basudev_42, Dillinath_42_2, Bishnuhari_42])
Dillinath_42_2.add_childs([RamPrasad_43, Chiranjibi_43_2])
Bishnuhari_42.add_childs([Kishor_43, Rajkumar_43, Deepak_43_2, Shreedhar_43_2])
RamPrasad_43.add_childs([Manoj_44, Bijay_44])
Chiranjibi_43_2.add_childs([Pramod_44, Niranjan_44])
Kishor_43.add_childs([Jeewan_44, Suraj_44_3])
#page 34
Bhrigu_34.add_child(Agnidhar_35)
Agnidhar_35.add_childs([Satyadhar_36, Gangadhar_36])
Satyadhar_36.add_childs([DevNarayan_37, Punyashil_37_2])
Gangadhar_36.add_child(Ramu_37)
Ramu_37.add_child(Prayagdut_38)
Prayagdut_38.add_child(Kashinath_39_2)

DevNarayan_37.add_child(Gokul_38)
Punyashil_37_2.add_child(Baijanath_38)
Baijanath_38.add_childs([Birbhadra_39, Makarananda_39])
Birbhadra_39.add_childs([Katakaba_40, Shumsheraba_40])

Makarananda_39.add_childs([HariNarayan_40, Laxminath_40, Jeewanath_40])
Katakaba_40.add_childs([Gopal_41, Lalav_41])
Shumsheraba_40.add_childs([Khadgav_41, Padmanav_41])
HariNarayan_40.add_childs([Laxmikanta_41, Bhojraj_41, Shankar_41, Keshav_41])
Laxminath_40.add_child(Hariprasad_41)

#page 35
Khadgav_41.add_child(Ganeshav_42)
Shankar_41.add_childs([Deepak_42, Shreedhar_42, Rajesh_42])
Keshav_41.add_childs([Jeewan_42, Shrawan_42, Bimal_42])
Hariprasad_41.add_childs([BadriPrasad_42, Kedar_42_1, Shyam_42, Jagannath_42, Balaram_42])
Ganeshav_42.add_childs([Belav_43, Ohmav_43, Ramsharan_43, Harisharan_43])
Deepak_42.add_childs([Abhishek_43])
BadriPrasad_42.add_childs([Maniram_43, Uddhav_43, Uttam_43])
Kedar_42.add_childs([Dwarika_43, KrishnaPrasad_43])
Shyam_42.add_child(Purushottam_43_2)
Balaram_42.add_child(Uday_43)

Belav_43.add_child(Hirav_44)
Ohmav_43.add_child(Harisharan_44)
Ramsharan_43.add_childs([Shivasharan_44, Sashindra_44])
Harisharan_43.add_child(Krishnasharan_44)
Maniram_43.add_child(LabaPrasad_44)

Jeewanath_40.add_childs([Pitabmar_41, Muktinath_41, Minanath_41])
Pitabmar_41.add_childs([Harischandra_42, Hareram_42, Harisharan_42])
Minanath_41.add_childs([Harinath_42, Sharadprasad_42])

#page 36
Bali_34.add_childs([Moksheswor_35, Sreeram_35, Ramkrishna_35, Bamdev_35])
Moksheswor_35.add_child(Chandramadi_36)
Chandramadi_36.add_childs([Tikaram_37, Laxmidhar_37, Liladhar_37])
Tikaram_37.add_childs([Haribamsha_38, Shivanath_38])
Haribamsha_38.add_childs([Shyamlal_39, Laxminath_39_2, Narayan_39])
Shivanath_38.add_childs([VishwoNath_39, Makardwoj_39, Ganapati_39_2])

Shyamlal_39.add_child(Shreebilas_40)
Laxminath_39_2.add_childs([Hitakanta_40, Gajabinod_40, Nandalal_40])
Narayan_39.add_child(Sashidhar_40)
VishwoNath_39.add_child(Chiranjibi_40)

Shreebilas_40.add_childs([Sadananda_41, Narandutta_41, Chandrakanta_41])
Hitakanta_40.add_child(Chabilal_41)
Nandalal_40.add_childs([Tankanath_41, Khomnath_41, VishwoNath_41])
Chiranjibi_40.add_childs([Sukadev_41, Gangasagar_41])

#page 37
Chandrakanta_41.add_child(Gopilal_42)
Gopilal_42.add_childs([SashyamPrasad_43, RamKrishna_43])
Chabilal_41.add_childs([Hemnath_42])
Hemnath_42.add_child(ShyamPrasad_43)
Khomnath_41.add_childs([Gopal_42_2, Rishi_42])
Rishi_42.add_childs([Madhu_43_2, Hari_43, Bharat_43])

VishwoNath_41.add_child(Laxminath_42)
Laxminath_42.add_childs([Ishwor_43, Niranjan_43])
Sukadev_41.add_childs([GopiKrishna_42, Bhojraj_42])
GopiKrishna_42.add_child(Gokul_43)
Gokul_43.add_childs([Byapak_44, Binay_44])
Bhojraj_42.add_childs([PurnaPrasad_43, Saroj_43])

Gangasagar_41.add_childs([Muktinath_42, Narayan_42])
Muktinath_42.add_childs([Bhairav_43, GyanPrasad_43])
GyanPrasad_43.add_childs([Prajyan_44, Pawan_44])
BinodPrasad_43.add_child(Murari_44)

Makardwoj_39.add_child(Taranath_40)
Taranath_40.add_childs([SivaPrasad_41, SitaRam_41])
SivaPrasad_41.add_childs([Dasrath_42, Gokul_42_2, Ashok_42, Surya_42])
SitaRam_41.add_childs([ChandikaPrasad_42, Niranjan_42])
ChandikaPrasad_42.add_child(UllasPunja_43)

#Page 38
Laxmidhar_37.add_child(PurnaBhadra_38)
PurnaBhadra_38.add_childs([HariLal_39_2, GauriKanta_39, Modnath_39])
Modnath_39.add_childs([Dandapani_40_2, PadmaNarayan_40])

HariLal_39_2.add_childs([Dilliram_40, Chakrapani_40_2, GaneshPrasad_40, RatnaPrasad_40])
GaneshPrasad_40.add_childs([BishnuPrasad_41, DurgaPrasad_41, Sudarshan_41])
RatnaPrasad_40.add_childs([KrishnaPrasad_41_2, Gopal_41_2])

BishnuPrasad_41.add_childs([Uddhav_42, Shyam_42_1, KrishnaPrasad_42, Baikuntha_42])
DurgaPrasad_41.add_childs([Ramesh_42, Dinesh_42, Saroj_42, Basanta_42])
Sudarshan_41.add_childs([Niraj_42, Rajan_42, Rajesh_42_1, Bhusan_42, Ashok_42])

KrishnaPrasad_41_2.add_childs([Shreeram_42_1, Mukunda_42_1])
Gopal_41_3.add_childs([Madhuwan_42, Madhav_42_2])

Uddhav_42.add_child(Deepak_43_3)
KrishnaPrasad_42.add_child(Suchit_43)
Ramesh_42.add_child(Pawan_43_2)
Saroj_43.add_childs([Sourya_43, Saurav_43])

Shreeram_42_1.add_child(Santosh_43)
Mukunda_42_1.add_child(Saroj_43_2)
Madhuwan_42.add_childs([Mahesh_43_3, Anupam_43])