import json
from genealogy_class import Person

gopal_31 = Person("Gopal", nepali_name="गोपाल", birth_year=1622, comment="उपत्यका आउने")
ram_bhadra_32 = Person("Ram Bhadra", nepali_name="रामभद्र", comment="लुभू सिस्नेरी आउने")
govinda_33 = Person("Govinda", nepali_name="गोविन्द", comment="ठूलाघरेका पूर्वज")
prajapati_33 = Person("Prajapati", nepali_name="प्रजापति", birth_year=1650, comment="तीनघरेका पूर्वज\nसन् १६७७ मा श्रीनिवास मल्लबाट विर्ता")
chamu_33 = Person("Chamu", nepali_name="चामु", comment="तीनघरेका पूर्वज")

gautam_34 = Person("Gautam", nepali_name="गौतम")
gangaram_34 = Person("Gangaram", nepali_name="गंगाराम", place="लामाटार")
bhrigu_34 = Person("Bhrigu", nepali_name="भृगु")
laxmidhar_35 = Person("Laxmidhar", nepali_name="लक्ष्मीधर")
ramchandra_35 = Person("RamChandra", nepali_name="रामचन्द्र")
devhari_kancha_35 = Person("DevHari", nepali_name="देवहरि")
laxminarayan_36 = Person("LaxmiNarayan", nepali_name="लक्ष्मीनारायण")
vidya_nanda_37 = Person("VidyaNanda", nepali_name="विद्यानन्द")
dharma_nanda_38 = Person("DharmaNanda", nepali_name="धर्मनन्द")
hari_lal_39 = Person("HariLal", nepali_name="हरिलाल")
shiva_nidhi_40 = Person("ShivaNidhi", nepali_name="शिवनिधि")
ged_lal_41 = Person("GedLal", nepali_name="गेदलाल")
lekhnath_41 = Person("LekhNath", nepali_name="लेखनाथ(गोपाल)")
premnath_41 = Person("PremNath", nepali_name="प्रेमनाथ")
ram_chandra_35 = Person("RamChandra", nepali_name="रामचन्द्र")
ratan_36 = Person("Ratan", nepali_name="रतन")
nini_37 = Person("Nini", nepali_name="नीनी")
vijaya_nanda_38 = Person("VijayaNanda", nepali_name="विजयानन्द")
gauri_shankar_39 = Person("GauriShankar", nepali_name="गौरीशंकर")
eknath_42 = Person("EkNath", nepali_name="एकनाथ")
ram_42 = Person("Ram", nepali_name="राम")
krishna_42 = Person("Krishna", nepali_name="कृष्ण")
badri_42 = Person("Badri", nepali_name="बद्री")
bishwo_nath_42 = Person("BishwoNath", nepali_name="विश्वनाथ")
aatma_ram_42 = Person("AatmaRam", nepali_name="आत्मराम")
#page 27
ananta_43 = Person("Ananta", nepali_name="अनन्त")
harihar_43 = Person("Harihar", nepali_name="हरिहर")
binod_43 = Person("Binod", nepali_name="विनोद")
pramod_43 = Person("Pramod", nepali_name="प्रमोद")
amod_43 = Person("Ammod", nepali_name="अमोद")
arun_43 = Person("Arun", nepali_name="अरुण")
shiva_nath_43 = Person("ShivaNath", nepali_name="शिवनाथ")
deepak_43 = Person("Deepak", nepali_name="दीपक")
diwakar_43 = Person("Diwakar", nepali_name="दिवाकर")
praveen_44 = Person("Praveen", nepali_name="प्रवीन")
vivek_44 = Person("Vivek", nepali_name="विवेक")
prashant_44 = Person("Prashant", nepali_name="प्रशान्त")

rambhadra_36 = Person("Rambhadra", nepali_name="रामभद्र(बलभद्र)")
ghanashyam_37 = Person("Ghanashyam", nepali_name="घनश्याम")
shiva_dutta_38 = Person("ShivaDutta", nepali_name="शिवदत्त", place="काशी")
bishnu_dutta_38 = Person("BishnuDutta", nepali_name="विष्णुदत्त", place="काशी")
ram_dutta_38 = Person("RamDutta", nepali_name="रामदत्त", place="चसिडोल")
hari_dutta_38 = Person("HariDutta", nepali_name="हरिदत्त", place="काशी")
padmalochan_39 = Person("Padmalochan", nepali_name="पद्मलोचन")
buddhinath_39 = Person("Buddhinath", nepali_name="बुद्धिनाथ")
laxminath_39 = Person("Laxminath", nepali_name="लक्ष्मीनाथ")
jeewanath_39 = Person("Jeewanath", nepali_name="जीवनाथ")
kashinath_39 = Person("Kashinath", nepali_name="काशीनाथ")
chakrapani_40 = Person("Chakrapani", nepali_name="चक्रपाणि")
dandapani_40 = Person("Dandapani", nepali_name="दण्डपाणि")
#page 28
guru_prasad_41 = Person("GuruPrasad", nepali_name="गुरुप्रसाद")
gunaraj_41 = Person("Gunaraj", nepali_name="गुणराज")
ramanath_41 = Person("Ramanath", nepali_name="रमानाथ")
balaram_41 = Person("Balaram", nepali_name="बलराम")
dillinath_41 = Person("Dilliram", nepali_name="डिल्लीराम")
toyanath_41 = Person("Toyanath", nepali_name="तोयनाथ")
krishna_prasad_41 = Person("KrishnaPrasad", nepali_name="कृष्णप्रसाद")
madan_42 = Person("Madan", nepali_name="मदन")
gokul_42 = Person("Gokul", nepali_name="गोकुल")
madhav_42 = Person("Madhav", nepali_name="माधव")
parshuram_42 = Person("Parshuram", nepali_name="परशुराम")
sita_ram_42 = Person("SitaRam", nepali_name="सीताराम")
dhruva_42 = Person("Dhruva", nepali_name="ध्रुव")
ishwori_42 = Person("Ishwori", nepali_name="ईश्वरी")
suryamani_42 = Person("Suryamani", nepali_name="सूर्यमणि")
janardan_42 = Person("Janardan", nepali_name="जनार्दन")
raghu_42 = Person("Raghu", nepali_name="रघु")
sudarshan_42 = Person("Sudarshan", nepali_name="सुदर्शन")

rishiram_43 = Person("Rishiram", nepali_name="ऋषिराम")
rajan_43 = Person("Rajan", nepali_name="राजन")
chiranjibi_43 = Person("Chiranjibi", nepali_name="चिरञ्जीवी")
uttam_43 = Person("Uttam", nepali_name="उत्तम")
narottam_43 = Person("Narottam", nepali_name="नरोत्तम", birth_year=1983)
mahesh_43 = Person("Mahesh", nepali_name="महेश")
niranjan_43 = Person("Niranjan", nepali_name="निरञ्जन")
manohar_43 = Person("Manohar", nepali_name="मनोहर")
krishna_murari_43 = Person("Krishna Murari", nepali_name="कृष्णमुरारी")
deepak_43_2 = Person("Deepak", nepali_name="दिपक")
ashok_43 = Person("Ashok", nepali_name="अशोक")
bibek_43 = Person("Bibek", nepali_name="विवेक")
ujjwol_43 = Person("Ujjwol", nepali_name="उज्ज्वल")
dipesh_43 = Person("Dipesh", nepali_name="दिपेश")
tanka_43 = Person("Tanka", nepali_name="टंक")
dadhi_43 = Person("Dadhi", nepali_name="दधि")
rewati_43 = Person("Rewati", nepali_name="रेवती")
manoj_43 = Person("Manoj", nepali_name="मनोज")
achyut_raj_43 = Person("AchyutRaj", nepali_name="अच्युतराज")
purushottam_43 = Person("Purushottam", nepali_name="पुरुषोत्तम")
basanta_43 = Person("Basanta", nepali_name="वसन्त")
bishwonath_43 = Person("Bishwonath", nepali_name="विश्वनाथ")
damodar_43 = Person("Damodar", nepali_name="दामोदर")

badibilas_40 = Person("Badibilas", nepali_name="बदिबिलास")
bavanath_40 = Person("Bavanath", nepali_name="भवनाथ")
naranath_40 = Person("Naranath", nepali_name="नरनाथ")
ganesh_dutta_40 = Person("GaneshDutta", nepali_name="गणेशदत्त", birth_year=1889)
bhuminanda_41 = Person("Bhuminanda", nepali_name="भूमिनन्द")
buddhinath_41 = Person("Buddhinath", nepali_name="बुद्धिनाथ")
durga_41 = Person("Durga", nepali_name="दुर्गा")
angirash_41 = Person("Angirash", nepali_name="अंगिरस", birth_year=1906)
dillinath_42 = Person("Dillinath", nepali_name="दिल्लीनाथ")
basudev_42 = Person("Basudev", nepali_name="वासुदेव")
debarshi_42 = Person("Debarshi", nepali_name="देवर्षि")
mukunda_42 = Person("Mukunda", nepali_name="मुकुन्द")
bishnugopal_42 = Person("Bishnugopal", nepali_name="विष्णुगोपाल")
kedar_42 = Person("Kedar", nepali_name="केदार")
hari_42 = Person("Hari", nepali_name="हरि")
parasar_42 = Person("Parasar", nepali_name="पराशर")

ram_43 = Person("Ram", nepali_name="राम")
laxman_43 = Person("Laxman", nepali_name="लक्ष्मण")
ramhari_43 = Person("Ramhari", nepali_name="रामहरि")
haribol_43 = Person("Haribol", nepali_name="हरिबोल")
anup_43 = Person("Anup", nepali_name="अनुप")
binod_43_2 = Person("Binod", nepali_name="विनोद", birth_year=1974)
sanod_43 = Person("Sanod", nepali_name="सनोद")
suresh_43 = Person("Suresh", nepali_name="सुरेश")
dinesh_43 = Person("Dinesh", nepali_name="दिनेश")
narayan_43 = Person("Narayan", nepali_name="नारायण", birth_year=1955)
bhagawan_43 = Person("Bhagawan", nepali_name="भगवान", birth_year=1961)
pushpa_raj_43 = Person("Pushpa", nepali_name="पुष्प", birth_year=1967)
madhu_sudan_43 = Person("Madhu", nepali_name="मधुसुदन")
kalyan_43 = Person("Kalyan", nepali_name="कल्याण", birth_year=1986)
sudhir_43 = Person("Sudhir", nepali_name="सुधीर")
prabakar_43 = Person("Prabakar", nepali_name="प्रभाकर")
sunil_43 = Person("Sunil", nepali_name="सुनिल")

saroj_44 = Person("Saroj", nepali_name="सरोज")
sabin_44 = Person("Sabin", nepali_name="सविन")
suman_44 = Person("Suman", nepali_name="सुमन")
ramesh_44 = Person("Ramesh", nepali_name="रमेश")
pujan_44 = Person("Pujan", nepali_name="पुजन")

keshav_44 = Person("Keshav", nepali_name="केशव")
sanjay_44 = Person("Sanjay", nepali_name="संजय")
bimal_44 = Person("Bimal", nepali_name="विमल")
sagar_44 = Person("Sagar", nepali_name="सागर")
ajij_44 = Person("Ajij", nepali_name="अजिज")
amish_44 = Person("Amish", nepali_name="अमिश")
ashok_44 = Person("Ashok", nepali_name="अशोक")
anup_44 = Person("Anup", nepali_name="अनुप")
anil_44 = Person("Anil", nepali_name="अनिल")
sujan_44 = Person("Sujan", nepali_name="सुजन")
ajay_44 = Person("Ajay", nepali_name="अजय")
anish_44 = Person("Anish", nepali_name="अनिश")
manish_44 = Person("Manish", nepali_name="मनिश")
aaditya_44 = Person("Aaditya", nepali_name="आदित्य")
aashish_44 = Person("Aashish", nepali_name="आशिष", birth_year=1983) #myself
pravesh_44 = Person("Pravesh", nepali_name="प्रवेश", birth_year=1991)
niraj_44 = Person("Niraj", nepali_name="निरज", birth_year=1991)
suraj_44 = Person("Suraj", nepali_name="सुरज", birth_year=1991)
kushal_44 = Person("Kushal", nepali_name="कुशल", birth_year=1995)
subhanga_44 = Person("Subhanga", nepali_name="सुभांग")

aayan_45 = Person("Aayan", nepali_name="आयान", birth_year=2017)
adwik_45 = Person("Adwik", nepali_name="अद्विक", birth_year=2019)

rishi_36 = Person("Rishi", nepali_name="ऋषि")
hari_narayan_37 = Person("HariNarayan", nepali_name="हरिनारायण")
shree_lal_38 = Person("ShreeLal", nepali_name="श्रीलाल")
ram_nath_38 = Person("RamNath", nepali_name="रामनाथ")
narandutta_39 = Person("Narandutta", nepali_name="नारनदत्त")
kedarnath_39 = Person("Kedarnath", nepali_name="केदारनाथ")
balbhadra_40 = Person("Balabhadra", nepali_name="बलभद्र")
dadhilal_40 = Person("Dadhilal", nepali_name="दधिलाल")
devhari_41 = Person("Devahari", nepali_name="देवहरी")
sahadutta_41 = Person("Sahadutta", nepali_name="सहदत्त")
lokraj_42 = Person("Lokaraj", nepali_name="लोकराज")
damodar_42 = Person("Damodar", nepali_name="दामोदर")

sadananda_43 = Person("Sadananda", nepali_name="षडानन्द")
homraj_43 = Person("Homraj", nepali_name="होमराज")
kulbahadur_43 = Person("Kulbahadur", nepali_name="कुलबहादुर")
balkrishna_43 = Person("Balkrishna", nepali_name="बालकृष्ण")

pushparaj_44 = Person("Pushraj", nepali_name="पुष्पराज")
aatmanath_44 = Person("Aatmanath", nepali_name="आत्मनाथ")
kirtinath_44 = Person("Kirtinath", nepali_name="कीर्तिनाथ")
rajaram_44 = Person("Rajaram", nepali_name="राजाराम")
balmiki_44 = Person("Balmiki", nepali_name="वाल्मीकि")
upendra_44 = Person("Upendra", nepali_name="उपेन्द्र")
raju_44 = Person("Raju", nepali_name="राजु")
saroj_44_2 = Person("Saroj", nepali_name="सरोज")
suraj_44_2 = Person("Suraj", nepali_name="सुरज")
sudeep_44 = Person("Sudeep", nepali_name="सुदीप")

ramraj_45 = Person("Ramraj", nepali_name="रामराज")
manoj_45 = Person("Manoj", nepali_name="मनोज")
shyam_krishna_45 = Person("ShyamKrishna", nepali_name="श्यामकृष्ण")
pramod_45 = Person("Pramod", nepali_name="प्रमोद")
sudan_45 = Person("Sudan", nepali_name="सुदन")
suman_45 = Person("Suman", nepali_name="सुमन")
naniram_45 = Person("Naniram", nepali_name="नानीराम")
dharmaraj_45 = Person("Dharmaraj", nepali_name="धर्मराज")
kulraj_45 = Person("Kulraj", nepali_name="कुलराज")
kapil_45 = Person("Kapil", nepali_name="कपिल")

#page 31
kashiram_35 = Person("Kashiram", nepali_name="काशीराम")
kapil_35 = Person("Kapil", nepali_name="कपिल")
gopal_35 = Person("Gopal", nepali_name="गोपाल")
jayanarayan_35 = Person("Jayanarayan", nepali_name="जयनारायण")

kamalpati_36 = Person("Kamalapati", nepali_name="कमलपति")
prajapati_37 = Person("Prajapati", nepali_name="प्रजापति")
punyashil_37 = Person("Punyashil", nepali_name="पुण्यशील")
krishnananda_37 = Person("Krishnananda", nepali_name="कृष्णानन्द")
basudev_37 = Person("Bashudev", nepali_name="वासुदेव")
dev_narayan_38 = Person("DevNarayan", nepali_name="देवनारायण")
basistha_38 = Person("Basistha", nepali_name="वशिष्ठ")
bishwamitra_38 = Person("Bishamitra", nepali_name="विश्वामित्र")
parmananda_38 = Person("Parmananda", nepali_name="परमानन्द")

ganapati_39 = Person("Ganapati", nepali_name="गणपति")
ramchandra_39 = Person("Ramchandra", nepali_name="रामचन्द्र")
laxman_39 = Person("laxman(Major)", nepali_name="लक्ष्मण(मेजर)", comment="मेजर")
shree_kanta_39 = Person("ShreeKanta", nepali_name="श्रीकान्त")
ramakanta_39 = Person("Ramakanta", nepali_name="रमाकान्त")

narandutta_40 = Person("Narandutta", nepali_name="नारनदत्त")
nanda_lal_41 = Person("NandaLal", nepali_name="नन्दलाल")
prabhunath_41 = Person("Prabhunath", nepali_name="प्रभुनाथ")
chudamani_41 = Person("Chudamani", nepali_name="चूडामणि")
thakurnath_41 = Person("Thakurnath", nepali_name="ठाकुरनाथ")
keshav_raj_41 = Person("KeshavRaj", nepali_name="केशवराज")
lilanath_41 = Person("Lilanath", nepali_name="लीलानाथ")
#page 32
pashupati_42 = Person("Pashupati", nepali_name="पशुपति")
ramchandra_42 = Person("Ramchandra", nepali_name="रामचन्द्र")
gopal_42 = Person("Gopal", nepali_name="गोपाल")
govinda_42 = Person("Govinda", nepali_name="गोविन्द")
hari_prasad_42 = Person("Hariprasad", nepali_name="हरिप्रसाद")
padmanath_42 = Person("Padmanav", nepali_name="पद्मनाथ")
madhusudan_42 = Person("Madhusudan", nepali_name="मधुसुदन", place="बल्थली")
mitraprasad_42 = Person("Mitraprasad", nepali_name="मित्रप्रसाद")

damodar_43_2 = Person("Damodar", nepali_name="दामोदर")
balaram_43 = Person("Balaram", nepali_name="बलराम")
mukunda_43 = Person("Mukunda", nepali_name="मुकुन्द")
shyamkrishna_43 = Person("Shyamkrishna", nepali_name="श्यामकृष्ण")
madhusudan_43_2 = Person("Madhusudan", nepali_name="मधुसुदन")
shivaram_43 = Person("Shivaram", nepali_name="शिवराम")
shreedhar_43 = Person("Shreedhar", nepali_name="श्रीधर")
sashidhar_43 = Person("Sashidhar", nepali_name="शशिधर")
diwakar_43_2 = Person("Diwakar", nepali_name="दिवाकर")
suresh_43_2 = Person("Suresh", nepali_name="सुरेश")
mahesh_43_2 = Person("Mahesh", nepali_name="महेश")
dinesh_43_2 = Person("Dinesh", nepali_name="दिनेश")

nirmal_44 = Person("Nirmal", nepali_name="निर्मल")
nirjan_44 = Person("Nirjan", nepali_name="निर्जन")
brihaspati_44 = Person("Brihaspati", nepali_name="बृहस्पति")
ekdev_44 = Person("Ekdev", nepali_name="एकदेव")
sudeep_44_2 = Person("Sudip", nepali_name="सुदीप")
sudu_44 = Person("Sudu", nepali_name="सुदु")
manish_44_2 = Person("Manish", nepali_name="मनिश")

nandikeshar_40 = Person("Nandikeshar", nepali_name="नन्दिकेशर")
udayananda_40 = Person("Udayananda", nepali_name="उदयानन्द")

taranath_41 = Person("Taranath", nepali_name="तारानाथ")
thakurnath_41_2 = Person("Thakurnath", nepali_name="ठाकुरनाथ")
ganesh_prasad_42 = Person("GaneshPrasad", nepali_name="गणेशप्रसाद")
ganapati_42 = Person("Ganapati", nepali_name="गणपति")
kedarnath_42 = Person("Kedarnath", nepali_name="केदारनाथ")

ramananda_38 = Person("Ramananda", nepali_name="रामानन्द")
dharma_nanda_39 = Person("DharmaNanda", nepali_name="धर्मनन्द")
shivadutta_39 = Person("Shivadutta", nepali_name="शिवदत्त")
manorath_40 = Person("Manorath", nepali_name="मनोरथ")
chandrakanta_40 = Person("Chandrakanta", nepali_name="चन्द्रकान्त")
haribansha_41 = Person("Haribansha", nepali_name="हरिवंश")
kashinath_41 = Person("Kashinath", nepali_name="काशीनाथ")

dharma_nanda_43 = Person("DharmaNanda", nepali_name="धर्मानन्द")
tika_prasad_43 = Person("TikaPrasad", nepali_name="टीकाप्रसाद")
badri_prasad_43 = Person("BadriPrasad", nepali_name="बद्रीप्रसाद")
ramnath_43 = Person("Ramnath", nepali_name="रामनाथ")

madhusudan_44 = Person("Madhusudan", nepali_name="मधुसुदन")
raju_44_2 = Person("Raju", nepali_name="राजु")
raghunath_44 = Person("Raghunath", nepali_name="रघुनाथ")
mohan_44 = Person("Mohan", nepali_name="मोहन")
navin_44 = Person("Navin", nepali_name="नवीन")
kumar_44 = Person("Kumar", nepali_name="कुमार")
deepak_44 = Person("Deepak", nepali_name="दीपक")

bhola_42 = Person("Bhola", nepali_name="भोला")
bashudev_42 = Person("Bashudev", nepali_name="वासुदेव")
dillinath_42_2 = Person("Dillinath", nepali_name="दिल्लीनाथ")
bishnuhari_42 = Person("Bishnuhari", nepali_name="विष्णुहरि")

ram_prasad_43 = Person("RamPrasad", nepali_name="रामप्रसाद")
chiranjibi_43_2 = Person("Chiranjibi", nepali_name="चिरञ्जीवी")
kishor_43 = Person("Kishor", nepali_name="किशोर")
rajkumar_43 = Person("Ramkumar", nepali_name="राजकुमार")
deepak_43_3 = Person("Deepak", nepali_name="दीपक")
shreedhar_43_2 = Person("Shreedhar", nepali_name="श्रीधर")

manoj_44 = Person("Manoj", nepali_name="मनोज")
bijay_44 = Person("Bijay", nepali_name="विजय")
pramod_44 = Person("Pramod", nepali_name="प्रमोद")
niranjan_44 = Person("Niranjan", nepali_name="निरञ्जन")
jeewan_44 = Person("Jeewan", nepali_name="जीवन")
suraj_44_3 = Person("Suraj", nepali_name="सुरज")

#page 34
agnidhar_35 = Person("Agnidhar", nepali_name="अग्निधर")
satyadhar_36 = Person("Satyadhar", nepali_name="सत्यधर")
gangadhar_36 = Person("Gangadhar", nepali_name="गंगाधर")
dev_narayan_37 = Person("DevNarayan", nepali_name="देवनारायण")
punyashil_37_2 = Person("Punyashil", nepali_name="पुण्यशील")
ramu_37 = Person("Ramu", nepali_name="रामु")
gokul_38 = Person("Gokul", nepali_name="गोकुल")
baijanath_38 = Person("Baijanath", nepali_name="बैजनाथ")
prayagdut_38 = Person("Prayagdut", nepali_name="प्रयागदत्त")

birbhadra_39 = Person("Birbhadra", nepali_name="बीरभद्र")
makarananda_39 = Person("Makarananda", nepali_name="मकरानन्द")
kashinath_39_2 = Person("Kashinath", nepali_name="काशीनाथ")

kataka_bahadur_40 = Person("KatakaBahadur", nepali_name="कटकबहादुर")
shumsher_bahadur_40 = Person("ShumasherBahadur", nepali_name="शुमशेरबहादुर")
hari_narayan_40 = Person("HariNarayan", nepali_name="हरिनारायण")
laxminath_40 = Person("Laxminath", nepali_name="लक्ष्मीनाथ")
jeewanath_40 = Person("Jeewanath", nepali_name="जीवनाथ")

gopal_41 = Person("Gopal", nepali_name="गोपाल")
lal_bahadur_41 = Person("LalBahadur", nepali_name="लाल")
khadgav_bahadur_41 = Person("KhadgaBahadur", nepali_name="खड्गबहादुर")
padma_bahadur_41 = Person("PadmaBahadur", nepali_name="पद्मबहादुर")
laxmikanta_41 = Person("Laxminkanta", nepali_name="लक्ष्मीकान्त")
bhojraj_41 = Person("Bhojraj", nepali_name="भोजराज")
shankar_41 = Person("Shankar", nepali_name="शंकर")
keshav_41 = Person("Keshav", nepali_name="केशव")
hariprasad_41 = Person("Hariprasad", nepali_name="हरिप्रसाद")

ganesh_bahadur_42 = Person("GaneshBahadur", nepali_name="गणेशबहादुर")
deepak_42_2 = Person("Deepak", nepali_name="दीपक")
shreedhar_42 = Person("Shreedhar", nepali_name="श्रीधर")
rajesh_42 = Person("Rajesh", nepali_name="राजेश")
jeewan_42 = Person("Jeewan", nepali_name="जीवन")
shrawan_42 = Person("Shrawan", nepali_name="श्रवण")
bimal_42 = Person("Bimal", nepali_name="बिमल")
badri_prasad_42 = Person("BadriPrasad", nepali_name="बद्रीप्रसाद")
kedar_42_2 = Person("Kedar", nepali_name="केदार")
shyam_42 = Person("Shyam", nepali_name="श्याम")
jagannath_42 = Person("Jagannath", nepali_name="जगन्नाथ")
balaram_42 = Person("Balaram", nepali_name="बलराम")

bel_bahadur_43 = Person("BelBahadur", nepali_name="बेलबहादुर")
om_bahadur_43 = Person("OmBahadur", nepali_name="ओमबहादुर")
ramsharan_43 = Person("Ramsharan", nepali_name="रामशरण")
harisharan_43 = Person("Harisharan", nepali_name="हरिशरण")
abhishek_43 = Person("Abhishek", nepali_name="अभिषेक")
maniram_43 = Person("Maniram", nepali_name="मणिराम")
uddhav_43 = Person("Uddhav", nepali_name="उद्धव")
uttam_43_2 = Person("Uttam", nepali_name="उत्तम")
dwarika_43 = Person("Dwarika", nepali_name="द्वारिका")
krishna_prasad_43 = Person("KrishnaPrasad", nepali_name="कृष्णप्रसाद")
purushottam_43_2 = Person("Purushottam", nepali_name="पुरुषोत्तम")
uday_43 = Person("Uday", nepali_name="उदय")
hira_bahadur_44 = Person("Hirav", nepali_name="हिरबहादुर")
harisharan_44 = Person("Harisharan", nepali_name="हरिशरण")
shivasharan_44 = Person("Shivasharan", nepali_name="शिवशरण")
sashindra_44 = Person("Sashindra", nepali_name="सशिन्द्र")
krishnasharan_44 = Person("Krishnasharan", nepali_name="कृष्णशरण")
laba_prasad_44 = Person("LabaPrasad", nepali_name="लवप्रसाद")

pitambar_41 = Person("Pitambar", nepali_name="पिताम्बर")
muktinath_41 = Person("Muktinath", nepali_name="मुक्तिनाथ")
minanath_41 = Person("Minanath", nepali_name="मीननाथ")
harischandra_42 = Person("Harischandra", nepali_name="हरिश्चन्द्र")
hareram_42 = Person("Shreeram", nepali_name="हरेराम")
harisharan_42 = Person("Harisharan", nepali_name="हरिशरण")
harinath_42 = Person("Harinath", nepali_name="हरिनाथ")
sharad_prasad_42 = Person("Sharadprasad", nepali_name="शरदप्रसाद")

bali_34 = Person("Bali", nepali_name="बलि")
parmananda_34 = Person("Parmananda", nepali_name="परमानन्द", comment="कान्छा - दारिमपाटेका पुर्खा")
moksheswor_35 = Person("Moksheswor", nepali_name="मोक्षेश्वर")
sreeram_35 = Person("Sreeram", nepali_name="श्रीराम")
ramkrishna_35 = Person("Ramkrishna", nepali_name="रामकृष्ण", death_year=1822, place="Lubhu")
bamdev_35 = Person("Bamdev", nepali_name="बमदेव")
chandramadi_36 = Person("Chandramadi", nepali_name="चन्द्रमदन")

tikaram_37 = Person("Tikaram", nepali_name="टीकाराम")
laxmidhar_37 = Person("Laxmidhar", nepali_name="लक्ष्मीधर")
liladhar_37 = Person("Liladhar", nepali_name="लीलाधर")
haribamsha_38 = Person("Haribamsha", nepali_name="हरिवंश")
shivanath_38 = Person("Shivanath", nepali_name="शिवनाथ")
shyamlal_39 = Person("Shyamlal", nepali_name="श्यामलाल")
laxminath_39_2 = Person("Laxminath", nepali_name="लक्ष्मीनाथ")
narayan_39 = Person("Narayan", nepali_name="नारायण")
vishwo_nath_39 = Person("BishwoNath", nepali_name="विश्वनाथ")
makardwoj_39 = Person("Makardwoj", nepali_name="मकरद्वोज")
ganapati_39_2 = Person("Ganapati", nepali_name="गणपति")

shreebilas_40 = Person("Shreebilas", nepali_name="श्रीबिलास")
hitakanta_40 = Person("Hitakanta", nepali_name="हितकान्त")
gajabinod_40 = Person("Gajabinod", nepali_name="गजबिनोद")
nandalal_40 = Person("Nandalal", nepali_name="नन्दलाल")
sashidhar_40 = Person("Sashidhar", nepali_name="सशिधर")
chiranjibi_40 = Person("Chiranjibi", nepali_name="चिरञ्जीवी")

sadananda_41 = Person("Sadananda", nepali_name="सदानन्द")
narandutta_41 = Person("Narandutta", nepali_name="नरदत्त")
chandrakanta_41 = Person("Chandrakanta", nepali_name="चन्द्रकान्त")
chabilal_41 = Person("Chabilal", nepali_name="चबिलाल")
tankanath_41 = Person("Tankanath", nepali_name="टंकनाथ")
khomnath_41 = Person("Khomnath", nepali_name="खोमनाथ")
vishwo_nath_41 = Person("BishwoNath", nepali_name="विश्वनाथ")
sukadev_41 = Person("Sukadev", nepali_name="सुकदेव")
gangasagar_41 = Person("Gangasagar", nepali_name="गंगासागर")

#page 37
gopilal_42 = Person("Gopilal", nepali_name="गोपीलाल")
hemnath_42 = Person("Hemnath", nepali_name="हेमनाथ")
gopal_42_2 = Person("Gopal", nepali_name="गोपाल")
rishi_42 = Person("Rishi", nepali_name="ऋषि")
laxminath_42 = Person("Laxminath", nepali_name="लक्ष्मीनाथ")
gopi_krishna_42 = Person("GopiKrishna", nepali_name="गोपीकृष्ण")
bhojraj_42 = Person("Bhojraj", nepali_name="भोजराज")
muktinath_42 = Person("Muktinath", nepali_name="मुक्तिनाथ")
narayan_42 = Person("Narayan", nepali_name="नारायण")

sashyam_prasad_43 = Person("SashyamPrasad", nepali_name="सश्यामप्रसाद")
ram_krishna_43 = Person("RamKrishna", nepali_name="रामकृष्ण")
shyam_prasad_43 = Person("ShyamPrasad", nepali_name="श्यामप्रसाद")
madhu_43_2 = Person("Madhu", nepali_name="मधु")
hari_43 = Person("Hari", nepali_name="हरि")
bharat_43 = Person("Hari", nepali_name="भरत")
ishwor_43 = Person("Ishwor", nepali_name="ईश्वर")
niranjan_43_2 = Person("Niranjan", nepali_name="निरञ्जन")
gokul_43 = Person("Gokul", nepali_name="गोकुल")
purna_prasad_43 = Person("PurnaPrasad", nepali_name="पूर्णप्रसाद")
saroj_43 = Person("Saroj", nepali_name="सरोज")
bhairav_43 = Person("Bhairav", nepali_name="भैरव")
gyan_prasad_43 = Person("GyanPrasad", nepali_name="ज्ञानप्रसाद")
binod_prasad_43 = Person("BinodPrasad", nepali_name="विनोदप्रसाद")

byapak_44 = Person("Byapak", nepali_name="व्यापक")
binay_44 = Person("Binay", nepali_name="विनय")
prajyan_44 = Person("Prajyan", nepali_name="प्रज्ञान")
pawan_44 = Person("Pawan", nepali_name="पवन")
murari_44 = Person("Murari", nepali_name="मुरारी")

taranath_40 = Person("Taranath", nepali_name="तारानाथ")
siva_prasad_41 = Person("SivaPrasad", nepali_name="शिवप्रसाद")
sita_ram_41 = Person("SitaRam", nepali_name="सीताराम")
dasrath_42 = Person("Dasrath", nepali_name="दशरथ")
gokul_42_2 = Person("Gokul", nepali_name="गोकुल")
ashok_42 = Person("Ashok", nepali_name="अशोक")
surya_42 = Person("Surya", nepali_name="सूर्य")
chandika_prasad_42 = Person("ChandikaPrasad", nepali_name="चण्डिकाप्रसाद")
niranjan_42 = Person("Niranjan", nepali_name="निरञ्जन")
ullas_punja_43 = Person("UllasPunja", nepali_name="उल्लासपुजा")
purna_bhadra_38 = Person("PurnaBhadra", nepali_name="पूर्णभद्र")
#page 38
hari_lal_39_2 = Person("HariLal", nepali_name="हरिलाल")
gauri_kanta_39 = Person("GauriKanta", nepali_name="गौरीकान्त")
modnath_39 = Person("Modnath", nepali_name="मोदनाथ")
dilliram_40 = Person("Dilliram", nepali_name="दिल्लीराम")
chakrapani_40_2 = Person("Chakrapani", nepali_name="चक्रपाणि")
ganesh_prasad_40 = Person("GaneshPrasad", nepali_name="गणेशप्रसाद")
ratna_prasad_40 = Person("RatnaPrasad", nepali_name="रत्नप्रसाद")
dandapani_40_2 = Person("Dandapani", nepali_name="दण्डपाणि")
padma_narayan_40 = Person("PadmaNarayan", nepali_name="पद्मनारायण")

bishnu_prasad_41 = Person("BishnuPrasad", nepali_name="विष्णुप्रसाद")
durga_prasad_41 = Person("DurgaPrasad", nepali_name="दुर्गाप्रसाद")
sudarshan_41 = Person("Sudarshan", nepali_name="सुदर्शन")
krishna_prasad_41_2 = Person("KrishnaPrasad", nepali_name="कृष्णप्रसाद")
gopal_41_2 = Person("Gopal", nepali_name="गोपाल")

uddhav_42 = Person("Uddhav", nepali_name="उद्धव")
shyam_42_1 = Person("Shyam", nepali_name="श्याम")
krishna_prasad_42 = Person("KrishnaPrasad", nepali_name="कृष्णप्रसाद")
baikuntha_42 = Person("Baikuntha", nepali_name="वैकुण्ठ")
ramesh_42 = Person("Ramesh", nepali_name="रमेश")
dinesh_42 = Person("Dinesh", nepali_name="दिनेश")
saroj_42 = Person("Saroj", nepali_name="सरोज")
basanta_42 = Person("Basanta", nepali_name="बसन्त")
niraj_42 = Person("Niraj", nepali_name="निरज")
rajan_42 = Person("Rajan", nepali_name="राजन")
rajesh_42_1 = Person("Rajesh", nepali_name="राजेश")
bhusan_42 = Person("Bhusan", nepali_name="भूषण")
ashok_42_2 = Person("Ashok", nepali_name="अशोक")
shreeram_42_1 = Person("Shreeram", nepali_name="श्रीराम")
mukunda_42_1 = Person("Mukunda", nepali_name="मुकुन्द")
madhuwan_42 = Person("Madhuwan", nepali_name="मधुवन")
madhav_42_2 = Person("Madhav", nepali_name="माधव")

deepak_43_4 = Person("Deepak", nepali_name="दीपक")
suchit_43 = Person("Suchit", nepali_name="सुचित")
pawan_43_2 = Person("Pawan", nepali_name="पवन")
sourya_43 = Person("Sourya", nepali_name="सौर्य")
saurav_43 = Person("Saurav", nepali_name="सौरव")
santosh_43 = Person("Santosh", nepali_name="सन्तोष")
saroj_43_2 = Person("Saroj", nepali_name="सरोज")
mahesh_43_3 = Person("Mahesh", nepali_name="महेश")
anupam_43 = Person("Anupam", nepali_name="अनुपम")

pashupati_38 = Person("Pashupati", nepali_name="पशुपति")
ganapati_38 = Person("Ganapati", nepali_name="गणपति")
padmanath_39 = Person("Padmanath", nepali_name="पद्मनाथ")
kashinath_39_3 = Person("Kashinath", nepali_name="काशीनाथ")
umanath_39 = Person("Umanath", nepali_name="उमानाथ")
kalu_40 = Person("Kalu", nepali_name="कालु")
muktinath_40 = Person("Muktinath", nepali_name="मुक्तिनाथ")
sadananda_40 = Person("Sadananda", nepali_name="सदानन्द")
emanath_40 = Person("Emanath", nepali_name="ईमानाथ")
bhimnath_40 = Person("Bhimnath", nepali_name="भीमनाथ")
narayan_40 = Person("Narayan", nepali_name="नारायण")

sukadev_41_2 = Person("Sukadev", nepali_name="सुकदेव")
dalbahadur_41 = Person("Dalbahadur", nepali_name="दलबहादुर")
gopal_41_3 = Person("Gopal", nepali_name="गोपाल")
ramjeev_41 = Person("Ramjeev", nepali_name="रामजीव")
shyamjeev_41 = Person("Shyamjeev", nepali_name="श्यामजीव")
sahadev_41 = Person("Sahadev", nepali_name="सहदेव")
arjun_41 = Person("Arjun", nepali_name="अर्जुन")
prahlad_41 = Person("Prahlad", nepali_name="प्रह्लाद")
kamal_41 = Person("Kamal", nepali_name="कमल")
ram_41 = Person("Ram", nepali_name="राम")
krishna_41 = Person("Krishna", nepali_name="कृष्ण")
bharat_41 = Person("Bharat", nepali_name="भरत")

nanibabu_42 = Person("Nanibabu", nepali_name="नानीबाबु")
rameshor_42 = Person("Rameshor", nepali_name="रामेश्वर")
achyut_42 = Person("Achyut", nepali_name="अच्युत")
shreeram_42_2 = Person("Shreeram", nepali_name="श्रीराम")
shyam_krishna_42 = Person("ShyamKrishna", nepali_name="श्यामकृष्ण")
shyam_kaji_42 = Person("ShyamKaji", nepali_name="श्यामकाजी")
hari_krishna_42 = Person("HariKrishna", nepali_name="हरिकृष्ण")
sundar_42 = Person("Sundar", nepali_name="सुन्दर")
bidur_42 = Person("Bidur", nepali_name="विदुर")
purushottam_42 = Person("Purushottam", nepali_name="पुरुषोत्तम")
krishnasharan_42 = Person("Krishnasharan", nepali_name="कृष्णशरण")
jayaraj_42 = Person("Jayaraj", nepali_name="जयराज")
sudama_42 = Person("Sudama", nepali_name="सुदामा")
suresh_42 = Person("Suresh", nepali_name="सुरेश")
govinda_42_1 = Person("Govinda", nepali_name="गोविन्द")
shambu_42 = Person("Shambhu", nepali_name="शम्भु")

nabaraj_43 = Person("Nabaraj", nepali_name="नवराज")
chitra_43 = Person("Chitra", nepali_name="चित्र")
habbu_43 = Person("Habbu", nepali_name="हब्बु")
kailash_43 = Person("Kailash", nepali_name="कैलाश")
umesh_43 = Person("Umesh", nepali_name="उमेश")
radheshyam_43 = Person("Radheshyam", nepali_name="राधेश्याम")
ghanashyam_43 = Person("Ganashyam", nepali_name="घनश्याम")
dinesh_43_3 = Person("Dinesh", nepali_name="दिनेश")

#Page 40
su_ramnath_36 = Person("Su_Ramnath", nepali_name="सु रामनाथ")
prabhunath_36 = Person("Prabhunath", nepali_name="प्रभुनाथ")
ranganath_36 = Person("Ranganath", nepali_name="रंगनाथ")
siromani_36 = Person("Siromani", nepali_name="शिरोमणि")
trilokya_36 = Person("Trilokya", nepali_name="त्रिलोक्य")
su_brajmohan_37 = Person("Su_Brajmohan", nepali_name="सु ब्रजमोहन")
yagyanidhi_37 = Person("Yagyanidhi", nepali_name="यज्ञनिधि")
ganapati_37 = Person("Ganapati", nepali_name="गणपति")

krishnamohan_38 = Person("Krishnamohan", nepali_name="कृष्णमोहन")
lalitmohan_38 = Person("Lalitmohan", nepali_name="ललितमोहन")
chaturmohan_38 = Person("Chaturmohan", nepali_name="चतुर्मोहन")
chandramohan_38 = Person("Chandramohan", nepali_name="चन्द्रमोहन")
harimohan_39 = Person("Harimohan", nepali_name="हरिमोहन")
rudramohan_39 = Person("Rudramohan", nepali_name="रुद्रामोहन")
lokmohan_39 = Person("Lokmohan", nepali_name="लोकमोहन")
ganeshmohan_39 = Person("Ganeshmohan", nepali_name="गणेशमोहन")
premmohan_39 = Person("Premmohan", nepali_name="प्रेममोहन")
yogmohan_39 = Person("Yogmohan", nepali_name="योगमोहन")
buddhimohan_39 = Person("Buddhimohan", nepali_name="बुद्धिमोहन")
ram_prasad_40 = Person("RamPrasad", nepali_name="रामप्रसाद")
narayan_40_2 = Person("Narayan", nepali_name="नारायण")
dhruvamohan_40 = Person("Dhruvamohan", nepali_name="ध्रुवमोहन")
tejmohan_40 = Person("Tejmohan", nepali_name="तेजमोहन")
harshamohan_40 = Person("Harshamohan", nepali_name="हर्षमोहन")
yankamohan_40 = Person("Yankamohan", nepali_name="यंकमोहन")
padmanath_41 = Person("Padmanav", nepali_name="पद्मनाथ")
binod_41 = Person("Binod", nepali_name="विनोद")
pramod_41 = Person("Pramod", nepali_name="प्रमोद")
amrit_41 = Person("Amrit", nepali_name="अमृत")
damodar_41 = Person("Damodar", nepali_name="दामोदर")
radhakrishna_41 = Person("Radhakrishna", nepali_name="राधाकृष्ण")
bamshidhar_41 = Person("Bamshidhar", nepali_name="बंशीधर")
yadav_41 = Person("Yadav", nepali_name="यादव")
suraj_41 = Person("Suraj", nepali_name="सुरज")
suman_41 = Person("Suman", nepali_name="सुमन")
sanjay_41 = Person("Sanjay", nepali_name="सञ्जय")

#page 41
sunod_42 = Person("Sunod", nepali_name="सुनोद")
sushan_42 = Person("Sushan", nepali_name="सुशान")
ramesh_42_2 = Person("Ramesh", nepali_name="रमेश")
pradeep_42 = Person("Pradeep", nepali_name="प्रदीप")
prakash_42 = Person("Prakash", nepali_name="प्रकाश")
kumud_42 = Person("Kumud", nepali_name="कुमुद")
enoj_42 = Person("Enoj", nepali_name="एनोज")
manoj_42 = Person("Manoj", nepali_name="मनोज")
anil_42 = Person("Anil", nepali_name="अनिल")

brahmananda_38 = Person("Brahmananda", nepali_name="ब्रह्मानन्द")
gaurinath_38 = Person("Gaurinath", nepali_name="गौरिनाथ")
ambarnath_38 = Person("Ambarnath", nepali_name="अम्बरनाथ")
rewatiraman_38 = Person("Rewatiraman", nepali_name="रेवतीरमण")
ramakanta_38 = Person("Ramakanta", nepali_name="रामकान्त")
pradhumna_38 = Person("Pradhumna", nepali_name="प्रधुम्न")
kabikulkeshari_38 = Person("Kabikulkeshari", nepali_name="कविकुलकेशरी")
sadananda_38 = Person("Sadananda", nepali_name="सदानन्द")
kashinath_38 = Person("Kashinath", nepali_name="काशीनाथ")
tejprasad_38 = Person("Tejprasad", nepali_name="तेजप्रसाद")

yojmohan_39 = Person("Yogmohan", nepali_name="योगमोहन")
krishna_dutta_39 = Person("KrishnaDutta", nepali_name="कृष्णदत्त")
pitambar_39 = Person("Pitambar", nepali_name="पिताम्बर")
vishwo_nath_39_2 = Person("BishwoNath", nepali_name="विश्वनाथ")
chiranjibi_39 = Person("Chiranjibi", nepali_name="चिरञ्जीवी")
tejprasad_39 = Person("Tejprasad", nepali_name="तेजप्रसाद")
maila_39 = Person("Maila", nepali_name="मैला")
jeevprasad_39 = Person("Jeevprasad", nepali_name="जीवप्रसाद")
tankanath_39 = Person("Tankanath", nepali_name="टंकनाथ")
yug_prasad_39 = Person("YudhPrasad", nepali_name="युगप्रसाद")
bhure_39 = Person("Bhure", nepali_name="भुरे")
gwange_39 = Person("Gwage", nepali_name="ग्वाँगे")
jhankanath_39 = Person("Jhankanath", nepali_name="झंकनाथ")
homnath_39 = Person("Homnath", nepali_name="होमनाथ")
maya_prasad_39 = Person("MayaPrasad", nepali_name="मायाप्रसाद")
tej_prasad_40 = Person("TejPrasad", nepali_name="तेजप्रसाद")
tejpinath_40 = Person("Tejpinath", nepali_name="तेजपीनाथ")
krishna_prasad_40 = Person("KrishnaPrasad", nepali_name="कृष्णप्रसाद")
devi_prasad_40 = Person("DeviPrasad", nepali_name="देवीप्रसाद")
prem_raj_40 = Person("PremRaj", nepali_name="प्रेमराज")
pushpa_raj_40 = Person("PushpaRaj", nepali_name="पुष्पराज")
thute_40 = Person("Thute", nepali_name="थुते")

ramji_41 = Person("Ramji", nepali_name="रामजी")
ramraj_41 = Person("Ramraj", nepali_name="रामराज")
laxman_41 = Person("Laxman", nepali_name="लक्ष्मण")
vidyaraj_42 = Person("Vidyaraj", nepali_name="विद्याराज")
nabaraj_42 = Person("Nabaraj", nepali_name="नवराज")
raju_42 = Person("Raju", nepali_name="राजु")
ratna_42 = Person("Ratna", nepali_name="रत्न")
vijay_42 = Person("Vijay", nepali_name="विजय")

#page 42
narad_36 = Person("Narad", nepali_name="नारद")
dinakar_36 = Person("Dinakar", nepali_name="दिनाकर")
prabhakar_36 = Person("Prabhakar", nepali_name="प्रभाकर")
antare_36 = Person("Antare", nepali_name="अन्तरे")
kancha_36 = Person("Kancha", nepali_name="कञ्चा")
laxmikanta_37 = Person("Laxmikanta", nepali_name="लक्ष्मीकान्त", place="ईखुडोल")
chandrasekhar_37 = Person("Chandrasekhar", nepali_name="चन्द्रशेखर", comment="ठुलाघर")
baburam_37 = Person("Baburam", nepali_name="बाबुराम")

nandalal_38 = Person("Nandalal", nepali_name="नन्दलाल")
harinanda_38 = Person("Harinanda", nepali_name="हरिनन्द")
chandrakanta_38 = Person("Chandrakanta", nepali_name="चन्द्रकान्त")
agnidhar_39 = Person("Agnidhar", nepali_name="अग्निधर")
yadunath_39 = Person("Yadunath", nepali_name="यदुनाथ")
gurudutta_39 = Person("Gurudutta", nepali_name="गुरुदत्त")
dharmananda_39 = Person("Dharmananda", nepali_name="धर्मानन्द")
bedimadhav_39 = Person("Bedimadhav", nepali_name="बेणीमाधव")
govinda_39 = Person("Govinda", nepali_name="गोविन्द")
damodar_39 = Person("Damodar", nepali_name="दामोदर")

jagannath_40 = Person("Jagannath", nepali_name="जगन्नाथ")
ramji_40 = Person("Ramji", nepali_name="रामजी")
bholanath_40 = Person("Bholanath", nepali_name="भोलानाथ")
madhav_40 = Person("Madhav", nepali_name="माधव")
nabaraj_40 = Person("Nabaraj", nepali_name="नवराज")

#page 43
binod_41_2 = Person("Binod", nepali_name="विनोद")
bijayanath_41 = Person("Bijayanath", nepali_name="विजयनाथ", comment="वंशावली सम्पादक")
pramod_41_2 = Person("Pramod", nepali_name="प्रमोद")
subodh_41 = Person("Subodh", nepali_name="सुबोध")
nayanath_41 = Person("Nayanath", nepali_name="नयनाथ")
samanath_41 = Person("Samanath", nepali_name="सामनाथ")
brihaspati_41 = Person("Brihaspati", nepali_name="बृहस्पति")
rukhmanath_41 = Person("Rukhmanath", nepali_name="रुखमनाथ")
grihanath_41 = Person("Grihanath", nepali_name="गृहनाथ")
shankar_41_2 = Person("Shankar", nepali_name="शंकर")
deepak_41 = Person("Deepak", nepali_name="दीपक")
sudarshan_41_2 = Person("Sudarshan", nepali_name="सुदर्शन")
nirmal_41 = Person("Nirmal", nepali_name="निर्मल")

ajay_42 = Person("Ajay", nepali_name="अजय")
sanjay_42 = Person("Sanjay", nepali_name="सञ्जय")
pradeep_42_1 = Person("Pradeep", nepali_name="प्रदीप")
uttam_42 = Person("Uttam", nepali_name="उत्तम")
bodhnath_42 = Person("Bodhnath", nepali_name="बोधनाथ")
heli_42 = Person("Heli", nepali_name="हेली")
heman_42 = Person("Heman", nepali_name="हेमन")
sabij_42 = Person("Sabij", nepali_name="सबिज")
manish_42 = Person("Manish", nepali_name="मनिश")
anish_42 = Person("Anish", nepali_name="अनिश")

damodar_37 = Person("Damodar", nepali_name="दामोदर")
mitralal_37 = Person("Mitralal", nepali_name="मित्रलाल")
sadananda_37 = Person("Sadananda", nepali_name="सदानन्द")
chetnath_38 = Person("Chetnath", nepali_name="चेतनाथ")
badri_39 = Person("Badri", nepali_name="बद्री", place="कोटेश्वर")
mahesh_40 = Person("Mahesh", nepali_name="महेश")
shyamhari_40 = Person("Shyamhari", nepali_name="श्यामहरि")

#page 44
maheshwor_38 = Person("Maheshwor", nepali_name="महेश्वर")
shiva_dutta_38_2 = Person("ShivaDutta", nepali_name="शिवदत्त")
bam_bahadur_38 = Person("BamBahadur", nepali_name="वमबहादुर")
bir_bahadur_38 = Person("BirBahadur", nepali_name="वीरबहादुर")
bhairab_bahadur_38 = Person("BhairabBahadur", nepali_name="भैरवबहादुर")
kataka_bahadur_38 = Person("KatakaBahadur", nepali_name="कटकबहादुर")
amar_bahadur_38 = Person("AmarBahadur", nepali_name="अमरबहादुर")

bhuwaneshor_39 = Person("Bhuwaneshor", nepali_name="भुवनेश्वर")
ganesh_dutta_39 = Person("GaneshDutta", nepali_name="गणेशदत्त")
shiva_prasad_40 = Person("ShivaPrasad", nepali_name="शिवप्रसाद")
sthaleshor_40 = Person("Sthaleshor", nepali_name="स्थलेश्वर")
ranganath_40 = Person("Ranganath", nepali_name="रंगनाथ")
fadindranath_40 = Person("Fadindranath", nepali_name="फदिन्द्रनाथ")
devi_prasad_40_1 = Person("DeviPrasad", nepali_name="देवीप्रसाद")
jhankanath_40 = Person("Jhankanath", nepali_name="झंकनाथ")
homanath_40 = Person("Homanath", nepali_name="होमनाथ")

kedar_bahadur_41 = Person("KedarBahadur", nepali_name="केदरबहादुर")
krishna_bahadur_41 = Person("KrishnBahadur", nepali_name="कृष्णबहादुर")
arjun_bahadur_41 = Person("ArjunBahadur", nepali_name="अर्जुनबहादुर")
badri_prasad_41_2 = Person("BadriPrasad", nepali_name="बद्रीप्रसाद")
shyam_prasad_41 = Person("ShyamPrasad", nepali_name="श्यामप्रसाद")
damodar_prasad_41 = Person("DamodarPrasad", nepali_name="दामोदरप्रसाद")
jagannath_41 = Person("Jagannath", nepali_name="जगन्नाथ")
tarkaraj_41 = Person("Tarkaraj", nepali_name="तर्कराज")
chiranjibi_41 = Person("Chiranjibi", nepali_name="चिरञ्जीवी")
rishi_41 = Person("Rishi", nepali_name="ऋषि")
hari_41 = Person("Hari", nepali_name="हरि")
shyam_41 = Person("Shyam", nepali_name="श्याम")
ramhari_41 = Person("Ramhari", nepali_name="रामहरि")

bishwo_nath_42_1 = Person("BishwoNath", nepali_name="विश्वनाथ")
badri_prasad_42_1 = Person("BadriPrasad", nepali_name="बद्रीप्रसाद")
kiran_42 = Person("Kiran", nepali_name="किरण")
ravi_42 = Person("Ravi", nepali_name="रवि")
mani_42 = Person("Mani", nepali_name="मणि")
kumar_42_2 = Person("Kumar", nepali_name="कुमार")
jeewan_42_1 = Person("Jeewan", nepali_name="जीवन")

diwakar_43_3 = Person("Diwakar", nepali_name="दिवाकर")
prabhakar_43 = Person("Prabhakar", nepali_name="प्रभाकर")
suman_43 = Person("Suman", nepali_name="सुमन")
sagar_43 = Person("Sagar", nepali_name="सागर")
sudhakar_43 = Person("Sudhakar", nepali_name="सुधाकर")
bhaskar_43 = Person("Bhaskar", nepali_name="भास्कर")
sankar_43 = Person("Sankar", nepali_name="शंकर")
mahesh_43_4 = Person("Mahesh", nepali_name="महेश")

#Page 45
ganesh_bahadur_39 = Person("GaneshBahadur", nepali_name="गणेशबहादुर")
kul_bahadur_39 = Person("KulBahadur", nepali_name="कुलबहादुर")
moti_bahadur_40 = Person("MotiBahadur", nepali_name="मोतिबहादुर")
gagan_bahadur_40 = Person("GaganBahadur", nepali_name="गगनबहादुर")
murli_40 = Person("Murli", nepali_name="मुरली")
krishna_bahadur_40 = Person("KrishnaBahadur", nepali_name="कृष्णबहादुर")
balaram_40 = Person("Balaram", nepali_name="बलराम")
indra_bahadur_40 = Person("IndraBahadur", nepali_name="इन्द्रबहादुर")
punya_bahadur_41 = Person("PunyaBahadur", nepali_name="पुण्यबहादुर")
amir_bahadur_41 = Person("AmirBahadur", nepali_name="अमीरबहादुर")
kamal_bahadur_41 = Person("KamalBahadur", nepali_name="कमलबहादुर")
bishnu_41 = Person("Bishnu", nepali_name="विष्णु")
bijay_41 = Person("Bijay", nepali_name="विजय")
arjun_41_2 = Person("Arjun", nepali_name="अर्जुन")
keshav_41_2 = Person("Keshav", nepali_name="केशव")
rajan_41 = Person("Rajan", nepali_name="रजन")
sudama_41 = Person("Sudama", nepali_name="सुदामा")
kapil_41 = Person("Kapil", nepali_name="कपिल")
dil_bahadur_41 = Person("DilBahadur", nepali_name="दिलबहादुर")

rajendra_42 = Person("Rajendra", nepali_name="राजेन्द्र")
devendra_42 = Person("Devendra", nepali_name="देवेन्द्र")
surendra_42 = Person("Surendra", nepali_name="सुरेन्द्र")
rabindra_42 = Person("Rabindra", nepali_name="रवीन्द्र")
rupendra_42 = Person("Rupendra", nepali_name="रुपेन्द्र")
laxman_42 = Person("Laxman", nepali_name="लक्ष्मण")
rajaram_42 = Person("Rajaram", nepali_name="राजाराम")
shantaram_42 = Person("Shantaram", nepali_name="शान्तराम")
surya_kumar_42 = Person("Suryakumar", nepali_name="सूर्यकुमार")
purna_kumar_42 = Person("PurnaKumar", nepali_name="पूर्णकुमार")
ram_chandra_42 = Person("RamChandra", nepali_name="रामचन्द्र")
prakash_42_1 = Person("Prakash", nepali_name="प्रकाश")
kiran_42_1 = Person("Kiran", nepali_name="किरण")
roshan_42 = Person("Roshan", nepali_name="रोशन")
chidananda_42 = Person("Chidananda", nepali_name="चिदानन्द")
suman_42 = Person("Suman", nepali_name="सुमन")
sudan_42 = Person("Sudan", nepali_name="सुदन")

bhakta_bahadur_39 = Person("BhaktaBahadur", nepali_name="भक्तबहादुर")
dol_bahadur_40 = Person("DolBahadur", nepali_name="डोलबहादुर")
sete_39 = Person("Sete", nepali_name="सेटे")
bharat_bahadur_39 = Person("BharatBahadur", nepali_name="भरतबहादुर")
tilak_bahadur_39 = Person("TilakBahadur", nepali_name="तिलकबहादुर")
ram_bahadur_40 = Person("RamBahadur", nepali_name="रामबहादुर")
krishna_bahadur_40_1 = Person("KrishnaBahadur", nepali_name="कृष्णबहादुर")
purna_bahadur_40 = Person("PurnaBahadur", nepali_name="पूर्णबहादुर")

#page 46
shiva_hari_41 = Person("ShivaHari", nepali_name="शिवहरि")
krishna_hari_41 = Person("KrishnaHari", nepali_name="कृष्णहरि")
babu_kaji_41 = Person("BabuKaji", nepali_name="बाबुकाजी")
shiva_41 = Person("Shiva", nepali_name="शिव")
bal_gopal_41 = Person("BalGopal", nepali_name="बालगोपाल")
rajendra_41 = Person("Rajendra", nepali_name="राजेन्द्र")
nabaraj_41 = Person("Nabaraj", nepali_name="नवराज")
prahlad_41_2 = Person("Prahlad", nepali_name="प्रह्लाद")
ramkumar_42 = Person("Ramkumar", nepali_name="रामकुमार")
shyam_42_2 = Person("Shyam", nepali_name="श्याम")
krishna_42_2 = Person("Krishna", nepali_name="कृष्ण")
bishnu_42 = Person("Bishnu", nepali_name="विष्णु")
niranjan_42_2 = Person("Niranjan", nepali_name="निरञ्जन")

shree_hari_36 = Person("ShreeHari", nepali_name="श्रीहरि")
brahma_37 = Person("Brahma", nepali_name="ब्रह्मा")
sree_krishna_37 = Person("SreeKrishna", nepali_name="श्रीकृष्ण")
shivanav_38 = Person("Bishwonav", nepali_name="विश्वनव")
bal_krishna_38 = Person("BalKrishna", nepali_name="बालकृष्ण", comment="१८५२को कागजमा साक्षी")

#page 47
pashupati_39 = Person("Pashupati", nepali_name="पशुपति")
bhaskar_39 = Person("Bhaskar", nepali_name="भास्कर")
padmanav_40 = Person("Padmanav", nepali_name="पद्मनाभ")
dasrath_40 = Person("Dasrath", nepali_name="दशरथ")
mayanath_40 = Person("Mayanath", nepali_name="मायानाथ")

hemnav_41 = Person("Hemnath", nepali_name="हेमनाभ")
basudev_41 = Person("Basudev", nepali_name="वासुदेव")
laxmikanta_41_2 = Person("Laxmikanta", nepali_name="लक्ष्मीकान्त")
ganeshnath_41 = Person("Ganeshnath", nepali_name="गणेशनाथ")
bhimnath_41 = Person("Bhimnath", nepali_name="भीमनाथ")
damodar_41_2 = Person("Damodar", nepali_name="दामोदर")
maan_bahadur_41 = Person("Manav", nepali_name="मानव")
bartaman_singh_41_2 = Person("BartamanSingh", nepali_name="वर्तमानसिंह")

radhakrishna_42 = Person("Radhakrishna", nepali_name="राधाकृष्ण")
ratna_prasad_42 = Person("RatnaPrasad", nepali_name="रत्नप्रसाद")
pradhumna_42 = Person("Pradhumna", nepali_name="प्रधुम्न")
gopal_42_1 = Person("Gopal", nepali_name="गोपाल")
krishna_42_1 = Person("Krishna", nepali_name="कृष्ण")
keshav_42 = Person("Keshav", nepali_name="केशव")
harihar_42 = Person("Harihar", nepali_name="हरिहर")
ramji_42 = Person("Ramji", nepali_name="रामजी")
krishna_42_3 = Person("Krishna", nepali_name="कृष्ण")
narandutta_42 = Person("Narandutta", nepali_name="नारनदत्त")

sunil_43_2 = Person("Sunil", nepali_name="सुनिल")
bikash_43 = Person("Bikash", nepali_name="विकास")
bhanu_kumar_43 = Person("BhanuKumar", nepali_name="भानुकुमार", place="काशी")
shashi_kumar_43 = Person("ShashiKumar", nepali_name="शशीकुमार", place="काशी")
madhav_43 = Person("Madhav", nepali_name="माधव")
achyut_43 = Person("Achyut", nepali_name="अच्युत")
sushil_43 = Person("Sushil", nepali_name="सुशील")
mahesh_43_5 = Person("Mahesh", nepali_name="महेश")
ramesh_43 = Person("Ramesh", nepali_name="रमेश")
suresh_43_3 = Person("Suresh", nepali_name="सुरेश")
kedar_43 = Person("Kedar", nepali_name="केदार")
bishnu_43 = Person("Bishnu", nepali_name="विष्णु")
shambhu_43 = Person("Shambhu", nepali_name="शम्भु")
sanjay_44_2 = Person("Sanjay", nepali_name="सञ्जय")
sanjiv_44 = Person("Sanjiv", nepali_name="सञ्जीव")
saroj_44_3 = Person("Saroj", nepali_name="सरोज")
santosh_44 = Person("Santosh", nepali_name="सन्तोष")
sudeep_44_3 = Person("Sudeep", nepali_name="सुदीप")
suman_44_2 = Person("Suman", nepali_name="सुमन")

#Page 48
jagannath_42_2 = Person("Jagannath", nepali_name="जगन्नाथ")
chudamani_42 = Person("Chudamani", nepali_name="चुडामणि")
buddhisagar_42 = Person("Buddhisagar", nepali_name="बुद्धिसागर")
narayan_42_2 = Person("Narayan", nepali_name="नारायण")
krishna_42_4 = Person("Krishna", nepali_name="कृष्ण")
ram_bahadur_42 = Person("RamBahadur", nepali_name="रामबहादुर")
ramji_42_2 = Person("Ramji", nepali_name="रामजी")

govinda_43 = Person("Govinda", nepali_name="गोविन्द")
dhruva_43 = Person("Dhruva", nepali_name="ध्रुव")
keshav_43 = Person("Keshav", nepali_name="केशव")
bharat_43_2 = Person("Bharat", nepali_name="भरत")
shyam_43 = Person("Shyam", nepali_name="श्याम")
sita_ram_43 = Person("SitaRam", nepali_name="सीताराम")
kamal_43 = Person("Kamal", nepali_name="कमल")
dhruva_43_2 = Person("Dhruva", nepali_name="ध्रुव")
durga_43 = Person("Durga", nepali_name="दुर्गा")
rameshwor_43 = Person("Rameshwor", nepali_name="रामेश्वर")
yagya_bahadur_43 = Person("YagyaBahadur", nepali_name="यज्ञबहादुर")
yuddha_bahadur_43 = Person("YuddhaBahadur", nepali_name="युद्धबहादुर")
badri_43 = Person("Badri", nepali_name="बद्री")
kedar_43_2 = Person("Kedar", nepali_name="केदार")
uttam_43_3 = Person("Uttam", nepali_name="उत्तम")

gopal_44 = Person("Gopal", nepali_name="गोपाल")
niraj_44_2 = Person("Niraj", nepali_name="निरज")
subash_44 = Person("Subash", nepali_name="सुवास")
uttam_44 = Person("Uttam", nepali_name="उत्तम")
dinesh_44_2 = Person("Dinesh", nepali_name="दिनेश")
mahesh_44 = Person("Mahesh", nepali_name="महेश")
ramesh_44_2 = Person("Ramesh", nepali_name="रमेश")
madan_44 = Person("Madan", nepali_name="मदन")
dayaram_44 = Person("Dayaram", nepali_name="दयाराम")
bishnu_44 = Person("Bishnu", nepali_name="विष्णु")

murali_35 = Person("Murali", nepali_name="मुरली")
purshuram_35 = Person("Purshuram", nepali_name="पुरुषोत्तम")
markandeya_35 = Person("Markandeya", nepali_name="मार्कण्डेय")
balbhadra_36 = Person("Balbhadra", nepali_name="बलभद्र")
govinda_37 = Person("Govinda", nepali_name="गोविन्द")
sreebilas_37 = Person("Sreebilas", nepali_name="श्रीविलास")
badibilas_37 = Person("Badibilas", nepali_name="वाणीविलास")

#Page 49
pundarika_38 = Person("Pundarika", nepali_name="पुण्डरीक")
ramakanta_38_2 = Person("Ramakanta", nepali_name="रमाकान्त")
umakanta_38 = Person("Umakanta", nepali_name="उमाकान्त")
chandrasekhar_38 = Person("Chandrasekhar", nepali_name="चन्द्रशेखर")
lekhnath_38 = Person("Lekhnath", nepali_name="लेखनाथ")
nayakeshari_38 = Person("Nayakeshari", nepali_name="नयकेशरी")
ghananath_38 = Person("Ghananath", nepali_name="घननाथ")
moksheswor_38 = Person("Moksheswor", nepali_name="मोक्षेश्वर")
agnisanta_38 = Person("Agnisanta", nepali_name="अग्निृशान्त")
nabaraj_38 = Person("Nabaraj", nepali_name="नवराज")
dasrath_38 = Person("Dasrath", nepali_name="दशरथ")

jangadwoj_39 = Person("Jangadwoj", nepali_name="जंगध्वज")
krishna_bahadur_39 = Person("KrishnaBahadur", nepali_name="कृष्णबहादुर")
gobre_39 = Person("Gobre", nepali_name="गोब्रे")
gopal_39 = Person("Gopal", nepali_name="गोपाल")
shankar_39 = Person("Shankar", nepali_name="शंकर")
padma_bahadur_40 = Person("PadmaBahadur", nepali_name="पद्मबहादुर")
chandra_bahadur_40 = Person("ChandraBahadur", nepali_name="चन्द्रबहादुर")
gute_40 = Person("Gute", nepali_name="गुते")
krishna_40 = Person("Krishna", nepali_name="कृष्ण")
krishna_bahadur_41_2 = Person("KrishnaBahadur", nepali_name="कृष्णबहादुर", place="विराटनगर")
hiranya_bahadur_41 = Person("HiranyaBahadur", nepali_name="हिरण्यबहादुर")
narayan_bahadur_41 = Person("NarayanBahadur", nepali_name="नारायणबहादुर")
shankar_42 = Person("Shankar", nepali_name="शंकर")

hari_lal_38 = Person("HariLal", nepali_name="हरिलाल")
nayakeshari_38_2 = Person("Nayakeshari", nepali_name="नयकेशरी")
dasrath_38_2 = Person("Dasrath", nepali_name="दशरथ")
ram_chandra_39 = Person("RamChandra", nepali_name="रामचन्द्र")
laxman_39_2 = Person("Laxman", nepali_name="लक्ष्मण")
devdutta_39 = Person("Devdutta", nepali_name="देवदत्त")
bidyakanta_chankhe_39 = Person("Bidyakanta", nepali_name="विद्याकान्त")
lilanath_39 = Person("Lilanath", nepali_name="लिलानाथ", place="जनकपुर भगवतीपुर")
ram_prasad_39 = Person("RamPrasad", nepali_name="रामप्रसाद")
rudranath_39 = Person("Rudranath", nepali_name="रुद्रनाथ")
lekhnath_39 = Person("Lekhnath", nepali_name="लेखनाथ")

#page 50
babulal_40 = Person("Babulal", nepali_name="बाबुलाल")
purna_bahadur_40_2 = Person("PurnaBahadur", nepali_name="पूर्णबहादुर")
ambar_bahadur_40 = Person("AmbarBahadur", nepali_name="अम्बरबहादुर")
keshav_40 = Person("Keshav", nepali_name="केशव")
bishwonath_40 = Person("Bishwonath", nepali_name="विश्वनाथ")
kirtinath_40 = Person("Kirtinath", nepali_name="कीर्तिनाथ")
hari_40 = Person("Hari", nepali_name="हरि")
purshuram_40 = Person("Purshuram", nepali_name="परशुराम")
bishnu_40 = Person("Bishnu", nepali_name="विष्णु")
shivakumar_40 = Person("Shivakumar", nepali_name="शिवकुमार")

ramchandra_41 = Person("Ramchandra", nepali_name="रामचन्द्र", place="बालकोट")
ganesh_bahadur_41 = Person("GaneshBahadur", nepali_name="गणेशबहादुर")
shyam_bahadur_41 = Person("ShyamBahadur", nepali_name="श्यामबहादुर")
sambhu_bahadur_41 = Person("ShambhuBahadur", nepali_name="शम्भुबहादुर")
pushpa_raj_41 = Person("PushpaRaj", nepali_name="पुष्पराज")
pradeep_41 = Person("Pradeep", nepali_name="प्रदीप")
niroj_41 = Person("Niroj", nepali_name="निरोज")
sarad_kumar_41 = Person("SaradKumar", nepali_name="शरदकुमार")
sree_kumar_41 = Person("SreeKumar", nepali_name="श्रीकुमार")

govinda_42_2 = Person("Govinda", nepali_name="गोविन्द")
sudarshan_42_2 = Person("Sudarshan", nepali_name="सुदर्शन")
madhav_42_3 = Person("Madhav", nepali_name="माधव")
narayan_42_3 = Person("Narayan", nepali_name="नारायण")
kedar_42_3 = Person("Kedar", nepali_name="केदार")
rajendra_42_2 = Person("Rajendra", nepali_name="राजेन्द्र")
shiva_bahadur_42 = Person("ShivaBahadur", nepali_name="शिवबहादुर")
kiran_42_2 = Person("Kiran", nepali_name="किरण")
kishor_42 = Person("Keshav", nepali_name="केशव")
rameshwor_42 = Person("Rameshwor", nepali_name="रामेश्वर")
ramesh_42_3 = Person("Ramesh", nepali_name="रमेश")
sudeep_42 = Person("Sudeep", nepali_name="सुदिप")

hari_36 = Person("Hari", nepali_name="हरि")
ramananda_37 = Person("Ramananda", nepali_name="रामानन्द")
liladhar_38 = Person("Liladhar", nepali_name="लिलाधर")
jayabhadra_38 = Person("Jayabhadra", nepali_name="जयभद्र")

#page 51
taranath_39 = Person("Taranath", nepali_name="तारानाथ")
loknath_39 = Person("Loknath", nepali_name="लोकनाथ")
prabhunath_39 = Person("Prabhunath", nepali_name="प्रभुनाथ")
sadananda_39 = Person("Sadananda", nepali_name="सदानन्द")
prayagdut_40 = Person("Prayagdut", nepali_name="प्रयागदत्त")
purushottam_40 = Person("Purushottam", nepali_name="पुरुषोत्तम")
narayan_40_3 = Person("Narayan", nepali_name="नारायण")
chabilal_40 = Person("Chabilal", nepali_name="चबिलाल")
kubernath_40 = Person("Kubernath", nepali_name="कुबेर्नाथ")

ganesh_bahadur_41_2 = Person("GaneshBahadur", nepali_name="गणेशबहादुर")
premnath_41_2 = Person("Premnath", nepali_name="प्रेमनाथ")
byas_41 = Person("Byas", nepali_name="व्यास")
sukadev_41_3 = Person("Sukadev", nepali_name="सुकदेव")
gunaraj_41_2 = Person("Gunaraj", nepali_name="गुणराज")
bhawaraj_41 = Person("Bawaraj", nepali_name="भवराज")
dhruva_prasad_41 = Person("DhruvaPrasad", nepali_name="ध्रुवप्रसाद")
kapil_dev_41 = Person("KapilDev", nepali_name="कपिलदेव", place="चण्डोल")

ram_kaji_42 = Person("RamKaji", nepali_name="रामकाजी")
basudev_42_2 = Person("Basudev", nepali_name="वासुदेव")
laxman_42_2 = Person("Laxman", nepali_name="लक्ष्मण")
binod_42 = Person("Binod", nepali_name="विनोद")
ramgopal_42 = Person("Ramgopal", nepali_name="रामगोपाल")
ranjan_raj_42 = Person("RanjanRaj", nepali_name="रञ्जनराज")
sitaram_42 = Person("Sitaram", nepali_name="सीताराम")
shivanath_42 = Person("Shivanath", nepali_name="शिवनाथ")
ram_prasad_42 = Person("RamPrasad", nepali_name="रामप्रसाद")
hari_prasad_42_2 = Person("HariPrasad", nepali_name="हरिप्रसाद")

bishesh_43 = Person("Bishesh", nepali_name="विशेष")
bibek_43_2 = Person("Bibek", nepali_name="विवेक")
raju_prasad_43 = Person("RajuPrasad", nepali_name="राजुप्रसाद")
sancha_43 = Person("Sancha", nepali_name="सञ्च")
saroj_43_3 = Person("Saroj", nepali_name="सरोज")
manoj_43_2 = Person("Manoj", nepali_name="मनोज")

#page 52
homnath_40 = Person("Homnath", nepali_name="होमनाथ")
padmanidhi_40 = Person("Padmanidhi", nepali_name="पद्मनिधि", place="कपन")
gangadutta_40 = Person("Gangadutta", nepali_name="गंगादत्त")
tulsiram_40 = Person("Tulsiram", nepali_name="तुल्सीराम")
narayan_41 = Person("Narayan", nepali_name="नारायण")
shiva_hari_41_2 = Person("ShivaHari", nepali_name="शिवहरि")
tulsi_prasad_41 = Person("TulsiPrasad", nepali_name="तुल्सीप्रसाद")
makarananda_41 = Person("Makarananda", nepali_name="मकरानन्द")
huta_prasad_41 = Person("HutaPrasad", nepali_name="हुतप्रसाद")
ghananath_41 = Person("Ghananath", nepali_name="घननाथ")
narayan_41_2 = Person("Narayan", nepali_name="नारायण")
khecharnath_41 = Person("Khecharnath", nepali_name="खेचरनाथ")

prem_kumar_42 = Person("PremKumar", nepali_name="प्रेमकुमार")
ramesh_42_4 = Person("Ramesh", nepali_name="रमेश")
aatma_ram_42_2 = Person("AatmaRam", nepali_name="आत्मराम")
badri_42_2 = Person("Badri", nepali_name="बद्री")
basudev_42_3 = Person("Basudev", nepali_name="वासुदेव")
dayanidhi_42 = Person("Dayanidhi", nepali_name="दयानिधि")
bal_krishna_42 = Person("BalKrishna", nepali_name="बालकृष्ण")
kedar_42_4 = Person("Kedar", nepali_name="केदार")
govinda_42_3 = Person("Govinda", nepali_name="गोविन्द")
keshav_42_3 = Person("Keshav", nepali_name="केशव")
shambu_42_2 = Person("Shambhu", nepali_name="सम्भु")
shyam_prasad_42 = Person("ShyamPrasad", nepali_name="श्यामप्रसाद")
baburam_42 = Person("Baburam", nepali_name="बाबुराम")
krishna_42_5 = Person("Krishna", nepali_name="कृष्ण")
bishnu_42_2 = Person("Bishnu", nepali_name="विष्णु")

pawan_43 = Person("Pawan", nepali_name="पवन")
rujhan_43 = Person("Rujhan", nepali_name="रुझान")
ranjan_43 = Person("Ranjan", nepali_name="रञ्जन")
shivakumar_43 = Person("Shivakumar", nepali_name="शिवकुमार")
gopal_43 = Person("Gopal", nepali_name="गोपाल")
prithu_43 = Person("Prithu", nepali_name="पृथु")
parshu_43 = Person("Parshu", nepali_name="परशु")
laxman_43_2 = Person("Laxman", nepali_name="लक्ष्मण")
shyamsundar_43 = Person("Shyamsundar", nepali_name="श्यामसुन्दर")
ram_43_2 = Person("Ram", nepali_name="राम")
ghanashyam_43_2 = Person("Ghanashyam", nepali_name="घनश्याम")
binod_43_3 = Person("Binod", nepali_name="विनोद")
narayan_43_2 = Person("Narayan", nepali_name="नारायण")
rajendra_43 = Person("Rajendra", nepali_name="राजेन्द्र")
binod_43_4 = Person("Binod", nepali_name="विनोद")
shambhu_43_2 = Person("Shambhu", nepali_name="शम्भु")
ramesh_43_2 = Person("Ramesh", nepali_name="रमेश")
kedar_43_3 = Person("Kedar", nepali_name="केदार")
rameshwor_43_3 = Person("Rameshwor", nepali_name="रामेश्वर")
raju_43 = Person("Raju", nepali_name="राजु")
deepak_43_5 = Person("Deepak", nepali_name="दीपक")

dinesh_44 = Person("Dinesh", nepali_name="दिनेश")
umesh_44 = Person("Umesh", nepali_name="उमेश")
rajesh_44 = Person("Rajesh", nepali_name="राजेश")

#Page 53
unnamed_36 = Person("Unnamed", nepali_name="नाम नखुलेको")
ram_chandra_37 = Person("Unnamed", nepali_name="रामचन्द्र")
unnamed_38 = Person("Unnamed", nepali_name="नाम नखुलेको", place="विराटनगर")
devdutta_38 = Person("Devdutta", nepali_name="देवदत्त")
rambhadra_39 = Person("Rambhadra", nepali_name="रामभद्र")
bhuminandan_39 = Person("Bhuminandan", nepali_name="भूमिनन्दन", place="कुमारीगाल")
dambar_bahadur_40 = Person("DambarBahadur", nepali_name="डमरबहादुर")
purna_bahadur_40_3 = Person("PurnaBahadur", nepali_name="पूर्णबहादुर")
harinandan_40 = Person("Harinandan", nepali_name="हरिनन्दन")
chandrakant_40 = Person("Chandrakant", nepali_name="चन्द्रकान्त")
chiranjibi_40_2 = Person("Chiranjibi", nepali_name="चिरञ्जीवी")
taranath_40_2 = Person("Taranath", nepali_name="तारानाथ")

bhim_bahadur_41 = Person("BhimBahadur", nepali_name="भीमबहादुर")
sete_41 = Person("Sete", nepali_name="सेते")
ramnath_41_2 = Person("Ramnath", nepali_name="रामनाथ")
shiva_prasad_41 = Person("ShivaPrasad", nepali_name="शिवप्रसाद")
purushottam_41 = Person("Purushottam", nepali_name="पुरुषोत्तम")

sanatkumar_42 = Person("Sanatkumar", nepali_name="सनतकुमार")
shivaram_42 = Person("Shivaram", nepali_name="शिवराम")
shree_krishna_42 = Person("ShreeKrishna", nepali_name="श्रीकृष्ण")
sreeram_42 = Person("SreeRam", nepali_name="श्रीराम")
ramsharan_42 = Person("Ramsharan", nepali_name="रामशरण")
maniram_42 = Person("Maniram", nepali_name="मणिराम")
nabaraj_42_2 = Person("Nabaraj", nepali_name="नवराज")
nirmal_43 = Person("Nirmal", nepali_name="निर्मल")
nirjan_43 = Person("Nirjan", nepali_name="निर्जन")
nischal_43 = Person("Nischal", nepali_name="निश्चल")

#Page 54





#####################################################
gopal_31.add_child(ram_bhadra_32)
ram_bhadra_32.add_childs([govinda_33, prajapati_33, chamu_33])
govinda_33.add_childs([gautam_34, gangaram_34, bhrigu_34, bali_34, parmananda_34])
gautam_34.add_childs([laxmidhar_35, ramchandra_35, devhari_kancha_35])
laxmidhar_35.add_childs([laxminarayan_36, rambhadra_36])
laxminarayan_36.add_child(vidya_nanda_37)
vidya_nanda_37.add_child(dharma_nanda_38)
dharma_nanda_38.add_child(hari_lal_39)
hari_lal_39.add_child(shiva_nidhi_40)

shiva_nidhi_40.add_childs([ged_lal_41, lekhnath_41, premnath_41])
ged_lal_41.add_child(eknath_42)
lekhnath_41.add_childs([ram_42, krishna_42, badri_42, bishwo_nath_42])
premnath_41.add_child(aatma_ram_42)
#page 27
ram_42.add_child(ananta_43)
krishna_42.add_childs([harihar_43, binod_43])
badri_42.add_childs([pramod_43, amod_43, arun_43])
bishwo_nath_42.add_child(shiva_nath_43)
aatma_ram_42.add_childs([deepak_43, diwakar_43])

harihar_43.add_child(praveen_44)
binod_43.add_child(vivek_44)
pramod_43.add_child(prashant_44)

rambhadra_36.add_child(ghanashyam_37)
ghanashyam_37.add_childs([shiva_dutta_38, bishnu_dutta_38, ram_dutta_38, hari_dutta_38])
ram_dutta_38.add_childs([padmalochan_39, buddhinath_39, laxminath_39, jeewanath_39, kashinath_39])
laxminath_39.add_childs([chakrapani_40, dandapani_40])
jeewanath_39.add_childs([badibilas_40, bavanath_40, naranath_40, ganesh_dutta_40])

chakrapani_40.add_childs([guru_prasad_41, gunaraj_41, ramanath_41, balaram_41, dillinath_41])
dandapani_40.add_childs([toyanath_41, krishna_prasad_41])
badibilas_40.add_childs([bhuminanda_41, buddhinath_41])
naranath_40.add_child(durga_41)
ganesh_dutta_40.add_child(angirash_41)

guru_prasad_41.add_childs([dhruva_42, ishwori_42])
gunaraj_41.add_childs([suryamani_42])
ramanath_41.add_childs([janardan_42, raghu_42])
balaram_41.add_childs([sudarshan_42, gokul_42, madan_42])
dillinath_41.add_childs([madhav_42, parshuram_42])
toyanath_41.add_childs([sita_ram_42])
bhuminanda_41.add_child(dillinath_42)
buddhinath_41.add_childs([basudev_42, debarshi_42, mukunda_42])
angirash_41.add_childs([bishnugopal_42, kedar_42, hari_42, parasar_42])

dhruva_42.add_childs([rishiram_43, rajan_43])
ishwori_42.add_childs([chiranjibi_43, uttam_43, narottam_43])
suryamani_42.add_child(mahesh_43)
janardan_42.add_childs([niranjan_43, manohar_43])
raghu_42.add_child(krishna_murari_43)
sudarshan_42.add_childs([deepak_43_2, ashok_43, bibek_43])
gokul_42.add_child(ujjwol_43)
madan_42.add_child(dipesh_43)
madhav_42.add_childs([tanka_43, dadhi_43, rewati_43,manoj_43])
parshuram_42.add_child(achyut_43)
sita_ram_42.add_childs([purushottam_43, basanta_43, bishwonath_43, damodar_43])
dillinath_42.add_childs([ram_43, laxman_43])
basudev_42.add_child(ramhari_43)
debarshi_42.add_childs([haribol_43, anup_43, binod_43_2, sanod_43])
mukunda_42.add_childs([suresh_43, dinesh_43])

bishnugopal_42.add_childs([narayan_43, bhagawan_43, pushpa_raj_43, madhu_sudan_43])
kedar_42.add_child(kalyan_43)
hari_42.add_childs([sudhir_43, prabakar_43])
parasar_42.add_child(sunil_43)

rishiram_43.add_childs([saroj_44, sabin_44, suman_44])
purushottam_43.add_child(keshav_44)
basanta_43.add_child(sanjay_44)
bishwonath_43.add_child(bimal_44)
damodar_43.add_child(sagar_44)
ram_43.add_childs([ajij_44, amish_44])
laxman_43.add_childs([ashok_44, anup_44, anil_44])
ramhari_43.add_child(sujan_44)
haribol_43.add_child(ajay_44)
anup_43.add_childs([anish_44, manish_44])
binod_43_2.add_child(aaditya_44)

narayan_43.add_child(aashish_44)
bhagawan_43.add_child(pravesh_44)
pushpa_raj_43.add_childs([suraj_44, niraj_44])
madhu_sudan_43.add_child(kushal_44)
kalyan_43.add_child(subhanga_44)

aashish_44.add_childs([aayan_45, adwik_45])

#page 29
devhari_kancha_35.add_child(rishi_36)
rishi_36.add_childs([hari_narayan_37])
hari_narayan_37.add_childs([shree_lal_38, ram_nath_38])
shree_lal_38.add_child(narandutta_39)
ram_nath_38.add_child(kedarnath_39)

#page 30
narandutta_39.add_child(balbhadra_40)
kedarnath_39.add_child(dadhilal_40)
balbhadra_40.add_child(devhari_41)
dadhilal_40.add_child(sahadutta_41)
devhari_41.add_child(lokraj_42)
sahadutta_41.add_child(damodar_42)

lokraj_42.add_childs([sadananda_43, homraj_43, kulbahadur_43, balkrishna_43])
sadananda_43.add_childs([pushparaj_44, aatmanath_44, kirtinath_44, rajaram_44])
homraj_43.add_child(balmiki_44)
kulbahadur_43.add_childs([upendra_44, raju_44, saroj_44_2, suraj_44_2])
balkrishna_43.add_child(sudeep_44)

pushparaj_44.add_child(ramraj_45)
aatmanath_44.add_childs([manoj_45, shyam_krishna_45])
kirtinath_44.add_childs([pramod_45, sudan_45, suman_45])
rajaram_44.add_child(naniram_45)
balmiki_44.add_childs([dharmaraj_45, kulraj_45])
upendra_44.add_child(kapil_45)

#Page 31
gangaram_34.add_childs([kashiram_35, kapil_35, gopal_35, jayanarayan_35])
kashiram_35.add_child(kamalpati_36)
kamalpati_36.add_childs([prajapati_37, punyashil_37, krishnananda_37, basudev_37])
punyashil_37.add_childs([dev_narayan_38, basistha_38, bishwamitra_38, parmananda_38])
basistha_38.add_childs([ganapati_39, ramchandra_39, laxman_39, shree_kanta_39, ramakanta_39])
ganapati_39.add_childs([narandutta_40])
narandutta_40.add_childs([nanda_lal_41, prabhunath_41, chudamani_41, thakurnath_41, keshav_raj_41, lilanath_41])

chudamani_41.add_childs([pashupati_42, ramchandra_42, gopal_42])
thakurnath_41.add_childs([govinda_42, hari_prasad_42, padmanath_42])
keshav_raj_41.add_childs([madhusudan_42, mitraprasad_42])

pashupati_42.add_childs([damodar_43_2])
ramchandra_42.add_childs([balaram_43, mukunda_43])
gopal_42.add_childs([shyamkrishna_43, madhusudan_43_2])
govinda_42.add_child(shivaram_43)
padmanath_42.add_childs([shreedhar_43, sashidhar_43])
madhusudan_42.add_childs([diwakar_43_2, suresh_43_2])
mitraprasad_42.add_childs([mahesh_43_2, dinesh_43_2])
damodar_43_2.add_childs([nirmal_44, nirjan_44])
balaram_43.add_childs([brihaspati_44, ekdev_44])
shyamkrishna_43.add_childs([sudeep_44_2, sudu_44])
madhusudan_43_2.add_child(manish_44_2)

laxman_39.add_childs([nandikeshar_40, udayananda_40])
udayananda_40.add_childs([taranath_41, thakurnath_41_2])
thakurnath_41_2.add_childs([ganesh_prasad_42, ganapati_42, kedarnath_42])
ganesh_prasad_42.add_childs([dharma_nanda_43, tika_prasad_43])
kedarnath_42.add_childs([badri_prasad_43, ramnath_43])
tika_prasad_43.add_childs([madhusudan_44, raju_44_2, raghunath_44])
badri_prasad_43.add_childs([mohan_44, navin_44, kumar_44])
ramnath_43.add_child(deepak_44)

#page 32
krishnananda_37.add_child(ramananda_38)
ramananda_38.add_childs([dharma_nanda_39, shivadutta_39])
dharma_nanda_39.add_child(manorath_40)
shivadutta_39.add_child(chandrakanta_40)
manorath_40.add_child(haribansha_41)
chandrakanta_40.add_child(kashinath_41)
haribansha_41.add_child(bhola_42)
kashinath_41.add_childs([basudev_42, dillinath_42_2, bishnuhari_42])
dillinath_42_2.add_childs([ram_prasad_43, chiranjibi_43_2])
bishnuhari_42.add_childs([kishor_43, rajkumar_43, deepak_43_3, shreedhar_43_2])

ram_prasad_43.add_childs([manoj_44, bijay_44])
chiranjibi_43_2.add_childs([pramod_44, niranjan_44])
kishor_43.add_childs([jeewan_44, suraj_44_3])

#page 34
bhrigu_34.add_child(agnidhar_35)
agnidhar_35.add_childs([satyadhar_36, gangadhar_36])
satyadhar_36.add_childs([dev_narayan_37, punyashil_37_2])
gangadhar_36.add_child(ramu_37)
ramu_37.add_child(prayagdut_38)
prayagdut_38.add_child(kashinath_39_2)

dev_narayan_37.add_child(gokul_38)
punyashil_37_2.add_child(baijanath_38)
baijanath_38.add_childs([birbhadra_39, makarananda_39])

birbhadra_39.add_childs([kataka_bahadur_40, shumsher_bahadur_40])
makarananda_39.add_childs([hari_narayan_40, laxminath_40, jeewanath_40])
kataka_bahadur_40.add_childs([gopal_41, lal_bahadur_41])
shumsher_bahadur_40.add_childs([khadgav_bahadur_41, padma_bahadur_41])
hari_narayan_40.add_childs([laxmikanta_41, bhojraj_41, shankar_41, keshav_41])
laxminath_40.add_child(hariprasad_41)

#page 35

khadgav_bahadur_41.add_child(ganesh_bahadur_42)
shankar_41.add_childs([deepak_42_2, shreedhar_42, rajesh_42])
keshav_41.add_childs([jeewan_42, shrawan_42, bimal_42])
hariprasad_41.add_childs([badri_prasad_42, kedar_42_2, shyam_42, jagannath_42, balaram_42])
ganesh_bahadur_42.add_childs([bel_bahadur_43, om_bahadur_43, ramsharan_43, harisharan_43])
deepak_42_2.add_childs([abhishek_43])
badri_prasad_42.add_childs([maniram_43, uddhav_43, uttam_43])
kedar_42_2.add_childs([dwarika_43, krishna_prasad_43])
shyam_42.add_child(purushottam_43_2)
balaram_42.add_child(uday_43)

bel_bahadur_43.add_child(hira_bahadur_44)
om_bahadur_43.add_child(harisharan_44)
ramsharan_43.add_childs([shivasharan_44, sashindra_44])
harisharan_43.add_child(krishnasharan_44)
maniram_43.add_child(laba_prasad_44)

jeewanath_40.add_childs([pitambar_41, muktinath_41, minanath_41])
pitambar_41.add_childs([harischandra_42, hareram_42, harisharan_42])
minanath_41.add_childs([harinath_42, sharad_prasad_42])

#page 36
bali_34.add_childs([moksheswor_35, sreeram_35, ramkrishna_35, bamdev_35])
moksheswor_35.add_child(chandramadi_36)
chandramadi_36.add_childs([tikaram_37, laxmidhar_37, liladhar_37])
tikaram_37.add_childs([haribamsha_38, shivanath_38])
haribamsha_38.add_childs([shyamlal_39, laxminath_39_2, narayan_39])
shivanath_38.add_childs([vishwo_nath_39, makardwoj_39, ganapati_39_2])

shyamlal_39.add_child(shreebilas_40)
laxminath_39_2.add_childs([hitakanta_40, gajabinod_40, nandalal_40])
narayan_39.add_child(sashidhar_40)
vishwo_nath_39.add_child(chiranjibi_40)

shreebilas_40.add_childs([sadananda_41, narandutta_41, chandrakanta_41])
hitakanta_40.add_child(chabilal_41)
nandalal_40.add_childs([tankanath_41, khomnath_41, vishwo_nath_41])
chiranjibi_40.add_childs([sukadev_41, gangasagar_41])

#page 37
chandrakanta_41.add_child(gopilal_42)
chabilal_41.add_childs([hemnath_42])
khomnath_41.add_childs([gopal_42_2, rishi_42])
vishwo_nath_41.add_child(laxminath_42)
sukadev_41.add_childs([gopi_krishna_42, bhojraj_42])
gangasagar_41.add_childs([muktinath_42, narayan_42])

gopilal_42.add_childs([sashyam_prasad_43, ram_krishna_43])
hemnath_42.add_child(shyam_prasad_43)
rishi_42.add_childs([madhu_43_2, hari_43, bharat_43])
laxminath_42.add_childs([ishwor_43, niranjan_43_2])
gopi_krishna_42.add_child(gokul_43)
bhojraj_42.add_childs([purna_prasad_43, saroj_43])
muktinath_42.add_childs([bhairav_43, gyan_prasad_43])
narayan_42.add_childs([binod_prasad_43])

gokul_43.add_childs([byapak_44, binay_44])
gyan_prasad_43.add_childs([prajyan_44, pawan_44])
binod_prasad_43.add_child(murari_44)

makardwoj_39.add_child(taranath_40)
taranath_40.add_childs([siva_prasad_41, sita_ram_41])
siva_prasad_41.add_childs([dasrath_42, gokul_42_2, ashok_42, surya_42])
sita_ram_41.add_childs([chandika_prasad_42, niranjan_42])
chandika_prasad_42.add_child(ullas_punja_43)


#Page 38
laxmidhar_37.add_child(purna_bhadra_38)
purna_bhadra_38.add_childs([hari_lal_39_2, gauri_kanta_39, modnath_39])
hari_lal_39_2.add_childs([dilliram_40, chakrapani_40_2, ganesh_prasad_40, ratna_prasad_40])
modnath_39.add_childs([dandapani_40_2, padma_narayan_40])
ganesh_prasad_40.add_childs([bishnu_prasad_41, durga_prasad_41, sudarshan_41])
ratna_prasad_40.add_childs([krishna_prasad_41_2, gopal_41_2])

bishnu_prasad_41.add_childs([uddhav_42, shyam_42_1, krishna_prasad_42, baikuntha_42])
durga_prasad_41.add_childs([ramesh_42, dinesh_42, saroj_42, basanta_42])
sudarshan_41.add_childs([niraj_42, rajan_42, rajesh_42_1, bhusan_42, ashok_42])

krishna_prasad_41_2.add_childs([shreeram_42_1, mukunda_42_1])
gopal_41_2.add_childs([madhuwan_42, madhav_42_2])

uddhav_42.add_child(deepak_43_4)
krishna_prasad_42.add_child(suchit_43)
ramesh_42.add_child(pawan_43_2)
saroj_42.add_childs([sourya_43, saurav_43])

shreeram_42_1.add_child(santosh_43)
mukunda_42_1.add_child(saroj_43_2)
madhuwan_42.add_childs([mahesh_43_3, anupam_43])

#Page 39
liladhar_37.add_childs([pashupati_38, ganapati_38])
pashupati_38.add_childs([padmanath_39, kashinath_39_3])
ganapati_38.add_child(umanath_39)

padmanath_39.add_child(kalu_40)
kashinath_39_3.add_childs([muktinath_40, sadananda_40, emanath_40, bhimnath_40])
umanath_39.add_child(narayan_40)
narayan_40.add_childs([ram_41, krishna_41, bharat_41])
kalu_40.add_childs([sukadev_41_2, dalbahadur_41])
sadananda_40.add_child(gopal_41_3)
bhimnath_40.add_childs([ramjeev_41, shyamjeev_41, sahadev_41, arjun_41, prahlad_41, kamal_41])

sukadev_41_2.add_child(nanibabu_42)
dalbahadur_41.add_childs([rameshor_42, achyut_42, shreeram_42_2])
gopal_41.add_childs([shyam_krishna_42, shyam_kaji_42, hari_prasad_42, sundar_42])

ramjeev_41.add_child(bidur_42)
shyamjeev_41.add_childs([purushottam_42, krishnasharan_42])
sahadev_41.add_childs([jayaraj_42])
arjun_41.add_childs([sudama_42, suresh_42])
prahlad_41.add_childs([govinda_42_1])
kamal_41.add_childs([shambu_42])

shyam_krishna_42.add_childs([nabaraj_43, chitra_43, habbu_43, kailash_43])
shyam_kaji_42.add_childs([umesh_43])
hari_prasad_42.add_childs([radheshyam_43, ghanashyam_43])
sundar_42.add_child(dinesh_43_3)

#Page 40
ramkrishna_35.add_childs([su_ramnath_36, prabhunath_36, ranganath_36, siromani_36, trilokya_36])
su_ramnath_36.add_childs([su_brajmohan_37, yagyanidhi_37])
ranganath_36.add_child(ganapati_37)

su_brajmohan_37.add_childs([krishnamohan_38, lalitmohan_38, chaturmohan_38, chandramohan_38])
chaturmohan_38.add_childs([harimohan_39, rudramohan_39, lokmohan_39, ganeshmohan_39, premmohan_39, yogmohan_39])
chandramohan_38.add_childs([buddhimohan_39])

rudramohan_39.add_childs([ram_prasad_40, narayan_40_2])
premmohan_39.add_child(dhruvamohan_40)
buddhimohan_39.add_childs([tejmohan_40, harshamohan_40, yankamohan_40])

ram_prasad_40.add_childs([padmanath_41, binod_41, pramod_41])
narayan_40_2.add_child(amrit_41)
dhruvamohan_40.add_childs([damodar_41, radhakrishna_41, bamshidhar_41])
tejmohan_40.add_childs([yadav_41, suraj_41, suman_41])
harshamohan_40.add_child(sanjay_41)

#Page 41
binod_41.add_childs([sunod_42, sushan_42])
damodar_41.add_childs([ramesh_42_2, pradeep_42, prakash_42])
bamshidhar_41.add_child(kumud_42)
yadav_41.add_childs([enoj_42, manoj_42, anil_42])

yagyanidhi_37.add_childs([brahmananda_38, gaurinath_38, ambarnath_38, rewatiraman_38, ramakanta_38, pradhumna_38, kabikulkeshari_38, sadananda_38, kashinath_38, tejprasad_38])
brahmananda_38.add_child(yogmohan_39)
gaurinath_38.add_childs([krishna_dutta_39, pitambar_39])
ambarnath_38.add_child(vishwo_nath_39_2)
rewatiraman_38.add_child(chiranjibi_39)
ramakanta_38.add_childs([tejprasad_39, maila_39, jeevprasad_39])
pradhumna_38.add_childs([tankanath_39, yug_prasad_39, bhure_39])
kabikulkeshari_38.add_childs([gwange_39, jhankanath_39])
sadananda_38.add_childs([homnath_39, maya_prasad_39])

yogmohan_39.add_child(tej_prasad_40)
krishna_dutta_39.add_child(tejpinath_40)
pitambar_39.add_child(krishna_prasad_40)
vishwo_nath_39_2.add_child(devi_prasad_40)
chiranjibi_39.add_child(prem_raj_40)
yug_prasad_39.add_childs([pushpa_raj_40, thute_40])

devi_prasad_40.add_childs([ramji_41])
prem_raj_40.add_childs([ramraj_41, laxman_41])
ramraj_41.add_childs([vidyaraj_42, nabaraj_42, raju_42])
laxman_41.add_childs([ratna_42, vijay_42])

#Page 42
sreeram_35.add_childs([narad_36, dinakar_36, prabhakar_36, antare_36, kancha_36])
narad_36.add_childs([laxmikanta_37, chandrasekhar_37])
dinakar_36.add_child(baburam_37)
chandrasekhar_37.add_childs([nandalal_38, harinanda_38, chandrakanta_38])

nandalal_38.add_childs([agnidhar_39, yadunath_39, gurudutta_39, dharmananda_39, bedimadhav_39])
chandrakanta_38.add_childs([govinda_39, damodar_39])
yadunath_39.add_child(jagannath_40)
gurudutta_39.add_child(ramji_40)
dharmananda_39.add_childs([bholanath_40, madhav_40])
bedimadhav_39.add_child(nabaraj_40)

#Page 43
jagannath_40.add_childs([binod_41_2, bijayanath_41, pramod_41_2, subodh_41])
bholanath_40.add_childs([nayanath_41, samanath_41, brihaspati_41, rukhmanath_41, grihanath_41])
nabaraj_40.add_childs([shankar_41_2, deepak_41, sudarshan_41_2, nirmal_41])
bijayanath_41.add_childs([ajay_42, sanjay_42, pradeep_42_1])
pramod_41_2.add_child(uttam_42)
nayanath_41.add_childs([bodhnath_42, heli_42])
samanath_41.add_child(heman_42)

shankar_41_2.add_child(sabij_42)
deepak_41.add_childs([manish_42, anish_42])

prabhakar_36.add_childs([damodar_37, mitralal_37, sadananda_37])
damodar_37.add_child(chetnath_38)
chetnath_38.add_child(badri_39)
badri_39.add_childs([mahesh_40, shyamhari_40])

#Page 44
laxmikanta_37.add_childs([maheshwor_38, shiva_dutta_38_2, bam_bahadur_38, bir_bahadur_38, bhairab_bahadur_38, kataka_bahadur_38, amar_bahadur_38])
maheshwor_38.add_child(bhuwaneshor_39)
shiva_dutta_38_2.add_childs([ganesh_dutta_39])
bhuwaneshor_39.add_childs([shiva_prasad_40, sthaleshor_40])
ganesh_dutta_39.add_childs([ranganath_40, fadindranath_40, devi_prasad_40_1, jhankanath_40, homanath_40])

sthaleshor_40.add_childs([kedar_bahadur_41, krishna_bahadur_41, arjun_bahadur_41, badri_prasad_41_2, shyam_prasad_41, damodar_prasad_41])
ranganath_40.add_childs([jagannath_41, tarkaraj_41])
fadindranath_40.add_childs([chiranjibi_41, rishi_41])
devi_prasad_40_1.add_childs([hari_41, shyam_41])
jhankanath_40.add_child(ramhari_41)

jagannath_41.add_childs([bishwo_nath_42_1, badri_prasad_42_1])
tarkaraj_41.add_child(kiran_42)
chiranjibi_41.add_childs([ravi_42, mani_42, kumar_42_2, jeewan_42_1])

bishwo_nath_42_1.add_childs([diwakar_43_3, prabhakar_43])
badri_prasad_42_1.add_child(suman_43)
kiran_42.add_childs([sagar_43, sudhakar_43])
ravi_42.add_childs([bhaskar_43, sankar_43])
mani_42.add_child(mahesh_43_4)

#page 45
bam_bahadur_38.add_childs([ganesh_bahadur_39, kul_bahadur_39])
ganesh_bahadur_39.add_childs([moti_bahadur_40, gagan_bahadur_40, murli_40])
kul_bahadur_39.add_childs([krishna_bahadur_40, balaram_40, indra_bahadur_40])
moti_bahadur_40.add_childs([punya_bahadur_41])
gagan_bahadur_40.add_child(amir_bahadur_41)
krishna_bahadur_40.add_child(kamal_bahadur_41)
balaram_40.add_childs([bishnu_41, bijay_41, arjun_41, keshav_41_2, rajan_41])
indra_bahadur_40.add_childs([sudama_41, kapil_41, dil_bahadur_41])

punya_bahadur_41.add_childs([rajendra_42, devendra_42, surendra_42, rabindra_42, rupendra_42])
amir_bahadur_41.add_child(laxman_42)
kamal_bahadur_41.add_childs([rajaram_42, shantaram_42, surya_kumar_42, purna_kumar_42, ram_chandra_42])
bishnu_41.add_childs([prakash_42_1, kiran_42_1, roshan_42, chidananda_42])
bijay_41.add_childs([suman_42, sudan_42])

bhairab_bahadur_38.add_child(bhakta_bahadur_39)
bhakta_bahadur_39.add_child(dol_bahadur_40)
kataka_bahadur_38.add_childs([sete_39, bharat_bahadur_39, tilak_bahadur_39])
bharat_bahadur_39.add_child(ram_bahadur_40)
tilak_bahadur_39.add_childs([krishna_bahadur_40_1, purna_bahadur_40])

#page 46
dol_bahadur_40.add_childs([shiva_hari_41, krishna_hari_41])
ram_bahadur_40.add_childs([babu_kaji_41, shiva_41])
krishna_bahadur_40_1.add_childs([bal_gopal_41, rajendra_41])
purna_bahadur_40.add_childs([nabaraj_41, prahlad_41_2])
babu_kaji_41.add_childs([ramkumar_42])
shiva_41.add_childs([shyam_42_2, krishna_42_2, bishnu_42, niranjan_42_2])

bamdev_35.add_child(shree_hari_36)
shree_hari_36.add_childs([brahma_37, sree_krishna_37])
brahma_37.add_childs([shivanav_38, bal_krishna_38])
bal_krishna_38.add_childs([pashupati_39, bhaskar_39])
pashupati_39.add_child(padmanav_40)
bhaskar_39.add_childs([dasrath_40, mayanath_40])

padmanav_40.add_childs([hemnav_41, basudev_41])
dasrath_40.add_childs([laxmikanta_41_2])
mayanath_40.add_childs([ganeshnath_41, bhimnath_41, damodar_41_2, maan_bahadur_41, bartaman_singh_41_2])

hemnav_41.add_childs([radhakrishna_42])
basudev_41.add_childs([ratna_prasad_42, pradhumna_42])
laxmikanta_41_2.add_childs([gopal_42_1, krishna_42_1, keshav_42, harihar_42])
ganeshnath_41.add_childs([ramji_42, krishna_42_3, narandutta_42])

ratna_prasad_42.add_child(sunil_43_2)
pradhumna_42.add_child(bikash_43)
gopal_42_1.add_childs([bhanu_kumar_43, shashi_kumar_43])
harihar_42.add_childs([madhav_43, achyut_43, sushil_43, mahesh_43_5, ramesh_43, suresh_43_3])
ramji_42_2.add_childs([kedar_43, bishnu_43, shambhu_43])
madhav_43.add_child(sanjay_44_2)
kedar_43.add_childs([sanjiv_44, saroj_44_3, santosh_44])
bishnu_43.add_child(sudeep_44_3)
shambhu_43.add_child(suman_44_2)

#page 48
bhimnath_41.add_childs([jagannath_42_2])
damodar_41_2.add_childs([chudamani_42, buddhisagar_42])
maan_bahadur_41.add_childs([narayan_42_2, krishna_42_4, ram_bahadur_42])
bartaman_singh_41_2.add_childs([ramji_42_2])

jagannath_42_2.add_childs([govinda_43, dhruva_43, keshav_43])
chudamani_42.add_childs([bharat_43_2, shyam_43])
buddhisagar_42.add_child(sita_ram_43)
narayan_42_2.add_childs([kamal_43, dhruva_43_2])
krishna_42_4.add_childs([durga_43])
ram_bahadur_42.add_childs([rameshwor_43, yagya_bahadur_43, yuddha_bahadur_43])
ramji_42_2.add_childs([badri_43, kedar_43_2, uttam_43_3])

govinda_43.add_child(gopal_44)
dhruva_43.add_child(niraj_44_2)
bharat_43_2.add_child(subash_44)
kamal_43.add_child(uttam_44)
dhruva_43_2.add_child(dinesh_44_2)
durga_43.add_childs([mahesh_44, ramesh_44_2, madan_44])
badri_43.add_child(dayaram_44)
kedar_43_2.add_child(bishnu_44)

parmananda_34.add_childs([murali_35, purshuram_35, markandeya_35])
murali_35.add_child(balbhadra_36)
balbhadra_36.add_childs([govinda_37, sreebilas_37, badibilas_37])
#page 49
govinda_37.add_child(pundarika_38)
sreebilas_37.add_childs([ramakanta_38_2, umakanta_38, chandrasekhar_38, lekhnath_38, nayakeshari_38, ghananath_38, moksheswor_38, agnisanta_38, nabaraj_38, dasrath_38])
lekhnath_38.add_childs([jangadwoj_39, krishna_bahadur_39])
nabaraj_38.add_childs([gobre_39, gopal_39, shankar_39])
gobre_39.add_child(gute_40)
shankar_39.add_child(krishna_40)

jangadwoj_39.add_child(padma_bahadur_40)
padma_bahadur_40.add_childs([krishna_bahadur_41_2, hiranya_bahadur_41])
hiranya_bahadur_41.add_child(shankar_42)
krishna_bahadur_39.add_child(chandra_bahadur_40)
chandra_bahadur_40.add_child(narayan_bahadur_41)

badibilas_37.add_childs([hari_lal_38, nayakeshari_38_2])
hari_lal_38.add_childs([ram_chandra_39, laxman_39_2])
nayakeshari_38_2.add_childs([devdutta_39, bidyakanta_chankhe_39])
dasrath_38.add_childs([lilanath_39, ram_prasad_39, rudranath_39, lekhnath_39])
devdutta_39.add_childs([babulal_40, purna_bahadur_40_2, ambar_bahadur_40])
lilanath_39.add_childs([keshav_40, bishwonath_40, kirtinath_40, hari_40])

ram_prasad_39.add_childs([purshuram_40, bishnu_40, shivakumar_40])
babulal_40.add_child(ramchandra_41)
purna_bahadur_40_2.add_childs([ganesh_bahadur_41])
ambar_bahadur_40.add_childs([shyam_bahadur_41, sambhu_bahadur_41])
purshuram_40.add_childs([pushpa_raj_41])
bishnu_40.add_childs([pradeep_41, niroj_41])
shivakumar_40.add_childs([sarad_kumar_41, sree_kumar_41])

ramchandra_41.add_childs([govinda_42_2, sudarshan_42_2, madhav_42_3])
ganesh_bahadur_41.add_childs([narayan_42_3, kedar_42_3])
shyam_bahadur_41.add_childs([ramesh_42_3, rameshwor_42, rajendra_42_2])
sambhu_bahadur_41.add_child(shiva_bahadur_42)
pushpa_raj_41.add_childs([kiran_42_2, kishor_42])

purshuram_35.add_child(hari_36)
hari_36.add_child(ramananda_37)
ramananda_37.add_childs([liladhar_38, jayabhadra_38])

#page 51
liladhar_38.add_child(taranath_39)
jayabhadra_38.add_childs([loknath_39, prabhunath_39, sadananda_39])
taranath_39.add_childs([prayagdut_40, purushottam_40, narayan_40_3])
loknath_39.add_childs([chabilal_40, kubernath_40])

prayagdut_40.add_child(ganesh_bahadur_41_2)
purushottam_40.add_child(premnath_41_2)
chabilal_40.add_childs([byas_41, sukadev_41_3, gunaraj_41_2, bhawaraj_41])
kubernath_40.add_childs([dhruva_prasad_41, kapil_dev_41])

ganesh_bahadur_41_2.add_child(ram_kaji_42)
premnath_41_2.add_child(basudev_42_2)
byas_41.add_childs([laxman_42_2, binod_42])
sukadev_41_3.add_child(ramgopal_42)
gunaraj_41_2.add_child(ranjan_raj_42)
dhruva_prasad_41.add_childs([sitaram_42, shivanath_42, ram_prasad_42])
kapil_dev_41.add_child(hari_prasad_42_2)
basudev_42_2.add_childs([bishesh_43, bibek_43_2])
sitaram_42.add_childs([raju_prasad_43])
shivanath_42.add_child(sancha_43)
hari_prasad_42_2.add_childs([saroj_43_3, manoj_43_2])

#Page 52
###### all done
prabhunath_39.add_childs([homnath_40])
sadananda_39.add_childs([padmanidhi_40, gangadutta_40, tulsiram_40])
homnath_40.add_childs([narayan_41, shiva_hari_41_2])
padmanidhi_40.add_childs([tulsi_prasad_41, makarananda_41, huta_prasad_41, ghananath_41, narayan_41_2])
tulsiram_40.add_child(khecharnath_41)

narayan_41.add_childs([prem_kumar_42, ramesh_42_4])
makarananda_41.add_childs([aatma_ram_42_2, badri_42_2, basudev_42_3, dayanidhi_42])
huta_prasad_41.add_childs([bal_krishna_42, kedar_42_4, govinda_42_3])
ghananath_41.add_childs([keshav_42_3, shambu_42_2])
narayan_41_2.add_child(shyam_prasad_42)
khecharnath_41.add_childs([baburam_42, krishna_42_5, bishnu_42_2])

prem_kumar_42.add_child(pawan_43)
ramesh_42.add_childs([rujhan_43, ranjan_43])
aatma_ram_42_2.add_child(shivakumar_43)
badri_42_2.add_childs([gopal_43, prithu_43, parshu_43, laxman_43_2])
dayanidhi_42
keshav_42_3


laxman_43_2 = Person("Laxman", nepali_name="लक्ष्मण")
shyamsundar_43 = Person("Shyamsundar", nepali_name="श्यामसुन्दर")
ram_43_2 = Person("Ram", nepali_name="राम")
ghanashyam_43_2 = Person("Ghanashyam", nepali_name="घनश्याम")
binod_43_3 = Person("Binod", nepali_name="विनोद")
narayan_43_2 = Person("Narayan", nepali_name="नारायण")
rajendra_43 = Person("Rajendra", nepali_name="राजेन्द्र")
binod_43_4 = Person("Binod", nepali_name="विनोद")
shambhu_43_2 = Person("Shambhu", nepali_name="शम्भु")
ramesh_43_2 = Person("Ramesh", nepali_name="रमेश")
kedar_43_3 = Person("Kedar", nepali_name="केदार")
rameshwor_43_3 = Person("Rameshwor", nepali_name="रामेश्वर")
raju_43 = Person("Raju", nepali_name="राजु")
deepak_43_5 = Person("Deepak", nepali_name="दीपक")









