import json
from genealogy_class import Person

gopal_31 = Person("Gopal", 1940)
ram_bhadra_32 = Person("Ram Bhadra", None)
govinda_33 = Person("Govinda", None)
prajapati_33 = Person("Prajapati", None)
chamu_33 = Person("Chamu", None)
gautam_34 = Person("Gautam", None)
laxmidhar_35 = Person("Laxmidhar", None)
ramchandra_35 = Person("RamChandra", None)
devhari_kancha_35 = Person("DevHari", None)
laxminarayan_36 = Person("LaxmiNarayan", None)
VidyaNanda_37 = Person("VidyaNanda", None)
DharmaNanda_38 = Person("DharmaNanda", None)
HariLal_39 = Person("HariLal", None)
ShivaNidhi_40 = Person("ShivaNidhi", None)
GedLal_41 = Person("GedLal", None)
Lekhnath_41 = Person("LekhNath", None)
Premnath_41 = Person("PremNath", None)
RamChandra_35 = Person("RamChandra", None)
Ratan_36 = Person("Ratan", None)
Nini_37 = Person("Nini", None)
VijayaNanda_38 = Person("VijayaNanda", None)
GauriShankar_39 = Person("GauriShankar", None)
Eknath_42 = Person("EkNath", None)

Ratan_36 = Person("Ratan", None)
Nini_37 = Person("Nini", None)
VijayaNanda_38 = Person("VijayaNanda", None)
GauriShankar_39 = Person("GauriShankar", None)

Ram_42 = Person("Ram", None)
Krishna_42 = Person("Krishna", None)
Badri_42 = Person("Badri", None)
VishwoNath_42 = Person("VishwoNath", None)

PremNath_41 = Person("PremNath", None)
AatmaRam_42 = Person("AatmaRam", None)

Ananta_43 = Person("Ananta", None)
Harihar_43 = Person("Harihar", None)
Binod_43 = Person("Binod", None)
Pramod_43 = Person("Pramod", None)
Amod_43 = Person("Ammod", None)
Arun_43 = Person("Arun", None)
ShivaNath_43 = Person("ShivaNath", None)
Deepak_43 = Person("Deepak", None)
Diwakar_43 = Person("Diwakar", None)

Praveen_44 = Person("Praveen", None)
Vivek_44 = Person("Vivek", None)
Prashant_44 = Person("Prashant", None)

Laxmidhar_35 = Person("Laxmidhar", None)
Rambhadra_36 = Person("Rambhadra", None)
Ghanashyam_37 = Person("Ghanashyam", None)

ShivaDutta_38 = Person("ShivaDutta", None)
BishnuDutta_38 = Person("BishnuDutta", None)
RamDutta_38 = Person("RamDutta", None)
HariDutta_38 = Person("HariDutta", None)

Padmalochan_39 = Person("Padmalochan", None)
Buddhinath_39 = Person("Buddhinath", None)
Laxminath_39 = Person("Laxminath", None)
Jeewanath_39 = Person("Jeewanath", None)
Kashinath_39 = Person("Kashinath", None)

Chakrapani_40 = Person("Chakrapani", None)
Dandapani_40 = Person("Dandapani", None)

GuruPrasad_41 = Person("GuruPrasad", None)
Gunaraj_41 = Person("Gunaraj", None)
Ramanath_41 = Person("Ramanath", None)
Balaram_41 = Person("Balaram", None)
Dilliram_41 = Person("Dilliram", None)

Toyanath_41 = Person("Toyanath", None)
KrishnaPrasad_41 = Person("KrishnaPrasad", None)
SitaRam_42 = Person("SitaRam", None)
Purushottam_43 = Person("Purushottam", None)
Basanta_43 = Person("Basanta", None)
Bishwonath_43 = Person("Bishwonath", None)
Damodar_43 = Person("Damodar", None)

Dhruva_42 = Person("Dhruva", None)
Ishwori_42 = Person("Ishwori", None)
Suryamani_42 = Person("Suryamani", None)
Janardan_42 = Person("Janardan", None)
Raghu_42 = Person("Raghu", None)
Sudarshan_42 = Person("Sudarshan", None)
Gokul_42 = Person("Gokul", None)
Madan_42 = Person("Madan", None)
Madhav_42 = Person("Madhav", None)
Parshuram_42 = Person("Parshuram", None)

Rishiram_43 = Person("Rishiram", None)
Rajan_43 = Person("Rajan", None)
Chiranjibi_43 = Person("Chiranjibi", None)
Uttam_43 = Person("Uttam", None)
Narottam_43 = Person("Narottam", 1983)
Mahesh_43 = Person("Mahesh", None)

Badibilas_40 = Person("Badibilas", None)
Bavanath_40 = Person("Bavanath", None)
Naranath_40 = Person("Naranath", None)
GaneshDutta_40 = Person("GaneshDutta", 1889)

Bhuminanda_41 = Person("Bhuminanda", None)
Buddhinath_41 = Person("Buddhinath", None)

Angirash_41 = Person("Angirash", 1906)

Dillinath_42 = Person("Dillinath", None)
Basudev_42 = Person("Basudev", None)
Debarshi_42 = Person("Debarshi", None)
Mukunda_42 = Person("Mukunda", None)
Bishnugopal_42 = Person("Bishnugopal", None)
Kedar_42 = Person("Kedar", None)
Hari_42 = Person("Hari", None)
Parasar_42 = Person("Parasar", None)

Ram_43 = Person("Ram", None)
Laxman_43 = Person("Laxman", None)
Ramhari_43 = Person("Ramhari", None)
Haribol_43 = Person("Haribol", None)
Anup_43 = Person("Anup", None)
Binod_43 = Person("Binod", 1974)
Sanod_43 = Person("Sanod", None)
Suresh_43 = Person("Suresh", None)
Dinesh_43 = Person("Dinesh", None)
Narayan_43 = Person("Narayan", 1955)
Bhagawan_43 = Person("Bhagawan", 1961)
Pushpa_43 = Person("Pushpa", 1967)
Madhu_43 = Person("Madhu", None)
Kalyan_43 = Person("Kalyan", 1986)
Sudhir_43 = Person("Sudhir", None)
Prabakar_43 = Person("Prabakar", None)
Sunil_43 = Person("Sunil", None)

Ajij_44 = Person("Ajij", None)
Amish_44 = Person("Amish", None)
Ashok_44 = Person("Ashok", None)
Anup_44 = Person("Anup", None)
Anil_44 = Person("Anil", None)

Sujan_44 = Person("Sujan", None)
Ajay_44 = Person("Ajay", None)
Anish_44 = Person("Anish", None)
Manish_44 = Person("Manish", None)
Aaditya_44 = Person("Aaditya", None)

Aashish_44 = Person("Aashish", 1983)
Pravesh_44 = Person("Pravesh", 1991)
Niraj_44 = Person("Niraj", 1991)
Suraj_44 = Person("Suraj", 1991)
Kushal_44 = Person("Kushal", 1995)

Aayan_45 = Person("Aayan", 2017)
Adwik_45 = Person("Adwik", 2019)
Samyog_44 = Person("Samyog", None)

DevHari_Kancha_35 = Person("DevHari", None)
Rishi_36 = Person("Rishi", None)
HariNarayan_37 = Person("HariNarayan", None)
ShreeLal_38 = Person("ShreeLal", None)
RamNath_38 = Person("RamNath", None)

Narandutta_39 = Person("Narandutta", None)
Kedarnath_39 = Person("Kedarnath", None)

Balabhadra_40 = Person("Balabhadra", None)
Devahari_41 = Person("Devahari", None)
Lokaraj_42 = Person("Lokaraj", None)

Dadhilal_40 = Person("Dadhilal", None)
Sahadutta_41 = Person("Sahadutta", None)
Damodar_42 = Person("Damodar", None)

Sadananda_43 = Person("Sadananda", None)
Homraj_43 = Person("Homraj", None)
Kulbahadur_43 = Person("Kulbahadur", None)
Balkrishna_43 = Person("Balkrishna", None)


Pushraj_44 = Person("Pushraj", None)
Aatmanath_44 = Person("Aatmanath", None)
Kirtinath_44 = Person("Kirtinath", None)
Rajaram_44 = Person("Rajaram", None)
Balmiki_44 = Person("Balmiki", None)
Upendra_44 = Person("Upendra", None)
Raju_44 = Person("Raju", None)
Saroj_44 = Person("Saroj", None)
Suraj_44_2 = Person("Suraj", None)
Sudeep_44 = Person("Sudeep", None)

Ramraj_45 = Person("Sudeep", None)
Manoj_45 = Person("Sudeep", None)
ShyamKrishna_45 = Person("Sudeep", None)
Pramod_45 = Person("Sudeep", None)
Sudan_45 = Person("Sudeep", None)
Suman_45 = Person("Sudeep", None)
Naniram_45 = Person("Sudeep", None)
Dharmaraj_45 = Person("Sudeep", None)
Kulraj_45 = Person("Sudeep", None)
Kapil_45 = Person("Sudeep", None)

Gangaram_34 = Person("Gangaram", None)
Kashiram_35 = Person("Kashiram", None)
Kapil_35 = Person("Kapil", None)
Gopal_35 = Person("Gopal", None)
Jayanarayan_35 = Person("Jayanarayan", None)

Kamalapati_36 = Person("Kamalapati", None)

Prajapati_37 = Person("Prajapati", None)
Punyashil_37 = Person("Punyashil", None)
Krishnananda_37 = Person("Krishnananda", None)
Bashudev_37 = Person("Bashudev", None)

DevNarayan_38 = Person("DevNarayan", None)
Basistha_38 = Person("Basistha", None)
Bishamitra_38 = Person("Bishamitra", None)
Parmananda_38 = Person("Parmananda", None)

Ganapati_39 = Person("Ganapati", None)
Ramchandra_39 = Person("Ramchandra", None)
Me_laxman_39 = Person("Me_laxman", None)
ShreeKanta_39 = Person("ShreeKanta", None)
Ramakanta_39 = Person("Ramakanta", None)

Narandutta_40 = Person("Narandutta", None)
NandaLal_41 = Person("NandaLal", None)
Prabhunath_41 = Person("Prabhunath", None)
Chudamani_41 = Person("Chudamani", None)
Thakurnath_41 = Person("Thakurnath", None)
KeshavRaj_41 = Person("KeshavRaj", None)
Lilanath_41 = Person("Lilanath", None)

Pashupati_42 = Person("Pashupati", None)
Ramchandra_42 = Person("Ramchandra", None)
Gopal_42 = Person("Gopal", None)
Govinda_42 = Person("Govinda", None)
Hariprasad_42 = Person("Hariprasad", None)
Padmanav_42 = Person("Padmanav", None)
Madhusudan_42 = Person("Madhusudan", None)
Mitraprasad_42 = Person("Mitraprasad", None)

Damodar_43 = Person("Damodar", None)
Balaram_43 = Person("Balaram", None)
Mukunda_43 = Person("Mukunda", None)
Shyamkrishna_43 = Person("Shyamkrishna", None)
Madhusudan_43 = Person("Madhusudan", None)
Shivaram_43 = Person("Shivaram", None)
Sashidhar_43 = Person("Sashidhar", None)
Diwakar_43 = Person("Diwakar", None)
Suresh_43 = Person("Suresh", None)
Mahesh_43 = Person("Mahesh", None)
Dinesh_43 = Person("Dinesh", None)

Nirmal_44 = Person("Nirmal", None)
Nirjan_44 = Person("Nirjan", None)
Brihaspati_44 = Person("Brihaspati", None)
Ekdev_44 = Person("Ekdev", None)
Sudip_44 = Person("Sudip", None)
Sudu_44 = Person("Sudu", None)
Manish_44 = Person("Manish", None)

Nandikeshar_40 = Person("Nandikeshar", None)
Udayananda_40 = Person("Udayananda", None)
Ramananda_40 = Person("Ramananda", None)

Taranath_41 = Person("Taranath", None)
Thakurnath_41_2 = Person("Thakurnath", None)
DharmaNanda_41 = Person("DharmaNanda", None)
Shivadutta_41 = Person("Shivadutta", None)

GaneshPrasad_42 = Person("GaneshPrasad", None)
Ganapati_42 = Person("Ganapati", None)
Kedarnath_42 = Person("Kedarnath", None)
Manorath_42 = Person("Manorath", None)
Chandrakanta_42 = Person("Chandrakanta", None)

DharmaNanda_43 = Person("DharmaNanda", None)
TikaPrasad_43 = Person("TikaPrasad", None)
BadriPrasad_43 = Person("BadriPrasad", None)
Ramnath_43 = Person("Ramnath", None)
Haribansha_43 = Person("Haribansha", None)
Kashinath_43 = Person("Kashinath", None)

Madhusudan_44 = Person("Madhusudan", None)
Raju_44 = Person("Raju", None)
Raghunath_44 = Person("Raghunath", None)
Mohan_44 = Person("Mohan", None)
Navin_44 = Person("Navin", None)
Kumar_44 = Person("Kumar", None)
Deepak_44 = Person("Deepak", None)
Bhola_44 = Person("Bhola", None)
Bashudev_44 = Person("Bashudev", None)
Dillinath_44 = Person("Dillinath", None)
Bishnuhari_44 = Person("Bishnuhari", None)

RamPrasad_45 = Person("RamPrasad", None)
Chiranjibi_45 = Person("Chiranjibi", None)
Kishor_45 = Person("Kishor", None)
Ramkumar_45 = Person("Ramkumar", None)
Deepak_45 = Person("Deepak", None)
Shreedhar_45 = Person("Shreedhar", None)

Manoj_45 = Person("Manoj", None)
Bijay_45 = Person("Bijay", None)
Pramod_45 = Person("Pramod", None)
Niranjan_45 = Person("Niranjan", None)
Jeewan_45 = Person("Jeewan", None)
Suraj_45 = Person("Suraj", None)

#Page 34
Bhrigu_34 = Person("Bhrigu", None)
Agnidhar_35 = Person("Agnidhar", None)

Satyadhar_36 = Person("Satyadhar", None)
Gangadhar_36 = Person("Gangadhar", None)

DevNarayan_37 = Person("DevNarayan", None)
Punyashil_37_2 = Person("Punyashil", None)
Ramu_37 = Person("Ramu", None)
Prayagdut_38 = Person("Prayagdut", None)
Kashinath_39 = Person("Kashinath", None)

Gokul_38 = Person("Gokul", None)
Baijanath_38 = Person("Baijanath", None)

Birbhadra_39 = Person("Birbhadra", None)
Katakaba_40 = Person("Katakaba", None)
Shumasheraba_40 = Person("Shumasheraba", None)
HariNarayan_40 = Person("HariNarayan", None)
Laxminath_40 = Person("Laxminath", None)
Jeewanath_40 = Person("Jeewanath", None)

Gopal_41 = Person("Gopal", None)
Lalav_41 = Person("Lalav", None)
Khadgav_41 = Person("Khadgav", None)
Padmav_41 = Person("Padmav", None)
Laxminkanta_41 = Person("Laxminkanta", None)
Bhojraj_41 = Person("Bhojraj", None)
Shankar_41 = Person("Shankar", None)
Keshav_41 = Person("Keshav", None)
Hariprasad_41 = Person("Hariprasad", None)

Ganeshav_42 = Person("Ganeshav", None)
Deepak_42 = Person("Deepak", None)
Shreedhar_42 = Person("Shreedhar", None)
Rajesh_42 = Person("Rajesh", None)
Jeewan_42 = Person("Jeewan", None)
Shrawan_42 = Person("Shrawan", None)
Bimal_42 = Person("Bimal", None)
BadriPrasad_42 = Person("BadriPrasad", None)
Kedar_42 = Person("Kedar", None)
Shyam_42 = Person("Shyam", None)
Jagannath_42 = Person("Jagannath", None)
Balaram_42 = Person("Balaram", None)

Belav_43 = Person("Belav", None)
Ohmav_43 = Person("Ohmav", None)
Ramsharan_43 = Person("Ramsharan", None)
Harisharan_43 = Person("Harisharan", None)
Abhishek_43 = Person("Abhishek", None)
Maniram_43 = Person("Maniram", None)
Uddhav_43 = Person("Uddhav", None)
Uttam_43 = Person("Uttam", None)
Dwarika_43 = Person("Dwarika", None)
KrishnaPrasad_43 = Person("KrishnaPrasad", None)
Purushottam_43_2 = Person("Purushottam", None)
Uday_43 = Person("Uday", None)

Hirav_44 = Person("Hirav", None)
Harisharan_44 = Person("Harisharan", None)
Shivasharan_44 = Person("Shivasharan", None)
Sashindra_44 = Person("Sashindra", None)
Krishnasharan_44 = Person("Krishnasharan", None)
LabaPrasad_44 = Person("LabaPrasad", None)

Hirav_44 = Person("Hirav", None)
Harisharan_44 = Person("Harisharan", None)
Shivasharan_44 = Person("Shivasharan", None)
Sashindra_44 = Person("Sashindra", None)
Krishnasharan_44 = Person("Krishnasharan", None)
LabaPrasad_44 = Person("LabaPrasad", None)

Pitabmar_41 = Person("Pitabmar", None)
Muktinath_41 = Person("Muktinath", None)
Minanath_41 = Person("Minanath", None)

Harischandra_42 = Person("Harischandra", None)
Shreeram_42 = Person("Shreeram", None)
Harisharan_42 = Person("Harisharan", None)
Harinath_42 = Person("Harinath", None)
Sharadprasad_42 = Person("Sharadprasad", None)

#page 36
Bali_34 = Person("Bali", None)
Moksheswor_35 = Person("Moksheswor", None)
Sreeram_35 = Person("Sreeram", None)
Ramkrishna_35 = Person("Ramkrishna", None, death_year=1822, place="Lubhu")
Bamdev_35 = Person("Bamdev", None)

Chandramadi_36 = Person("Chandramadi", None)
Tikaram_37 = Person("Tikaram", None)
Laxmidhar_37 = Person("Laxmidhar", None)
Liladhar_37 = Person("Liladhar", None)

Haribas_38 = Person("Haribas", None)
Shivanath_38 = Person("Shivanath", None)

Shyamlal_39 = Person("Shyamlal", None)
Laxminath_39_2 = Person("Laxminath", None)
Narayan_39 = Person("Narayan", None)
VishwoNath_39 = Person("VishwoNath", None)
Makardwoj_39 = Person("Makardwoj", None)
Ganapati_39_2 = Person("Ganapati", None)

Shreebilas_40 = Person("Shreebilas", None)
Hitakanta_40 = Person("Hitakanta", None)
Gajabinod_40 = Person("Gajabinod", None)
Nandalal_40 = Person("Nandalal", None)
Sashidhar_40 = Person("Sashidhar", None)
Chiranjibi_40 = Person("Chiranjibi", None)

Sadananda_41 = Person("Sadananda", None)
Narandutta_41 = Person("Narandutta", None)
Chandrakanta_41 = Person("Chandrakanta", None)
Chabilal_41 = Person("Chabilal", None)
Tankanath_41 = Person("Tankanath", None)
Khomnath_41 = Person("Khomnath", None)
VishwoNath_41 = Person("VishwoNath", None)
Sukadev_41 = Person("Sukadev", None)
Gangasagar_41 = Person("Gangasagar", None)

#Page 37
Gopilal_42 = Person("Gopilal", None)
Hemnath_42 = Person("Hemnath", None)
Gopal_42_2 = Person("Gopal", None)
Rishi_42 = Person("Rishi", None)
Laxminath_42 = Person("Laxminath", None)
GopiKrishna_42 = Person("GopiKrishna", None)
Bhojraj_42 = Person("Bhojraj", None)
Muktinath_42 = Person("Muktinath", None)
Narayan_42 = Person("Narayan", None)

SashyamPrasad_43 = Person("SashyamPrasad", None)
RamKrishna_43 = Person("RamKrishna", None)
ShyamPrasad_43 = Person("ShyamPrasad", None)
Madhu_43_2 = Person("Madhu", None)
Hari_43 = Person("Hari", None)
Ishwor_43 = Person("Ishwor", None)
Niranjan_43 = Person("Niranjan", None)
Gokul_43 = Person("Gokul", None)
PurnaPrasad_43 = Person("PurnaPrasad", None)
Saroj_43 = Person("Saroj", None)
Bhairav_43 = Person("Bhairav", None)
GyanPrasad_43 = Person("GyanPrasad", None)
BinodPrasad_43 = Person("BinodPrasad", None)

Byapak_43 = Person("Byapak", None)
Binay_43 = Person("Binay", None)
Prajyan_43 = Person("Prajyan", None)
Pawan_43 = Person("Pawan", None)
Murari_43 = Person("Murari", None)

Taranath_43 = Person("Taranath", None)
SivaPrasad_44 = Person("SivaPrasad", None)
SitaRam_44 = Person("SitaRam", None)

Dasrath_44 = Person("Dasrath", None)
Gokul_44 = Person("Gokul", None)
Ashok_44_2 = Person("Ashok", None)
Surya_44 = Person("Surya", None)
ChandikaPrasad_44 = Person("ChandikaPrasad", None)
Niranjan_44 = Person("Niranjan", None)

UllasPunja_45 = Person("UllasPunja", None)

#Page 38
PurnaBhadra_38 = Person("PurnaBhadra", None)
HariLal_39_2 = Person("HariLal", None)
GauriKanta_39 = Person("GauriKanta", None)
Modnath_39 = Person("Modnath", None)

Dilliram_40 = Person("Dilliram", None)
Chakrapani_40_2 = Person("Chakrapani", None)
GaneshPrasad_40 = Person("GaneshPrasad", None)
RatnaPrasad_40 = Person("RatnaPrasad", None)
Dandapani_40_2 = Person("Dandapani", None)
PadmaNarayan_40 = Person("PadmaNarayan", None)

BishnuPrasad_41 = Person("BishnuPrasad", None)
DurgaPrasad_41 = Person("DurgaPrasad", None)
Sudarshan_41 = Person("Sudarshan", None)
KrishnaPrasad_41_2 = Person("KrishnaPrasad", None)
Gopal_41_2 = Person("Gopal", None)

Uddhav_42 = Person("Uddhav", None)
Shyam_42_1 = Person("Shyam", None)
KrishnaPrasad_42 = Person("KrishnaPrasad", None)
Baikuntha_42 = Person("Baikuntha", None)
Ramesh_42 = Person("Ramesh", None)
Dinesh_42 = Person("Dinesh", None)
Saroj_42 = Person("Saroj", None)
Basanta_42 = Person("Basanta", None)
Niraj_42 = Person("Niraj", None)
Rajan_42 = Person("Rajan", None)
Rajesh_42_1 = Person("Rajesh", None)
Bhusan_42 = Person("Bhusan", None)
Ashok_42 = Person("Ashok", None)
Shreeram_42_1 = Person("Shreeram", None)
Mukunda_42_1 = Person("Mukunda", None)
Madhuwan_42 = Person("Madhuwan", None)
Madhav_42_2 = Person("Madhav", None)

Deepak_43_2 = Person("Deepak", None)
Suchit_43 = Person("Suchit", None)
Pawan_43_2 = Person("Pawan", None)
Sourya_43 = Person("Sourya", None)
Saurav_43 = Person("Saurav", None)

Santosh_43 = Person("Santosh", None)
Saroj_43_2 = Person("Saroj", None)
Mahesh_43_2 = Person("Mahesh", None)
Anupam_43 = Person("Anupam", None)

#Page 39
Pashupati_38 = Person("Pashupati", None)
Ganapati_38 = Person("Ganapati", None)

Padmanath_39 = Person("Padmanath", None)
Kashinath_39_2 = Person("Kashinath", None)
Umanath_39 = Person("Umanath", None)

Kalu_40 = Person("Kalu", None)
Muktinath_40 = Person("Muktinath", None)
Sadananda_40 = Person("Sadananda", None)
Emanath_40 = Person("Emanath", None)
Bhimnath_40 = Person("Bhimnath", None)
Narayan_40 = Person("Narayan", None)

Sukadev_41_2 = Person("Sukadev", None)
Dalbahadur_41 = Person("Dalbahadur", None)
Gopal_41_3 = Person("Gopal", None)
Ramjeev_41 = Person("Ramjeev", None)
Shyamjeev_41 = Person("Shyamjeev", None)
Sahadev_41 = Person("Sahadev", None)
Arjun_41 = Person("Arjun", None)
Prahlad_41 = Person("Prahlad", None)
Kamal_41 = Person("Kamal", None)
Ram_41 = Person("Ram", None)
Krishna_41 = Person("Krishna", None)
Bharat_41 = Person("Bharat", None)

Nanibabu_42 = Person("Nanibabu", None)
Rameshor_42 = Person("Rameshor", None)
Achyut_42 = Person("Achyut", None)
Shreeram_42_2 = Person("Shreeram", None)
ShyamKrishna_42 = Person("ShyamKrishna", None)
ShyamKaji_42 = Person("ShyamKaji", None)
HariKrishna_42 = Person("HariKrishna", None)
Sundar_42 = Person("Sundar", None)
Bidur_42 = Person("Bidur", None)
Purushottam_42 = Person("Purushottam", None)
Krishnasharan_42 = Person("Krishnasharan", None)
Jayaraj_42 = Person("Jayaraj", None)
Sudama_42 = Person("Sudama", None)
Suresh_42 = Person("Suresh", None)
Govinda_42_1 = Person("Govinda", None)
Sambhu_42 = Person("Sambhu", None)

Nabaraj_43 = Person("Nabaraj", None)
Chitra_43 = Person("Chitra", None)
Habbu_43 = Person("Habbu", None)
Kailash_43 = Person("Kailash", None)
Umesh_43 = Person("Umesh", None)
Radheshyam_43 = Person("Radheshyam", None)
Ganashyam_43 = Person("Ganashyam", None)
Dinesh_43_2 = Person("Dinesh", None)

#Page 40
Su_Ramnath_36 = Person("Su_Ramnath", None)
Prabhunath_36 = Person("Prabhunath", None)
Ranganath_36 = Person("Ranganath", None)
Siromani_36 = Person("Siromani", None)
Trilokya_36 = Person("Trilokya", None)

Su_Brajmohan_37 = Person("Su_Brajmohan", None)
Yagyanidhi_37 = Person("Yagyanidhi", None)
Ganapati_37 = Person("Ganapati", None)

Krishnamohan_38 = Person("Krishnamohan", None)
Lalitmohan_38 = Person("Lalitmohan", None)
Chaturmohan_38 = Person("Chaturmohan", None)
Chandramohan_38 = Person("Chandramohan", None)

Harimohan_39 = Person("Harimohan", None)
Rudramohan_39 = Person("Rudramohan", None)
Lokmohan_39 = Person("Lokmohan", None)
Ganeshmohan_39 = Person("Ganeshmohan", None)
Premmohan_39 = Person("Premmohan", None)
Yogmohan_39 = Person("Yogmohan", None)
Buddhimohan_39 = Person("Buddhimohan", None)

RamPrasad_40 = Person("RamPrasad", None)
Narayan_40_2 = Person("Narayan", None)
Dhruvamohan_40 = Person("Dhruvamohan", None)
Tejmohan_40 = Person("Tejmohan", None)
Harshamohan_40 = Person("Harshamohan", None)
Yankamohan_40 = Person("Yankamohan", None)

Padmanav_41 = Person("Padmanav", None)
Binod_41 = Person("Binod", None)
Pramod_41 = Person("Pramod", None)
Amrit_41 = Person("Amrit", None)
Damodar_41 = Person("Damodar", None)
Radhakrishna_41 = Person("Radhakrishna", None)
Bamshidhar_41 = Person("Bamshidhar", None)
Yadav_41 = Person("Yadav", None)
Suraj_41 = Person("Suraj", None)
Suman_41 = Person("Suman", None)
Sanjay_41 = Person("Sanjay", None)

#Page 41
Sunod_42 = Person("Sunod", None)
Sushan_42 = Person("Sushan", None)
Ramesh_42_2 = Person("Ramesh", None)
Pradeep_42 = Person("Pradeep", None)
Prakash_42 = Person("Prakash", None)
Kumud_42 = Person("Kumud", None)
Enoj_42 = Person("Enoj", None)
Manoj_42 = Person("Manoj", None)
Anil_42 = Person("Anil", None)

Brahmananda_38 = Person("Brahmananda", None)
Gaurinath_38 = Person("Gaurinath", None)
Ambarnath_38 = Person("Ambarnath", None)
Rewatiraman_38 = Person("Rewatiraman", None)
Ramakanta_38 = Person("Ramakanta", None)
Pradhumna_38 = Person("Pradhumna", None)
Kabikulkeshari_38 = Person("Kabikulkeshari", None)
Sadananda_38 = Person("Sadananda", None)
Kashinath_38 = Person("Kashinath", None)
Tejprasad_38 = Person("Tejprasad", None)

Yojmohan_39 = Person("Yogmohan", None)
KrishnaDutta_39 = Person("KrishnaDutta", None)
Pitabmar_39 = Person("Pitabmar", None)
VishwoNath_39_2 = Person("VishwoNath", None)
Chiranjibi_39 = Person("Chiranjibi", None)
Tejprasad_39 = Person("Tejprasad", None)
Maila_39 = Person("Maila", None)
Jeevprasad_39 = Person("Jeevprasad", None)
Tankanath_39 = Person("Tankanath", None)
YudhPrasad_39 = Person("YudhPrasad", None)
Bhure_39 = Person("Bhure", None)
Gwage_39 = Person("Gwage", None)
Jhankanath_39 = Person("Jhankanath", None)
Homnath_39 = Person("Homnath", None)
MayaPrasad_39 = Person("MayaPrasad", None)

TejPrasad_40 = Person("TejPrasad", None)
Tejpinath_40 = Person("Tejpinath", None)
KrishnaPrasad_40 = Person("KrishnaPrasad", None)
DeviPrasad_40 = Person("DeviPrasad", None)
PremRaj_40 = Person("PremRaj", None)
PushpaRaj_40 = Person("PushpaRaj", None)
Thute_40 = Person("Thute", None)

Ramji_41 = Person("Ramji", None)
Ramraj_41 = Person("Ramraj", None)
Laxman_41 = Person("Laxman", None)

Vidyaraj_42 = Person("Vidyaraj", None)
Nabaraj_42 = Person("Nabaraj", None)
Raju_42 = Person("Raju", None)
Ratna_42 = Person("Ratna", None)
Vijay_42 = Person("Vijay", None)

#page 42
Narad_36 = Person("Narad", None)
Dinakar_36 = Person("Dinakar", None)
Prabhakar_36 = Person("Prabhakar", None)
Antare_36 = Person("Antare", None)
Kancha_36 = Person("Kancha", None)

Laxmikanta_37 = Person("Laxmikanta", None, place="Ekhudol")
Chandrasekhar_37 = Person("Chandrasekhar", None)
Baburam_37 = Person("Baburam", None)

Nandalal_38 = Person("Nandalal", None)
Harinanda_38 = Person("Harinanda", None)
Chandrakanta_38 = Person("Chandrakanta", None)

Agnidhar_39 = Person("Agnidhar", None)
Yadunath_39 = Person("Yadunath", None)
Gurudutta_39 = Person("Gurudutta", None)
Dharmananda_39 = Person("Dharmananda", None)
Bedimadhav_39 = Person("Bedimadhav", None)
Govinda_39 = Person("Govinda", None)
Damodar_39 = Person("Damodar", None)

Jagannath_40 = Person("Jagannath", None)
Ramji_39 = Person("Ramji", None)
Bholanath_39 = Person("Bholanath", None)
Madhav_39 = Person("Madhav", None)
Nabaraj_39 = Person("Nabaraj", None)

#page 43
Binod_41_2 = Person("Binod", None)
Bijayanath_41 = Person("Bijayanath", None)
Pramod_41_2 = Person("Pramod", None)
Subodh_41 = Person("Subodh", None)
Nayanath_41 = Person("Nayanath", None)
Samanath_41 = Person("Samanath", None)
Brihaspati_41 = Person("Brihaspati", None)
Rukhmanath_41 = Person("Rukhmanath", None)
Grihanath_41 = Person("Grihanath", None)
Shankar_41_2 = Person("Shankar", None)
Deepak_41 = Person("Deepak", None)
Sudarshan_41_2 = Person("Sudarshan", None)
Nirmal_41 = Person("Nirmal", None)

Ajay_42 = Person("Ajay", None)
Sanjay_42 = Person("Sanjay", None)
Pradeep_42_1 = Person("Pradeep", None)
Uttam_42 = Person("Uttam", None)
Bodhnath_42 = Person("Bodhnath", None)
Heli_42 = Person("Heli", None)
Heman_42 = Person("Heman", None)
Sabij_42 = Person("Sabij", None)
Anish_42 = Person("Anish", None)
Manish_42 = Person("Manish", None)

Damodar_37 = Person("Damodar", None)
Mitralal_37 = Person("Mitralal", None)
Sadananda_37 = Person("Sadananda", None)

Chetnath_38 = Person("Chetnath", None)

Badri_39 = Person("Badri", None, place="Koteshor")
Mahesh_40 = Person("Mahesh", None)
Shyamhari_40 = Person("Shyamhari", None)

#Page 44
Maheshwor_38 = Person("Maheshwor", None)
ShivaDutta_38_2 = Person("ShivaDutta", None)
Wahaba_38 = Person("Wahaba", None)
Birava_38 = Person("Birava", None)
Bhairaba_38 = Person("Bhairaba", None)
Katakaba_38 = Person("Katakaba", None)
Amaraba_38 = Person("Amaraba", None)

Bhuwaneshor_39 = Person("Bhuwaneshor", None)
GaneshDutta_39 = Person("GaneshDutta", None)

ShivaPrasad_40 = Person("ShivaPrasad", None)
Sthaleshor_40 = Person("Sthaleshor", None)
Ranganath_40 = Person("Ranganath", None)
Fadindranath_40 = Person("Fadindranath", None)
DeviPrasad_40_1 = Person("DeviPrasad", None)
Jhankanath_40 = Person("Jhankanath", None)
Homanath_40 = Person("Homanath", None)

Kedarav_41 = Person("Kedarav", None)
Krishnav_41 = Person("Krishnav", None)
Arjunav_41 = Person("Arjunav", None)
BadriPrasad_41 = Person("BadriPrasad", None)
ShyamPrasad_41 = Person("ShyamPrasad", None)
DamodarPrasad_41 = Person("DamodarPrasad", None)
Jagannath_41 = Person("Jagannath", None)
Tarkaraj_41 = Person("Tarkaraj", None)
Chiranjibi_41 = Person("Chiranjibi", None)
Rishi_41 = Person("Rishi", None)
Hari_41 = Person("Hari", None)
Shyam_41 = Person("Shyam", None)
Ramhari_41 = Person("Ramhari", None)

VishwoNath_42_1 = Person("VishwoNath", None)
BadriPrasad_42_1 = Person("BadriPrasad", None)
Kiran_42 = Person("Kiran", None)
Ravi_42 = Person("Ravi", None)
Mani_42 = Person("Mani", None)
Kumar_42 = Person("Kumar", None)
Jeewan_42_1 = Person("Jeewan", None)

Diwakar_43_2 = Person("Diwakar", None)
Prabhakar_43 = Person("Prabhakar", None)
Suman_43 = Person("Suman", None)
Sagar_43 = Person("Sagar", None)
Sudhakar_43 = Person("Sudhakar", None)
Bhaskar_43 = Person("Bhaskar", None)
Sankar_43 = Person("Sankar", None)
Mahesh_43_3 = Person("Mahesh", None)

#Page 45
_4 = Person("Yogmohan", None)
#####################################################
gopal_31.add_child(ram_bhadra_32)
ram_bhadra_32.add_childs([govinda_33, prajapati_33, chamu_33])
govinda_33.add_childs([gautam_34, Bali_34])
gautam_34.add_childs([laxmidhar_35, ramchandra_35, devhari_kancha_35])
laxmidhar_35.add_childs([laxminarayan_36, Rambhadra_36])
laxminarayan_36.add_child(VidyaNanda_37)
VidyaNanda_37.add_child(DharmaNanda_38)
DharmaNanda_38.add_child(HariLal_39)
HariLal_39.add_child(ShivaNidhi_40)

ShivaNidhi_40.add_childs([GedLal_41, Lekhnath_41, Premnath_41])
GedLal_41.add_child(Eknath_42)
Lekhnath_41.add_childs([Ram_42, Krishna_42, Badri_42, VishwoNath_42])
PremNath_41.add_child(AatmaRam_42)
Ram_42.add_child(Ananta_43)
Krishna_42.add_childs([Harihar_43, Binod_43])
Harihar_43.add_child(Praveen_44)
Binod_43.add_child(Vivek_44)

Badri_42.add_childs([Pramod_43, Amod_43, Arun_43])
Pramod_43.add_child(Prashant_44)

VishwoNath_42.add_child(ShivaNath_43)
AatmaRam_42.add_childs([Deepak_43, Diwakar_43])

Rambhadra_36.add_child(Ghanashyam_37)
Ghanashyam_37.add_childs([ShivaDutta_38, BishnuDutta_38, RamDutta_38, HariDutta_38])
RamDutta_38.add_childs([Padmalochan_39, Buddhinath_39, Laxminath_39, Jeewanath_39, Kashinath_39])
Laxminath_39.add_childs([Chakrapani_40, Dandapani_40])
Chakrapani_40.add_childs([GuruPrasad_41, Gunaraj_41, Ramanath_41, Balaram_41, Dilliram_41])
GuruPrasad_41.add_childs([Dhruva_42, Ishwori_42])
Gunaraj_41.add_childs([Suryamani_42])
Suryamani_42.add_child(Mahesh_43)
Ramanath_41.add_childs([Janardan_42, Raghu_42])
Balaram_41.add_childs([Sudarshan_42, Gokul_42, Madan_42])
Dilliram_41.add_childs([Madhav_42, Parshuram_42])
Dhruva_42.add_childs([Rishiram_43, Rajan_43])
Ishwori_42.add_childs([Chiranjibi_43, Uttam_43, Narottam_43])

Dandapani_40.add_childs([Toyanath_41, KrishnaPrasad_41])
Toyanath_41.add_childs([SitaRam_42])
SitaRam_42.add_childs([Purushottam_43, Basanta_43, Bishwonath_43, Damodar_43])
Jeewanath_39.add_childs([Badibilas_40, Bavanath_40, Naranath_40, GaneshDutta_40])
Badibilas_40.add_childs([Bhuminanda_41, Buddhinath_41])
GaneshDutta_40.add_child(Angirash_41)
Angirash_41.add_childs([Bishnugopal_42, Kedar_42, Hariprasad_42, Parasar_42])
Dillinath_42.add_childs([Ram_43, Laxman_43])
Buddhinath_41.add_childs([Basudev_42, Debarshi_42, Mukunda_42])
Basudev_42.add_child(Ramhari_43)
Debarshi_42.add_childs([Haribol_43, Anup_43, Binod_43, Sanod_43])
Mukunda_42.add_childs([Suresh_43, Dinesh_43])

Bishnugopal_42.add_childs([Narayan_43, Bhagawan_43, Pushpa_43, Madhu_43])
Kedar_42.add_child(Kalyan_43)
Hari_42.add_childs([Sudhir_43, Prabakar_43])
Parasar_42.add_child(Sunil_43)

Narayan_43.add_child(Aashish_44)
Aashish_44.add_childs([Aayan_45, Adwik_45])
Kalyan_43.add_child(Samyog_44)

Bhagawan_43.add_child(Pravesh_44)
Pushpa_43.add_childs([Suraj_44, Niraj_44])
Madhu_43.add_child(Kushal_44)

#page 29
devhari_kancha_35.add_child(Rishi_36)
Rishi_36.add_childs([HariNarayan_37])
HariNarayan_37.add_childs([ShreeLal_38, RamNath_38])
ShreeLal_38.add_child(Narandutta_39)
RamNath_38.add_child(Kedarnath_39)

#page 30



